### ISSUE TITLE
hashcat on iMac Pro with Vega 56

### ISSUE THREAD

**Issue by guru431** [hashcat/hashcat#1497] opened 2018-01-23 18:32 UTC
I have a new iMac Pro with a video card AMD Radeon Vega 56.
The iMac has two operating systems: macOS High Sierra and Windows 10.
In both of them I tried to run hashcat benchmark.
And under macOS, the speed of hashcat is almost two times lower.
Why is this happening?

Windows:

hashcat64 -m 2500 -w 3 -b
hashcat (v4.0.1) starting in benchmark mode...

OpenCL Platform #1: Advanced Micro Devices, Inc.
================================================
* Device #1: gfx901, 6732/8176 MB allocatable, 56MCU
* Device #2: Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz, skipped.

Benchmark relevant options:
===========================
* --workload-profile=3

Hashmode: 2500 - WPA/WPA2

Speed.Dev.#1.....:   352.0 kH/s (77.70ms)

macOS:

hashcat -m 2500 -w 3 -b
hashcat (v4.0.1) starting in benchmark mode...

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz, skipped.
* Device #2: AMD Radeon Pro Vega 56 Compute Engine, 2044/8176 MB allocatable, 56MCU

Benchmark relevant options:
===========================
* --workload-profile=3

Hashmode: 2500 - WPA/WPA2

Speed.Dev.#2.....:   199.8 kH/s (68.96ms)

**Comment by neheb** [comment] 2018-01-23 19:10
Because Apple's drivers suck. Simple as that.

**Comment by guru431** [comment] 2018-01-23 19:59
To use Windows is the only way out?
I basically have to work in macOS. Can there is still some way to raise the speed? Is there something similar to the -w 3 key or can there be unofficial patched drivers for Vega?

**Comment by neheb** [comment] 2018-01-23 20:28
Let's see. You could virtualize the GPU. Maybe?

ssh into a system which is properly set up (Windows or Linux). 

I woudln't hold my breath for Apple to make proper drivers. One research area would be to see if Apple's OpenCL runtime allows inline assembly so that some of the more advanced features of Vega can be used. Don't hold your breath though.

**Comment by emwinkler** [comment] 2018-01-31 17:00
Have you tried version 3.5.0?  I too am running MacOS High Sierra 10.13.3, but with an AMD RX 580 in eGPU on a Macbook Air.  I see terrible benchmarks with v4.0.1 as seen below.

hashcat-3.5.0 results:
./hashcat -m 2500 -w 3 -b -d 3
hashcat () starting in benchmark mode...

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz, skipped.
* Device #2: HD Graphics 5000, skipped.
* Device #3: AMD Radeon RX 580 Compute Engine, 2048/8192 MB allocatable, 36MCU

Hashtype: WPA/WPA2

Speed.Dev.#3.....:   214.1 kH/s (83.32ms)


hashcat-4.0.1 results:
./hashcat -m 2500 -w 3 -b -d 3
hashcat (v4.0.1) starting in benchmark mode...

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz, skipped.
* Device #2: HD Graphics 5000, skipped.
* Device #3: AMD Radeon RX 580 Compute Engine, 2048/8192 MB allocatable, 36MCU

Benchmark relevant options:
===========================
* --opencl-devices=3
* --workload-profile=3

Hashmode: 2500 - WPA/WPA2

Speed.Dev.#3.....:    59432 H/s (72.00ms)

**Comment by jsteube** [comment] 2018-02-01 08:26
I can't reproduce with almost the same GPU (RX480).

v4.1.0 (it's the RC1 of v4.0.1 - no kernel changes):

```
root@sf:~/hashcat# ./hashcat -b -m 2500
hashcat (v4.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Advanced Micro Devices, Inc.
================================================
* Device #1: Ellesmere, 3254/4077 MB allocatable, 36MCU

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 2500 - WPA/WPA2 (Iterations: 4096)

Speed.Dev.#1.....:   173.8 kH/s (52.28ms)

Started: Thu Feb  1 09:19:45 2018
Stopped: Thu Feb  1 09:20:08 2018
root@sf:~/hashcat# ./hashcat -b -m 2500 -w 3
hashcat (v4.1.0) starting in benchmark mode...

OpenCL Platform #1: Advanced Micro Devices, Inc.
================================================
* Device #1: Ellesmere, 3254/4077 MB allocatable, 36MCU

Benchmark relevant options:
===========================
* --workload-profile=3

Hashmode: 2500 - WPA/WPA2 (Iterations: 4096)

Speed.Dev.#1.....:   174.0 kH/s (102.26ms)

Started: Thu Feb  1 09:20:15 2018
Stopped: Thu Feb  1 09:20:28 2018
```

v3.5.0:

```
root@sf:~/hashcat# ./hashcat -b -m 2500 -w 3
hashcat (v3.5.0) starting in benchmark mode...

OpenCL Platform #1: Advanced Micro Devices, Inc.
================================================
* Device #1: Ellesmere, 3829/4077 MB allocatable, 36MCU

Hashtype: WPA/WPA2

Speed.Dev.#1.....:   173.1 kH/s (105.89ms)

Started: Thu Feb  1 09:21:21 2018
Stopped: Thu Feb  1 09:21:32 2018
```

Same speed. Without being able to reproduce I can't fix it.

**Comment by jsteube** [comment] 2018-02-01 16:05
I've add some code to disable code caching, a shot in the dark. Can you please pull master, recompile and retry?

**Comment by emwinkler** [comment] 2018-02-01 20:40
I will test later and let you know.  I do know that it only occurs with hashmode 2500.  All others benchmark equally or better with 4.0.1.

**Comment by emwinkler** [comment] 2018-02-02 20:08
Same result with latest version 4.1.0.  I :
./hashcat -b -m 2500 -d 3
hashcat (v4.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz, skipped.
* Device #2: HD Graphics 5000, skipped.
* Device #3: AMD Radeon RX 580 Compute Engine, 2048/8192 MB allocatable, 36MCU

Benchmark relevant options:
===========================
* --opencl-devices=3
* --optimized-kernel-enable

Hashmode: 2500 - WPA/WPA2 (Iterations: 4096)

Speed.Dev.#3.....:    58793 H/s (72.83ms)

Started: Fri Feb  2 14:52:50 2018
Stopped: Fri Feb  2 14:53:07 2018

I went back and tested old versions of hashcat I had and the issue starts in all 4.0 versions I have.  3.6 versions have no issue as shown below:

./hashcat -b -m 2500 -d 3
hashcat (v3.6.0-3-ge87fb31d) starting in benchmark mode...

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz, skipped.
* Device #2: HD Graphics 5000, skipped.
* Device #3: AMD Radeon RX 580 Compute Engine, 2048/8192 MB allocatable, 36MCU

Hashtype: WPA/WPA2

Speed.Dev.#3.....:   201.4 kH/s (83.16ms)

Started: Fri Feb  2 15:05:56 2018
Stopped: Fri Feb  2 15:06:03 2018

**Comment by jsteube** [comment] 2018-02-03 12:58
I've add some more code to change certain parameters, another shot in the dark, since I do not have access to that system and can not reproduce locally. Can you please pull master, recompile and retry again?

**Comment by emwinkler** [comment] 2018-02-03 16:10
Same result.

./hashcat -b -m 2500 -d 3     
hashcat (v4.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz, skipped.
* Device #2: HD Graphics 5000, skipped.
* Device #3: AMD Radeon RX 580 Compute Engine, 2048/8192 MB allocatable, 36MCU

Benchmark relevant options:
===========================
* --opencl-devices=3
* --optimized-kernel-enable

Hashmode: 2500 - WPA/WPA2 (Iterations: 4096)

Speed.Dev.#3.....:    76867 H/s (54.31ms) @ Accel:1024 Loops:8 Thr:64 Vec:1

Started: Sat Feb  3 11:05:38 2018
Stopped: Sat Feb  3 11:06:03 2018

**Comment by philsmd** [comment] 2018-02-03 17:09
Are we actually sure that this is not the same problem reported here: #1290 ?

@emwinkler can you please make the test mentioned here: https://github.com/hashcat/hashcat/issues/1290#issuecomment-338306987

**Comment by jsteube** [comment] 2018-02-13 08:18
Please retry with latest github master version. It's important to run make clean this time.

**Comment by emwinkler** [comment] 2018-02-13 16:00
Whatever you changed fixed the benchmark speed for my AMD Radeon RX 580:

Hashmode: 2500 - WPA/WPA2 (Iterations: 4096)

Speed.Dev.#3.....:   213.6 kH/s (85.01ms) @ Accel:128 Loops:64 Thr:256 Vec:1

**Comment by jsteube** [comment] 2018-02-14 10:48
Please redo the test with latest github master. Had to do some change because this workaround made other hash-modes no longer working. But with a bit of luck the latest changes lead to the same result.

**Comment by emwinkler** [comment] 2018-02-14 14:13
The change you made breaks the benchmark speed for my AMD Radeon RX 580.  It is slow again:

Hashmode: 2500 - WPA/WPA2 (Iterations: 4096)

Speed.Dev.#3.....:    62451 H/s (72.57ms) @ Accel:64 Loops:32 Thr:256 Vec:1

**Comment by jsteube** [comment] 2018-02-14 16:47
Pull again and retry please

**Comment by emwinkler** [comment] 2018-02-14 17:19
No change.  Still the slow benchmark.

Hashmode: 2500 - WPA/WPA2 (Iterations: 4096)

Speed.Dev.#3.....:    62638 H/s (72.42ms) @ Accel:64 Loops:32 Thr:256 Vec:1

**Comment by emwinkler** [comment] 2018-02-26 15:55
Running on the same hardware after booting into Ubuntu 16.04, I get normal benchmarks with the RX 580.  Looks to be a macOS driver issue as you suggest.

OpenCL Platform #1: Intel(R) Corporation
========================================
* Device #1: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz, skipped.

OpenCL Platform #2: Advanced Micro Devices, Inc.
================================================
* Device #2: Ellesmere, 4048/6472 MB allocatable, 36MCU

Benchmark relevant options:
===========================
* --opencl-devices=2
* --optimized-kernel-enable

Hashmode: 2500 - WPA/WPA2 (Iterations: 4096)

Speed.Dev.#2.....:   212.3 kH/s (85.51ms) @ Accel:128 Loops:64 Thr:256 Vec:1

**Comment by jsteube** [comment] 2019-03-16 10:02
The issue should be fixed, can you please retry with the latest version from GitHub master and close this issue?

**Comment by jsteube** [comment] 2019-04-18 17:15
deep update for -m 2500. please retry with latest version from github master

**Comment by emwinkler** [comment] 2019-04-22 20:50
OpenCL build errors are present.

./hashcat -b -m 2500 -d 3
hashcat (v5.1.0-943-gbf4b1a8e) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz, skipped.
* Device #2: Intel(R) UHD Graphics 630, skipped.
* Device #3: AMD Radeon RX Vega 64 Compute Engine, 2044/8176 MB allocatable, 64MCU

Benchmark relevant options:
===========================
* --opencl-devices=3
* --optimized-kernel-enable

Hashmode: 2500 - WPA-EAPOL-PBKDF2 (Iterations: 4095)

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

Error returned by cvms_element_build_from_source
* Device #3: Kernel /hashcat/OpenCL/m02500-pure.cl build failed - proceeding without this device.


Started: Mon Apr 22 16:47:54 2019
Stopped: Mon Apr 22 16:48:23 2019

**Comment by emwinkler** [comment] 2019-04-23 14:11
Here is some more detail on the error from OpenCL using the export CL_LOG_ERRORS="stdout" on the command line with hashcat.  

[CL_DEVICE_NOT_AVAILABLE] : OpenCL Error : Error: Build Program driver returned (518)
Break on OpenCLErrorBreak to debug.
OpenCL Warning : clBuildProgram failed: could not build program for 0x1021d00 (AMD Radeon RX Vega 64 Compute Engine) (err:-2)
Break on OpenCLWarningBreak to debug.
[CL_BUILD_ERROR] : OpenCL Build Error : Compiler build log:
Error returned by cvms_element_build_from_source

**Comment by mike-lo** [comment] 2019-10-08 15:39
Hello, I have the same issue with hashcat on my iMac Pro 

```
clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

Error returned by cvms_element_build_from_source
* Device #2: Kernel /Users/mikelo/Tools/hashcat/OpenCL/m02500-pure.cl build failed - proceeding without this device.
```

is there any solution yet?

**Comment by jsteube** [comment] 2019-12-24 09:44
We successfully fixed a similar problem on OSX + Vega GPU. Maybe it helps for this issue as well. Please retry with new GitHub master version and make sure to have the kernels/ kernel cached removed first.

**Comment by jsteube** [comment] 2020-07-03 12:00
Please retry with hashcat 6.0.0 + 32 beta from https://hashcat.net/beta/ and reopen the issue if it still exists.

**Closed as completed by jsteube** 2020-07-03 12:00 UTC
