### ISSUE TITLE
Wordlist Slow Speed but Piping is way faster ?

### ISSUE THREAD

**Issue by HeIp** [hashcat/hashcat#2546] opened 2020-09-09 13:33 UTC
Hello is there a reason when I use a wordlist file the speed is like 12 Hashes per second?
For example : hashcat -w 4 -a 3 -m 2500 name.hccapx './list.txt'
![image](https://user-images.githubusercontent.com/31706214/92605203-71aaaa80-f27f-11ea-82d7-2ca495d05181.png)

Vs when I pipe the list : 
cat ./list.txt | hashcat -w 4 -a 3 -m 2500 name.hccapx
![image](https://user-images.githubusercontent.com/31706214/92605164-6788ac00-f27f-11ea-92b9-1f3c897f6c94.png)

**Comment by philsmd** [comment] 2020-09-11 08:39
The problem here is most probably that you didn't provide hashcat with enough work, see https://hashcat.net/faq/morework .

That's also the reason why it's important to always mention the full details: the most important thing here is missing i.e. what input size is provided to hashcat (how large is the dict ? how many lines etc) and why do you not use some work acceleration like rules etc 

The problem is that this is a well-known fact that you either need to provide enough work to hashcat or use rules to get full acceleration: this problem was answered already hundreds of times in the hashcat forum and even made it into the **most frequently asked questions** (FAQ).

You could also use `-S` to accomplish basically the same as with the pipe, i.e. use a different slow-candidates mode to provide the password candidates to hashcat devices etc.

I think we should close this issue, because it's a known fact that hashcat needs enough work to accelerate to the maximum possible. Please do not forget to close the issue @HeIp 

I also think that questions like this are more suitable for the hashcat forum, because we can't really do anything here. It's not really a source code bug, but just a misunderstanding about how GPU work and how hashcat can reach maximum acceleration. These questions have been already answered on the forum, so it should be enough to use the forum's search function to find the answers. Thx

**Comment by jsteube** [comment] 2020-09-11 11:26
Not enough work is one of the problems, but I think another problem here is using -a 3 with a wordlist. Hashcat will treat the wordlist as a maskfile. 

IOW, don't use -a 3.

**Closed as completed** 2020-09-11 11:26 UTC
