### ISSUE TITLE
Session restarts from save session !?!?!

### ISSUE THREAD

**Issue by HeIp** [hashcat/hashcat#2015] opened 2019-05-07 23:20 UTC
The command I am running:
`./hashcat --status --status-timer=1 -m 2500 HOME-FA4F-2.4.hccapx -w 3 --session FILENAME--restore -a 1 ./dicts/num.txt ./dicts/2.txt --force`

Which I see creates : FILENAME.log & FILENAME.restore
Throughout the process I see that 
The following line remains constant the whole session:
> Restore.Point....: 0/960000 (0.00%)

Through the whole process checkpoint is enabled(pressed c), then later press q to quit.
Then I run the following line:

> ./hashcat --session FILENAME--restore

Only to see the progress restart from 0%.
Someone please help!

Extra problem:
When cracking hashcat prompts the following:

> Cracking performance lower than expected?
> * Update your OpenCL runtime / driver the right way:
>   https://hashcat.net/faq/wrongdriver
> * Create more work items to make use of your parallelization power:
>   https://hashcat.net/faq/morework

And kills 1 of my 2 GPUS,
Examples :
Goes from
![image](https://user-images.githubusercontent.com/31706214/57339012-aa6fc800-70fd-11e9-94f4-b263b4662904.png)

To

![image](https://user-images.githubusercontent.com/31706214/57339029-be1b2e80-70fd-11e9-98e1-023c67b49d33.png)
Utilization litteraly goes to 0%, how can I stop that ? I want both to be actively @ 100%

**Comment by philsmd** [comment] 2019-05-08 05:29
First of all, do not use --force:
`You can use --force to override this, but do not report related errors.`

Do **NOT** report errors when using --force.

This questions/discussions are more suited for the hashcat forum https://hashcat.net/forum/ , the github issue tracker should be used to report (code) problems/bug or request new features etc. It's not very good/useful for user questions.
The forum already contains several interesting and helpful threads when it comes to --restore and restore points etc (also use the forum search function).

To troubleshoot the problem (without --force of course), we would also need much more information (on the forum) like how large the dictionaries are and how many hashes you load etc.

I would say it makes sense to close this issue and try to find help on the forum, if you really find nothing that already solves your problem by reading related forum threads (I doubt that), you could create a new forum thread and ask your question with much more details.

**Comment by HeIp** [comment] 2019-05-08 15:01
Sorry the --force part was trying to make the 2nd gpu work without going to 0% Utilization, would  I still need to go to the forums ?

**Comment by jsteube** [comment] 2019-05-08 18:12
The problem is that you are using -a 1 in combination with a slow hash (WPA). If the modifier is big, you have to wait for a long time to finish with "c". You can avoid this by using a more clever attack method, but that's something for the forum, not GitHub issue.

**Closed as completed by jsteube** 2019-05-08 18:12 UTC
