### ISSUE TITLE
No feedback using password mask file.

### ISSUE THREAD

**Issue by xflyboy** [hashcat/hashcat#1466] opened 2017-12-03 17:24 UTC
So i'm using following options on hashcat (v4.0.1-36-g75db4e56):
sudo hashcat -m 2500 -w 3 -a 3 -o outfile.txt --session=Cata Catamarca.hccapx mix.hcmask
hccapx contains multiple captures: 
Recovered........: 39/57 (68.42%) Digests, 5/16 (31.25%) Salts
hcmask file contains multiple known values and a at the bottom multiple mask lines.

After runing, hashcat runs known values ok, but first mask run makes hashcat completely ignore key entry and possibly halt the process (not sure if i explain myself clearly).
Last line:

> 
Session..........: Cata
Status...........: Exhausted
Hash.Type........: WPA/WPA2
Hash.Target......: Catamarca.hccapx
Time.Started.....: Fri Dec  1 09:37:54 2017 (4 hours, 2 mins)
Time.Estimated...: Fri Dec  1 13:40:39 2017 (0 secs)
Guess.Mask.......: ?d?d?d?d?d?d?d?d [8]
Guess.Queue......: 12/45 (26.67%)
Speed.Dev.#1.....:    59272 H/s (12.41ms)
Recovered........: 42/57 (73.68%) Digests, 7/16 (43.75%) Salts
Progress.........: 1600000000/1600000000 (100.00%)
Rejected.........: 0/1600000000 (0.00%)
Restore.Point....: 10000000/10000000 (100.00%)
Candidates.#1....: 62518397 -> 67646497
HWMon.Dev.#1.....: Temp: 74c Fan: 52% Util: 98% Core:1280MHz Mem:2700MHz Bus:16
[CAPS.tar.gz](https://github.com/hashcat/hashcat/files/1524988/CAPS.tar.gz)

[s]tatus [p]ause [b]ypass [c]heckpoint [q]uit => 
After that,S/C/Q does not work at all. process still runing for a couple of days, i guess, it's working with next mask which is 10 dig long.
Only CTRL C works.
pc@pc ~ $ date
Sun Dec  3 14:22:37 -03 2017
8 digits should have ended long ago.

Happened sames with RC2.
Running on Mint 18. I guess it have something to do with adding known values to hcmix file. Didnt happen when file had less that known values. No HW modification done lateley only OS requested updates. Last run was with RC2.
I will wait till 10digits run finishes and will try removing "known" values from hcmask file and run it again.

**Comment by philsmd** [comment] 2017-12-03 18:27
Do you have any Intel CPU OpenCL driver installed?
What does you setup look like (GPU / CPU)?

We saw some similar behaviour with intel drivers and AMD systems.
I think the problem there was that whenever the Intel OpenCL driver was installed hashcat was not interactive anymore (no key presses where registered etc).

If you have the Intel OpenCL driver installed, please try to use only your GPU driver (if possible) and therefore uninstall the Intel OpenCL driver for testing this.

Thanks

**Comment by xflyboy** [comment] 2017-12-03 18:47
You are correct. My bad i forgot to mention that i tried to install OpenCL drivers on my old Intel Xenon x5xxx processor without success. Since it was long time ago i completely forgot about it. Apologize.
Close the issue as N/A.
I'll see how to solve the issue. Thx for quick reply.

**Comment by philsmd** [comment] 2017-12-04 08:27
good that this problem was kind of resolved.

Please note that only you - the original reporter OP - (or the project owner) can close issues.
Could you please close the issue if you think that the problem is solved. thx

**Closed as completed** 2017-12-04 11:43 UTC
