### ISSUE TITLE
M2 mba not supported

### ISSUE THREAD

**Issue by miguelacaro** [hashcat/hashcat#3671] opened 2023-04-06 23:06 UTC
**Describe the bug**
M2 macbook air not supported

**To Reproduce**
```
hashcat -m 2500 capture.hccapx  repos/WiFiCrack/rockyou.txt
hashcat (v6.2.6) starting

* Device #2: Apple's OpenCL drivers (GPU) are known to be unreliable.
             You have been warned.

METAL API (Metal 306.3.5)
=========================
* Device #1: Apple M2, 8160/16384 MB, 10MCU

OpenCL API (OpenCL 1.2 (Dec 16 2022 20:37:40)) - Platform #1 [Apple]
====================================================================
* Device #2: Apple M2, skipped

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

The plugin 2500 is deprecated and was replaced with plugin 22000. For more details, please read: https://hashcat.net/forum/thread-10253.html

Started: Fri Apr  7 01:00:57 2023
Stopped: Fri Apr  7 01:00:57 2023
```

**Hardware/Compute device (please complete the following information):**
- Compute device name: M2, 2022
- OpenCL/CUDA driver name: OpenCL API (OpenCL 1.2 (Dec 16 2022 20:37:40)) - Platform #1 [Apple]
- OpenCL/CUDA driver version: 1.2
- OpenCL/CUDA driver source: [e.g. runtime installer/.exe installer]

**Hashcat version (please complete the following information):**
 - OS: mac OS
 - Distribution: Ventura
 - Version: 13.2.1 (22D68)

**Diagnostic output compute devices:**

**Comment by Chick3nman** [comment] 2023-04-06 23:13
Please reread the error message:
```
The plugin 2500 is deprecated and was replaced with plugin 22000. For more details, please read: https://hashcat.net/forum/thread-10253.html
```
MacOS is supported, your selected plugin is not.

This is not a bug and appears to just be user error, closing as such.

**Closed as completed by Chick3nman** 2023-04-06 23:13 UTC
Labels: bug
