### ISSUE TITLE
--show doesnt work as expected with "empty" second part of LM-hashes   

### ISSUE THREAD

**Issue by realSnoopy** [hashcat/hashcat#2968] opened 2021-09-07 13:55 UTC
we know, lm splits the given pw into 2*7chars, so when the pw is shorter than 7 chars, the second part of the hash will be aad3b435b51404ee [empty hash]

hashcat skips this part by default, because it is an empty hash BUT when using --show with such a short cracked pass it will result in
`pass[notfound]` and not in correct `pass`

**Comment by jsteube** [comment] 2021-09-15 10:39
Can't reproduce:

```
root@ht:~/hashcat# cat > hash
aad3b435b51404ee 
299bd128c1101fd6
root@ht:~/hashcat# ./hashcat -m 3000 hash --show
aad3b435b51404ee:
```

Also works in split mode:

```
root@ht:~/hashcat# cat hashcat.potfile 
7584248b8d2c9f9e:A
root@ht:~/hashcat# cat hash
7584248b8d2c9f9eaad3b435b51404ee
root@ht:~/hashcat# ./hashcat -m 3000 hash --show
7584248b8d2c9f9eaad3b435b51404ee:A
```

**Comment by realSnoopy** [comment] 2021-09-17 13:09
Windows 10 
hashcat (v6.2.4-53-ga1ec246c8)
using a batch (all vars are set correctly)
```
hashcat.exe ^
--logfile-disable ^
--hash-type !hash! ^
--show ^
--username ^
--outfile-format 2 ^
!tocrack! ^
--potfile-path !potfilepath!
```
-> same problem, tried (copied my mode-3000.potfile as hashcat.potfile)

`hashcat.exe -m 3000 --username LM.2crack --show`
-> same problem
cleaned my LM.2crack removing the usernames
`hashcat.exe -m 3000 LM.2crack --show`
-> same problem

due to the fact that LM is crackable in minutes, i think it is okay to post hashes here (you can delete them if not)
my output with/without usernames is always:

cf4feebcbddf396daad3b435b51404ee:HDL4[notfound]
8884fb011432c81eaad3b435b51404ee:2460[notfound]
f80c1ddb26ac964baad3b435b51404ee:GEDDES[notfound]

**Comment by jsteube** [comment] 2021-09-18 11:32
I can reproduce this, but it seems to be a windows only problem. On my first tests I did do them only on Linux since there was no indication the OS is relevant. On Linux it works as it should.

**Comment by jsteube** [comment] 2021-09-18 12:18
Fixed with commit https://github.com/hashcat/hashcat/commit/dbefc7e60eaa435b1cf567dd3c62b7e9edeed675

Many thanks for reporting.

New binary beta, up, too.

**Closed as completed by jsteube** 2021-09-18 12:18 UTC
Labels: bug
