### ISSUE TITLE
Combination Attack - Plaintext printed incomplete

### ISSUE THREAD

**Issue by s3inlc** [hashcat/hashcat#2122] opened 2019-07-19 08:45 UTC
When having a hash with a plaintext slightly longer than 31 chars, e.g (md5): 
```
55869721e8fcfe006a2e90a2f731c0f1:1234567890123456789012345678901234
```
and running this with the optimized kernel in -a 0 this obviously would not work, as the plain gets rejected due to length.

But when running with this with combination attack, e.g. using  12345678901234567890 as left part and 12345678901234 as right part, the hash gets cracked, but the plaintext is printed incomplete and cut after 31 chars:

```
$ ./hashcat -m 0 -O 55869721e8fcfe006a2e90a2f731c0f1 -a 1 combo1.txt combo2.txt
hashcat (v5.1.0-1243-gd1f473d) starting...

[...]

Host memory required for this attack: 408 MB

Dictionary cache hit:
* Filename..: combo1.txt
* Passwords.: 1
* Bytes.....: 21
* Keyspace..: 1

55869721e8fcfe006a2e90a2f731c0f1:1234567890123456789012345678901
                                                 
Session..........: hashcat
Status...........: Cracked
Hash.Name........: MD5
Hash.Target......: 55869721e8fcfe006a2e90a2f731c0f1
Time.Started.....: Fri Jul 19 10:43:20 2019 (0 secs)
Time.Estimated...: Fri Jul 19 10:43:20 2019 (0 secs)
Guess.Base.......: File (combo1.txt), Left Side
Guess.Mod........: File (combo2.txt), Right Side
Speed.#2.........:      340 H/s (0.06ms) @ Accel:64 Loops:1 Thr:512 Vec:1
Recovered........: 1/1 (100.00%) Digests
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 0/1 (0.00%)
Restore.Sub.#2...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidates.#2....: 1234567890123456789012345678901 -> 1234567890123456789012345678901

Started: Fri Jul 19 10:43:18 2019
Stopped: Fri Jul 19 10:43:21 2019
```

The last three chars are cut off on the printed found.
So it should either not accept the plain (as it is too long) or print it correctly as otherwise this leads to founds which are not correct.

**Comment by matrix** [comment] 2019-07-19 13:58
Hi @s3inlc, probably the issue is here:

https://github.com/hashcat/hashcat/blob/master/src/interface.c#L686-L687

```
            case ATTACK_KERN_COMBI:     pw_max = MIN (pw_max, PW_DICTMAX);
                                        break;

```

By comment out these two lines or replace MIN with MAX it work, but I don't know if this change breaks other flows (we need to do a more in-depth analysis).

The other interesting thing is that by adding -S to the command line the password is not found ...

Thanks :)

**Comment by jsteube** [comment] 2019-07-29 13:45
If we use -S, then the _a0 kernel is used which supports only up to length 31. Therefore it can't get cracked in -S mode.

**Comment by matrix** [comment] 2019-07-29 13:48
Yes, with -S it's ok that don't crack, but without -S the output password is truncated. I try find a way to truncate the input but I think it's not possible with combinator ..

**Comment by jsteube** [comment] 2019-07-29 13:49
I just wanted to explain this behavior:

> The other interesting thing is that by adding -S to the command line the password is not found ...

It's correct this way.

**Comment by jsteube** [comment] 2019-07-29 14:12
Fixed with https://github.com/hashcat/hashcat/commit/e76c3de86a063b9ca46bf521c42caac571ae5b10
Thanks for reporting!

**Closed as completed by jsteube** 2019-07-29 14:12 UTC
