### ISSUE TITLE
charsets: Permission denied on hashcat 3.40 (docs: Permission denied on 3.40-38-gf651f44)

### ISSUE THREAD

**Issue by alphastar868** [hashcat/hashcat#1180] opened 2017-03-12 06:22 UTC
Trying to run hashcat (Using cmd.exe or HashcatGUI) results in Permission denied.

### Solutions attempted:
- Tried Hashcat beta as per #1006 
- Changed filesystem from NTFS to FAT32 (no permissions)
- _attrib *.* -r -s -h_ on hashcat-3.4.0 folder
- hashcat64 from _Administrator: Command Prompt_ only

Also, immediately after extracting 3.40-38-gf651f44 from the 7z archive, the error is:
```docs: Permission denied```

After trying to remove Read Only from the entire folder (top level and individual folders/files), the error is:
```charsets: Permission denied```

And finally, the Read Only permission on the charset folder always seems to be reset to Read Only by the O/S (Windows 10 x64).  Even if there are only R/W files in the charset folder, **the folders themselves appear to switch back to RO automatically** when the GUI is OK'ed  on Windows/FAT32 and NTFS (and exFat).

**Comment by d2-d2** [comment] 2017-03-12 10:31
Hey, it looks as the same issue I reported and you linked to it, however, I tested latest official release and following two new versions from /beta/ on my Win10 x64 box.

```
hashcat-3.40+38.7z                                 11-Mar-2017 08:17             2680799
hashcat-3.40+43.7z                                 12-Mar-2017 10:19             2674053
```

Everytime I tested I used 7z x archive.7z to extract files and then executed example0.cmd script to see what's going on. In my case, everything worked without issues.

*EDIT*: I also checked permissions of *docs* and *charsets* folders before and after executing example0.cmd - I see read-only permissions. Even though, everything seems to be running fine.

**Comment by alphastar868** [comment] 2017-03-12 16:17
@d2-d2 - many thanks for responding - _was_ wondering if it was syntax related.

Discovered a few additional things:

1. This error occurs with every version after Hashcat 3.10 (i.e. 3.20 and up to the current Beta).
2. Hashcat [doesn't yet work on $RAR3$\*1\*](https://hashcat.net/forum/thread-5334-post-28950.html#pid28950) hashes, so I get the Line Length exception described [here](https://hashcat.net/forum/thread-5334-post-28914.html#pid28914)

Neither of these explain the _Permission denied_ error message under my specific circumstances.

FWIW, my command was:

`.hashcat64.exe -a 6 -m 12500 --session=all -p * -o "Output.txt" --outfile-format=3 -w 2 --gpu-temp-abort=80 -1 ?h "RARfile.hash" "dict1.dic" ?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1`

**Comment by philsmd** [comment] 2017-03-13 11:23
This is an interesting report.

The problem is, that there are a lot of hashcat users out there that also use windows 10 and none of them reported problems like this recently (except the bug we found some weeks ago thanks to @d2-d2, but this was indeed a problem that was introduced with some refactoring and fixed very quickly).

I've also done various testings with windows 10 (benchmarks, cracking jobs, I ran some tests etc)... but never experience any file permission problems. (note: I am normally a linux user, so I might not be the right guy for windows-specific stuff, but I was always able to start hashcat without any permission problems on windows).

I therefore think that it's almost 100% a local issue and that the problem is not hashcat itself.

You should definitely do some more tests @alphastar868.
I also do not understand why you use fat32. Is this an usb drive?

Maybe the problem is due to the usb drive, some local permission problems (parent folders etc) or they are only affecting the way you extracted the archive or the GUI (3rd party tool!) is the culprit.
This are some test you should do to exclude that anything like this is part of the problem.

So I would suggest that (for these tests) you do not use fat32, you do not use external USB disks and that you download a fresh copy of hashcat from https://hashcat.net/hashcat and extract it with 7-Zip within a folder that you know is read/writable by your user (like C:\users\alphastar868\Downloads\hashcat\ , replace alphastar868 with your windows user name) and try to run it with cmd.exe inside that particular folder.
It is also advisable that you first make sure that you can read/write files within C:\users\alphastar868\Downloads\hashcat\ , so open something like notepad or notepad++ and try to write and read a file (e.g. test.txt).

Thanks

**Comment by alphastar868** [comment] 2017-03-15 00:03
I should have clarified that point regarding FAT32.

I actually started off with everything in a folder on the Desktop, i.e. _hashcat\hashcat-3.40_ and _hashcat\HashcatGUI_050b1_ - both on NTFS.

When I saw the permissions issues, I tried to remedy by moving to a filesystem without additional filesystem security, then by changing the permissions on the folder(s).

As for re-testing, I used 7-Zip to extract all the files to C;\\Users\\\<username\>\\Downloads\\hashcat-test\ (same folder structure as above) and then attempted the command above.  The output from the first run:
hashcat (v3.40-38-gf651f44) starting...

```
hashcat (v3.40-38-gf651f44) starting...

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 1080, 2048/8192 MB allocatable, 20MCU

docs: Permission denied

Started: Tue Mar 14 19:48:50 2017
Stopped: Tue Mar 14 19:49:02 2017
```
Even running from Downloads, the extracted folders all show as RO, although the individual files are not.  Any attempt to change them (and Apply to all folders, subfolders and files) results in the folders showing as RO the very next time (Right-click, Properties).

All subsequent runs give the following error:


```
hashcat (v3.40-38-gf651f44) starting...

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 1080, 2048/8192 MB allocatable, 20MCU

charsets: Permission denied

Started: Tue Mar 14 19:57:17 2017
Stopped: Tue Mar 14 19:57:17 2017
```

(It's always *charset*, for subsequent runs).

**Comment by neheb** [comment] 2017-03-15 04:12
sounds like a windows issue. exfat as opposed to fat32 might help.

Could also try using cygwin to change the permissions. or linux.

**Comment by philsmd** [comment] 2017-03-15 10:33
Could you also please post the full command you are using and the full output?

Does it also happen with something as simple as
`hashcat -b`
?

Do you by any chance have a separate computer/notebook (preferably with similar setup, e.g. win 10 etc) to test if it happens there too ?

Also, you said that you only use cmd, right? Do you use additional terminals like mingw/cygwin/msys? Maybe it also has something to do with other programs you have installed or individual windows settings?
It could also be that the problem is not at all the read-only permission (those files/folders could also be just read-only, because hashcat only reads those files, it doesn't write to them), but the ownership (the user who can access/read them etc).

**Comment by jsteube** [comment] 2017-03-17 08:43
I'm not 100% certain, but the command "-p *" might cause your shell to incorrectly expand the command to something different and results in creating stuff like "docs" and "charset" to be a treated as a hashlist. Opening a folder as a file sometimes creates that typical invalid error message "Permission denied" produced by windows, which then leads to the false assumption this is something related to filesystem ACL's. IOW, remove the -p parameter and try again.

**Comment by jsteube** [comment] 2017-03-28 09:03
OP not responding plus I'm kind of sure it the problem is the -p usage error, therefore closing. Feel free to reopen if that wasn't the case.

**Closed as completed by jsteube** 2017-03-28 09:03 UTC
