### ISSUE TITLE
Next Big Bang ETA for pretty simple cracking

### ISSUE THREAD

**Issue by sectroyer** [hashcat/hashcat#2726] opened 2021-03-12 10:52 UTC
I keep on getting:
```Time.Estimated...: Next Big Bang, (42477 years, 20 days) ```
for what looks to be pretty simple cracking session:
```./hashcat.bin -w3 -n32 --force -O -m 1500 ./tmp/sort_cameras.pwd -a3  -l 1104495 -s 0 -1 ?l?d -2 'abcdefghijklmn' '?2?1?1?1?1?1?u?u' --session=./sessions/dc_brute_des_hashcat_1 --user```
There are 14 hashes in pwd file of which 12 are cracked:
```Recovered........: 12/14 (85.71%) Digests, 12/14 (85.71%) Salts```
I mention this because if I remove those 12 hashes from pot file ETA is correct again. Let me know if you need anything else.

**Comment by jsteube** [comment] 2021-04-28 07:29
The mask is actually not that big. Can you provide me with all files I need to reproduce locally?

**Comment by jsteube** [comment] 2021-05-17 19:48
OP please update

**Comment by jsteube** [comment] 2021-06-03 19:05
No response from OP, plus I can't reproduce locally:

```
Time.Started.....: Thu Jun  3 21:04:32 2021, (5 secs)
Time.Estimated...: Thu Jun  3 21:10:17 2021, (5 mins, 40 secs)
```

Feel free to reopen with all files  I need to reproduce locally.

**Comment by sectroyer** [comment] 2021-06-06 10:14
I think the value that is calculated is dependent on number of hashes cracked. Now I am getting 2600 years for this command:
 ./hashcat.bin -w3 -n32 --force -O -m 1500 ./tmp/sort_cameras.pwd -a3 -l 1104495 -s 0 -1 ?l?d -2 'abcdefghijklmn' '?2?1?1?1?1?1?u?u' --session=./sessions/dc_brute_des_hashcat_1 --user
ETA:
`Time.Estimated...: Thu Dec 21 13:06:56 4643, (2622 years, 197 days)  `                                                                                                                

Here are hashes that I have in pwd file:
```
root:a03e3thxwWU0g
root:ab8nBoH3mb8.g
root:FCb/N1tGGXtP6
root:fRW5anhWEAGwY
root:GIgEh3ZZNHRh2
root:hbJdVywKWttVM
root:Sd5ZXUyhT8kwQ
root:Uu1Kq8MmXhxqA
root:yE7gW4O0CSXXg
root:7PJZu5rjtntsk
root:8QYQ7w7.s1xXM
root:04h6XLo9zAfEM
root:aVG8.5PMEOfnQ
root:Z2eoH2SgzVIfA
```
PS. I don't see an option to "reopen". Should I create new issue ?

**Comment by jsteube** [comment] 2021-06-07 08:08
Thanks for the update. I can't reproduce locally:

Vega64:

```
Time.Estimated...: Mon Jun  7 10:50:06 2021, (42 mins, 30 secs)
```

CPU:

```
Time.Estimated...: Mon Jun  7 17:59:07 2021, (7 hours, 50 mins)
```

Are you using latest hashcat version?

**Comment by Xanadrel** [comment] 2021-07-07 12:37
Same as @jsteube, I don't have the issue:

GPU: `Time.Estimated...: Wed Jul 07 14:28:43 2021, (1 min, 50 secs)`

CPU: `Time.Estimated...: Wed Jul 07 19:42:09 2021, (5 hours, 14 mins)`

@sectroyer You could include the output of `./hashcat.bin -I` too.

Also; reporting issues while using `--force` is not recommended.

**Comment by sectroyer** [comment] 2021-07-07 13:13
@jsteube, @Xanadrel did you have 12 hashes in potfile?

**Comment by jsteube** [comment] 2021-07-07 16:31
We still need the files to reproduce. I had asked for them in one of my first comments. Please provide all data we need to reproduce locally.

**Comment by sectroyer** [comment] 2021-07-13 19:45
As I said in pwd file I only have this:
```
root:a03e3thxwWU0g
root:ab8nBoH3mb8.g
root:FCb/N1tGGXtP6
root:fRW5anhWEAGwY
root:GIgEh3ZZNHRh2
root:hbJdVywKWttVM
root:Sd5ZXUyhT8kwQ
root:Uu1Kq8MmXhxqA
root:yE7gW4O0CSXXg
root:7PJZu5rjtntsk
root:8QYQ7w7.s1xXM
root:04h6XLo9zAfEM
root:aVG8.5PMEOfnQ
root:Z2eoH2SgzVIfA
```

I have downloaded fresh hashcat and put in potfile 12 fake pws:
```
a03e3thxwWU0g:test1
ab8nBoH3mb8.g:test2
FCb/N1tGGXtP6:test3
fRW5anhWEAGwY:test4
GIgEh3ZZNHRh2:test5
hbJdVywKWttVM:test6
Sd5ZXUyhT8kwQ:test7
Uu1Kq8MmXhxqA:test8
yE7gW4O0CSXXg:test9
7PJZu5rjtntsk:test10
8QYQ7w7.s1xXM:test11
04h6XLo9zAfEM:test12
```

And as a result I got:

```
Time.Started.....: Tue Jul 13 21:47:30 2021, (5 secs)
Time.Estimated...: Sun May 27 11:16:41 3460, (1438 years, 318 days)
Kernel.Feature...: Pure Kernel
Guess.Mask.......: ?2?1?1?1?1?1?u?u [8]
....
Recovered........: 12/14 (85.71%) Digests, 12/14 (85.71%) Salts
```

It really doesn't matter what is in potfile. It's just important to have 12 of 14 "cracked" 😄

**Comment by Xanadrel** [comment] 2021-07-13 19:59
Ok can reproduce, I don't get next big bang, but 237 years, even though it ends after under 2 minutes.

**Comment by jsteube** [comment] 2021-07-14 08:28
Fixed with commit https://github.com/hashcat/hashcat/commit/a82fce2c8f302309d190aac9743a5ef986bffb37

**Closed as completed by jsteube** 2021-07-14 08:28 UTC
Labels: bug

**Comment by sectroyer** [comment] 2021-07-14 08:31
I was able to reproduce it with latest version. It looks it depends on power of gpu. Once I switched to very poor one I got it once again:
```
Time.Estimated...: Next Big Bang, (134689 years, 24 days)
```

**Comment by jsteube** [comment] 2021-07-14 08:34
Problem was fixed few minutes ago

**Comment by jsteube** [comment] 2021-07-14 14:01
Please confirm all problems fixed

**Comment by Sudococommunity** [comment] 2022-11-24 15:36
Paid help
