### ISSUE TITLE
hashcat failing to find all entries in potfile for hashlist

### ISSUE THREAD

**Issue by thesle3p** [hashcat/hashcat#535] opened 2016-10-10 19:43 UTC
I am not sure which commit introduced this issue but I have noticed that when comparing hashes it does not prune all of the already cracked hashes in the potfile  when they are compared to the potfile, the number varies but when I try and other pass on a hashlist the percentage of cracked hashes is down roughly 5-10% from when the last pass on the list ended and many of the hashes I cracked in the last pass are cracked again.

**Comment by jsteube** [comment] 2016-10-13 08:16
I need a way to reproduce, please provide the files required

**Comment by jsteube** [comment] 2016-10-13 08:16
Also, try with latest beta: hashcat.net/beta

**Comment by thesle3p** [comment] 2016-10-13 11:13
Is there a email address I can send them to?

**Comment by thesle3p** [comment] 2016-10-14 19:16
Ok, further testing with both beta and git versions shows this only is the case with md5 hashes, I tested SHA-1 and NTLM and it detected and pruned entries from the potfile at run time.I also noticed that with md5 it displays the wrong amount of total hashes  as well as the cracked hashes (if including entries from the potfile) in the recovered field of console output. Could this be a issue in the md5 kernel issue?

**Comment by jsteube** [comment] 2016-10-15 08:52
I don't think so, because the MD5 kernel isn't involved in the potfile handling. Please pack the data I need to reproduce this, upload it somewhere (maybe password protect it before) and send me the link in an email to atom@hashcat.net

**Comment by jsteube** [comment] 2016-10-19 12:28
Please retry with latest beta version from https://hashcat.net/beta/ and close the issue if fixed

**Closed as completed** 2016-10-19 18:40 UTC
