### ISSUE TITLE
hashcat v3.30-49-g2f81532 from source, 3.20 64bit binary and git master segfaults

### ISSUE THREAD

**Issue by biatwc** [hashcat/hashcat#1010] opened 2017-02-01 17:58 UTC
Hi
I'm getting a segfault when I try to show the cracked passwords from an LM hash.
Background on this issue is here: https://hashcat.net/forum/thread-6250.html.
Laptop is Ubuntu Xenial: 
`Linux laptop 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

I try this command with any of the versions listed above:

`./hashcat64.bin -m 3000 --username --show --outfile-format 2 --potfile-path ../hashcat/hashcat.potfile ../original_hashes.txt`

and get:

ive_changed_the_username:F7R[E|P
Segmentation fault (core dumped)

Contents of hashcat.potfile is:

6b6db1d087ea9ba5:S?A
62c2efb7cb601def:F7R[E|P

Contents of original_hashes.txt is:

`ive_changed_the_username:62c2efb7cb601def6b6db1d087ea9ba5`

Anything else I need to put on here?

Many thanks

**Comment by philsmd** [comment] 2017-02-01 19:00
Since I can't reproduce, could you please recompile like this:
```
make clean
DEBUG=1 make
```

the output if you run it afterwards already should be more verbose, if not enough, please use:
`gdb --args ./hashcat64.bin -m 3000 --username --show --outfile-format 2 --potfile-path ../hashcat/hashcat.potfile ../original_hashes.txt`

after that type "r" to tun it under gdb, use "bt" to show the full backtrack (you can exit with "q" and "yes")
Thanks

**Comment by philsmd** [comment] 2017-02-02 07:30
note: this might also be related to this issue that was already fixed: https://github.com/hashcat/hashcat/issues/996
... but if that would be the case, you shouldn't experience crashes with the newest version from github (or beta: https://hashcat.net/beta/)

**Comment by jsteube** [comment] 2017-02-08 18:39
Please use latest beta version, the issue should be fixed

**Closed as completed by jsteube** 2017-02-08 18:39 UTC
Labels: needs information / data
