### ISSUE TITLE
Cannot run rule on 22000 WPA-PBKDF2-PMKID+EAPOL for words under 8 letters

### ISSUE THREAD

**Issue by hack3rman** [hashcat/hashcat#3278] opened 2022-05-10 15:49 UTC
**Check the FAQ**
DONE

**Describe the bug**
Hashcat refuses to operate rule based straight attack on words with fewer than 8 letters even if the wordset with rules will result in keys that have 8+ letters.

**To Reproduce**
`./hashcat.bin -a0 -m22000 hash.hc22000 list -r 2_letter`

**Expected behavior**
Hashcat should try the resulting wordlist from worlist+rules on wordlist with fewer than 8 characters. Currently it does not try any keys. 

**Hardware/Compute device (please complete the following information):**
- Compute device name: GP108M,
- OpenCL/CUDA driver name: nvidia-driver-470
- OpenCL/CUDA driver version: 470.103.01-0ubuntu0.20.04.1
- OpenCL/CUDA driver source: debian official repo

**Hashcat version (please complete the following information):**
 - OS: Linux
 - Distribution: Ubuntu 20.04
 - Version: 6.2.5

**Diagnostic output compute devices:**

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:2D:00.0 Off |                  N/A |
| N/A   56C    P0    N/A /  N/A |   1718MiB /  2002MiB |     85%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

```

```
Post clinfo output
```

```
hashcat (v6.2.5) starting in backend information mode

CUDA Info:
==========

CUDA.Version.: 11.4

Backend Device ID #1 (Alias: #2)
  Name...........: NVIDIA GeForce MX330
  Processor(s)...: 3
  Clock..........: 1594
  Memory.Total...: 2002 MB
  Memory.Free....: 284 MB
  PCI.Addr.BDFe..: 0000:2d:00.0

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: NVIDIA Corporation
  Name....: NVIDIA CUDA
  Version.: OpenCL 3.0 CUDA 11.4.189

  Backend Device ID #2 (Alias: #1)
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: NVIDIA GeForce MX330
    Version........: OpenCL 3.0 CUDA
    Processor(s)...: 3
    Clock..........: 1594
    Memory.Total...: 2002 MB (limited to 500 MB allocatable in one block)
    Memory.Free....: 256 MB
    OpenCL.Version.: OpenCL C 1.2 
    Driver.Version.: 470.103.01
    PCI.Addr.BDF...: 2d:00.0

```

```
00:00.0 Host bridge: Intel Corporation Device 9b61 (rev 0c)
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics (rev 02)
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 0c)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
00:12.0 Signal processing controller: Intel Corporation Comet Lake Thermal Subsytem
00:14.0 USB controller: Intel Corporation Device 02ed
00:14.2 RAM memory: Intel Corporation Device 02ef
00:14.3 Network controller: Intel Corporation Wireless-AC 9462
00:15.0 Serial bus controller [0c80]: Intel Corporation Serial IO I2C Host Controller
00:16.0 Communication controller: Intel Corporation Comet Lake Management Engine Interface
00:1c.0 PCI bridge: Intel Corporation Device 02b8 (rev f0)
00:1c.4 PCI bridge: Intel Corporation Device 02bc (rev f0)
00:1d.0 PCI bridge: Intel Corporation Device 02b0 (rev f0)
00:1d.4 PCI bridge: Intel Corporation Device 02b4 (rev f0)
00:1f.0 ISA bridge: Intel Corporation Device 0284
00:1f.3 Audio device: Intel Corporation Device 02c8
00:1f.4 SMBus: Intel Corporation Device 02a3
00:1f.5 Serial bus controller [0c80]: Intel Corporation Comet Lake SPI (flash) Controller
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (10) I219-V
02:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS522A PCI Express Card Reader (rev 01)
03:00.0 PCI bridge: Intel Corporation JHL6240 Thunderbolt 3 Bridge (Low Power) [Alpine Ridge LP 2016] (rev 01)
04:00.0 PCI bridge: Intel Corporation JHL6240 Thunderbolt 3 Bridge (Low Power) [Alpine Ridge LP 2016] (rev 01)
04:01.0 PCI bridge: Intel Corporation JHL6240 Thunderbolt 3 Bridge (Low Power) [Alpine Ridge LP 2016] (rev 01)
04:02.0 PCI bridge: Intel Corporation JHL6240 Thunderbolt 3 Bridge (Low Power) [Alpine Ridge LP 2016] (rev 01)
05:00.0 System peripheral: Intel Corporation JHL6240 Thunderbolt 3 NHI (Low Power) [Alpine Ridge LP 2016] (rev 01)
2b:00.0 USB controller: Intel Corporation JHL6240 Thunderbolt 3 USB 3.1 Controller (Low Power) [Alpine Ridge LP 2016] (rev 01)
2d:00.0 3D controller: NVIDIA Corporation GP108M [GeForce MX330] (rev a1)
2e:00.0 Non-Volatile memory controller: Sandisk Corp Device 5006
[rules+wordlist.zip](https://github.com/hashcat/hashcat/files/8663082/rules%2Bwordlist.zip)

```

**Additional context**

**Comment by Chick3nman** [comment] 2022-05-10 23:51
This behavior is not a bug, it is done on purpose. If you would like to discuss why/how this makes sense, feel free to start a forum thread or ask in the discord, I'd be happy to explain it.

**Comment by jsteube** [comment] 2022-05-13 11:38
I'll close this issue because hashcats way of applying the rules (as you described) can be done by using -S (make sure to upper case).

**Closed as completed by jsteube** 2022-05-13 11:38 UTC
Labels: bug
