### ISSUE TITLE
hashcat --stdout issue 

### ISSUE THREAD

**Issue by crwingfield** [hashcat/hashcat#1930] opened 2019-02-21 17:34 UTC
the command using --stdout runs 1x then fails with clbuildprogram error.
any thoughts?

Brutus:~ cisco$ echo -n  'Odessa77' | hashcat --stdout -j '%1s Dp ip$'
Ode$sa77
Brutus:~ cisco$ echo -n  'Odessa77' | hashcat --stdout -j '%1s Dp ip$'
clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

Brutus:~ cisco$ 

 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

**Comment by crwingfield** [comment] 2019-02-21 17:38
OpenCL Info:

Platform ID #1
  Vendor  : Apple
  Name    : Apple
  Version : OpenCL 1.2 (Oct 29 2018 21:43:16)

  Device ID #1
    Type           : CPU
    Vendor ID      : 4
    Vendor         : Intel
    Name           : Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
    Version        : OpenCL 1.2 
    Processor(s)   : 4
    Clock          : 2800
    Memory         : 2048/8192 MB allocatable
    OpenCL Version : OpenCL C 1.2 
    Driver Version : 1.1

  Device ID #2
    Type           : GPU
    Vendor ID      : 4
    Vendor         : Intel
    Name           : Iris
    Version        : OpenCL 1.2 
    Processor(s)   : 40
    Clock          : 1200
    Memory         : 384/1536 MB allocatable
    OpenCL Version : OpenCL C 1.2 
    Driver Version : 1.2(Nov 26 2018 20:27:28)

**Comment by philsmd** [comment] 2019-02-21 18:51
can't reproduce over here. that's a very weird problem.
how should it be always the second attempt. who is counting up to 2 ?
but jokes aside, do you have only problems with --stdout or is this also happening with "normal" runs ?

we might need to do a make DEBUG=1 run and get more debugging info about the kernel problem

I guess it has to do with your macOS driver, maybe it's somehow unstable/broken etc

**Comment by jsteube** [comment] 2019-02-22 06:17
This sounds like if the cached kernel binary which is generated by the opencl runtime and which is stored in kernels/ is not useable. In the first run we use the binary compiled by the JiT, which could explain that the first run is working. 

Anyway, this behavior was not changed in any recent version. IOW, this never has worked before, correct?

**Comment by jsteube** [comment] 2019-03-11 08:21
The problem was fixed with commit https://github.com/hashcat/hashcat/commit/b99d392e78c92cd9e624c04f4c72eb4cb6c55849

Feel free to reopen if fixes did not work for you. Thank you for reporting

**Closed as completed by jsteube** 2019-03-11 08:21 UTC
