### ISSUE TITLE
problem hashcat in Mining(10 nvidia 1080 ti)

### ISSUE THREAD

**Issue by amheydari** [hashcat/hashcat#2193] opened 2019-09-23 09:30 UTC
Hi
I run hahscat 5.1.0 with 10 graphics cards(1080 ti).
After some time, some of the main attack program threads are removed.
Number of thread in start time program 84

The number of threads at the start of the program equals 84 but then it's been 76.
![log](https://user-images.githubusercontent.com/5462021/65415104-ecc24900-de01-11e9-8533-4fa7853fde9d.jpg)

**Comment by jsteube** [comment] 2019-09-23 10:57
The problem is that the Nvidia driver currently has a bug in NVML which randomly reports an error back to the calling program. If this happens, hashcat stops the monitoring thread for this particular device. Over time, more and more threads are being removed (to a maximum of number of GPU * 2). There's nothing we can do to prevent this error. You can verify this is not a hashcat bug by using nvidia-smi provided by Nvidia driver. Run it multiple times, after some time you will find the fan speed reported as an error. Since this is not a hashcat issue I will close it.

**Closed as completed by jsteube** 2019-09-23 10:57 UTC
