### ISSUE TITLE
Hashcat 3.2 error..

### ISSUE THREAD

**Issue by mad76e** [hashcat/hashcat#904] opened 2016-12-03 17:18 UTC
As you see in picture it works pretty good in Hashcat 3.1, but when i am trying to run 3.2 i get a lot of error messages

AMD Radeon Software Crimson Edition" (15.12)

Windows7 64 bit
16 gig ram
2 AMD SAPPHIRE NITRO Radeon™ R9 380X 4GD5
Intel Pentium G3258
OpenCL Runtime for Intel Core and Intel Xeon Processors 16.1.1
OpenCL Driver for Intel Iris and Intel HD Graphics

Running with --force doesn't change anything. Graphics cards NOT overclocked

Any ideas how to solve this.

![q816aio](https://cloud.githubusercontent.com/assets/24358047/20860963/9a5b575a-b984-11e6-88a0-f638000ca140.png)

**Comment by jsteube** [comment] 2016-12-04 13:11
OK, thanks for reporting. Can you please post a full output of "clinfo" tool. Also please post output of "hashcat -I" on hashcat v3.20. Thanks!

**Comment by mad76e** [comment] 2016-12-04 17:19
Added the info you requested 

[hashcat64.txt](https://github.com/hashcat/hashcat/files/629679/hashcat64.txt)
[Clinfo.txt](https://github.com/hashcat/hashcat/files/629680/Clinfo.txt)

**Comment by untitledxi** [comment] 2016-12-05 22:08
Similar issue, when running hashcat in benchmark mode:

```
hashcat (v3.20-18-g2039e2c+) starting in benchmark mode...

* Device #3: Not a native Intel OpenCL runtime, expect massive speed loss
             You can use --force to override this but do not post error reports if you do so
ADL_Overdrive6_TargetTemperatureData_Get(): -8

OpenCL Platform #1: Intel(R) Corporation
========================================
* Device #1: Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz, skipped

OpenCL Platform #2: Advanced Micro Devices, Inc.
================================================
* Device #2: Hawaii, 2047/4096 MB allocatable, 40MCU
* Device #3: Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz, skipped

Hashtype: MD4

clEnqueueNDRangeKernel(): CL_MEM_OBJECT_ALLOCATION_FAILURE
```

64bit:

- Works with Intel-only (D1)
- Crashes with ```CL_MEM_OBJECT_ALLOCATION_FAILURE``` when AMD (D2) is selected

32bit:

- Crashes at start no matter what device-type is selected

hashcat

```
hashcat (v3.20-18-g2039e2c+) starting...

OpenCL Info:

Platform ID #1
  Vendor  : Intel(R) Corporation
  Name    : Intel(R) OpenCL
  Version : OpenCL 1.2

  Device ID #1
    Type           : CPU
    Vendor ID      : 8
    Vendor         : Intel(R) Corporation
    Name           : Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
    Version        : OpenCL 1.2 (Build 10094)
    Processor(s)   : 4
    Clock          : 3400
    Memory         : 2047/16313 MB allocatable
    OpenCL Version : OpenCL C 1.2
    Driver Version : 5.2.0.10094

Platform ID #2
  Vendor  : Advanced Micro Devices, Inc.
  Name    : AMD Accelerated Parallel Processing
  Version : OpenCL 2.0 AMD-APP (2117.14)

  Device ID #2
    Type           : GPU
    Vendor ID      : 1
    Vendor         : Advanced Micro Devices, Inc.
    Name           : Hawaii
    Version        : OpenCL 2.0 AMD-APP (2117.14)
    Processor(s)   : 40
    Clock          : 1050
    Memory         : 2047/4096 MB allocatable
    OpenCL Version : OpenCL C 2.0
    Driver Version : 2117.14 (VM)

  Device ID #3
    Type           : CPU
    Vendor ID      : 128
    Vendor         : GenuineIntel
    Name           : Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
    Version        : OpenCL 1.2 AMD-APP (2117.14)
    Processor(s)   : 4
    Clock          : 3400
    Memory         : 2047/16313 MB allocatable
    OpenCL Version : OpenCL C 1.2
    Driver Version : 2117.14 (sse2,avx)
```

CLInfo:

```
Number of platforms:                             2
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 1.2
  Platform Name:                                 Intel(R) OpenCL
  Platform Vendor:                               Intel(R) Corporation
  Platform Extensions:                           cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_3d_image_writes cl_intel_exec_by_local_thread cl_khr_spir cl_khr_dx9_media_sharing cl_intel_dx9_media_sharing cl_khr_d3d11_sharing cl_khr_gl_sharing cl_khr_fp64
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.0 AMD-APP (2117.14)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices


  Platform Name:                                 Intel(R) OpenCL
Number of devices:                               1
  Device Type:                                   CL_DEVICE_TYPE_CPU
  Vendor ID:                                     8086h
  Max compute units:                             4
  Max work items dimensions:                     3
    Max work items[0]:                           8192
    Max work items[1]:                           8192
    Max work items[2]:                           8192
  Max work group size:                           8192
  Preferred vector width char:                   1
  Preferred vector width short:                  1
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      32
  Native vector width short:                     16
  Native vector width int:                       8
  Native vector width long:                      4
  Native vector width float:                     8
  Native vector width double:                    4
  Max clock frequency:                           3400Mhz
  Address bits:                                  64
  Max memory allocation:                         4276445184
  Image support:                                 Yes
  Max number of images read arguments:           480
  Max number of images write arguments:          480
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    480
  Max size of kernel argument:                   3840
  Alignment (bits) of base address:              1024
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     Yes
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               No
    Round to +ve and infinity:                   No
    IEEE754-2008 fused multiply-add:             No
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    262144
  Global memory size:                            17105780736
  Constant buffer size:                          131072
  Max number of constant args:                   480
  Local memory type:                             Global
  Local memory size:                             32768
  Kernel Preferred work group size multiple:     128
  Error correction support:                      0
  Unified memory for Host and Device:            1
  Profiling timer resolution:                    301
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     Yes
  Queue on Host properties:
    Out-of-Order:                                Yes
    Profiling :                                  Yes
  Name:                                          Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
  Vendor:                                        Intel(R) Corporation
  Device OpenCL C version:                       OpenCL C 1.2
  Driver version:                                5.2.0.10094
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 1.2 (Build 10094)
  Extensions:                                    cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_3d_image_writes cl_intel_exec_by_local_thread cl_khr_spir cl_khr_dx9_media_sharing cl_intel_dx9_media_sharing cl_khr_d3d11_sharing cl_khr_gl_sharing cl_khr_fp64


  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               2
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     1002h
  Board name:                                    AMD Radeon R9 200 Series
  Device Topology:                               PCI[ B#2, D#0, F#0 ]
  Max compute units:                             40
  Max work items dimensions:                     3
    Max work items[0]:                           256
    Max work items[1]:                           256
    Max work items[2]:                           256
  Max work group size:                           256
  Preferred vector width char:                   4
  Preferred vector width short:                  2
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      4
  Native vector width short:                     2
  Native vector width int:                       1
  Native vector width long:                      1
  Native vector width float:                     1
  Native vector width double:                    1
  Max clock frequency:                           1050Mhz
  Address bits:                                  64
  Max memory allocation:                         3019898880
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          64
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    16
  Max size of kernel argument:                   1024
  Alignment (bits) of base address:              2048
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     No
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    16384
  Global memory size:                            4294967296
  Constant buffer size:                          65536
  Max number of constant args:                   8
  Local memory type:                             Scratchpad
  Local memory size:                             32768
  Max pipe arguments:                            16
  Max pipe active reservations:                  16
  Max pipe packet size:                          3019898880
  Max global variable size:                      2717908992
  Max global variable preferred total size:      4294967296
  Max read/write image args:                     64
  Max on device events:                          1024
  Queue on device max size:                      8388608
  Max on device queues:                          1
  Queue on device preferred size:                262144
  SVM capabilities:
    Coarse grain buffer:                         Yes
    Fine grain buffer:                           Yes
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     64
  Error correction support:                      0
  Unified memory for Host and Device:            0
  Profiling timer resolution:                    1
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     No
  Queue on Host properties:
    Out-of-Order:                                No
    Profiling :                                  Yes
  Queue on Device properties:
    Out-of-Order:                                Yes
    Profiling :                                  Yes
  Name:                                          Hawaii
  Vendor:                                        Advanced Micro Devices, Inc.
  Device OpenCL C version:                       OpenCL C 2.0
  Driver version:                                2117.14 (VM)
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 2.0 AMD-APP (2117.14)
  Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_liquid_flash


  Device Type:                                   CL_DEVICE_TYPE_CPU
  Vendor ID:                                     1002h
  Board name:
  Max compute units:                             4
  Max work items dimensions:                     3
    Max work items[0]:                           1024
    Max work items[1]:                           1024
    Max work items[2]:                           1024
  Max work group size:                           1024
  Preferred vector width char:                   16
  Preferred vector width short:                  8
  Preferred vector width int:                    4
  Preferred vector width long:                   2
  Preferred vector width float:                  8
  Preferred vector width double:                 4
  Native vector width char:                      16
  Native vector width short:                     8
  Native vector width int:                       4
  Native vector width long:                      2
  Native vector width float:                     8
  Native vector width double:                    4
  Max clock frequency:                           3400Mhz
  Address bits:                                  64
  Max memory allocation:                         4276445184
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          64
  Max image 2D width:                            8192
  Max image 2D height:                           8192
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    16
  Max size of kernel argument:                   4096
  Alignment (bits) of base address:              1024
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     Yes
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    32768
  Global memory size:                            17105780736
  Constant buffer size:                          65536
  Max number of constant args:                   8
  Local memory type:                             Global
  Local memory size:                             32768
  Max pipe arguments:                            16
  Max pipe active reservations:                  16
  Max pipe packet size:                          4276445184
  Max global variable size:                      1879048192
  Max global variable preferred total size:      1879048192
  Max read/write image args:                     64
  Max on device events:                          0
  Queue on device max size:                      0
  Max on device queues:                          0
  Queue on device preferred size:                0
  SVM capabilities:
    Coarse grain buffer:                         No
    Fine grain buffer:                           No
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     1
  Error correction support:                      0
  Unified memory for Host and Device:            1
  Profiling timer resolution:                    301
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     Yes
  Queue on Host properties:
    Out-of-Order:                                No
    Profiling :                                  Yes
  Queue on Device properties:
    Out-of-Order:                                No
    Profiling :                                  No
  Name:                                          Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
  Vendor:                                        GenuineIntel
  Device OpenCL C version:                       OpenCL C 1.2
  Driver version:                                2117.14 (sse2,avx)
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 1.2 AMD-APP (2117.14)
  Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_spir cl_khr_gl_event
```

**Comment by jsteube** [comment] 2016-12-06 11:42
Looks like this is some AMD-and-only-on-Windows issue. Need to build such a system locally to reproduce.

**Comment by mad76e** [comment] 2016-12-06 21:47
Is there something else i can do to help Jsteube

**Comment by jsteube** [comment] 2016-12-09 14:01
No, give me some time so that I can build a new PC using the combination of Windows + AMD GPU otherwise I can not reproduce

**Comment by jsteube** [comment] 2016-12-27 13:51
Wait, is this from a notebook computer?

**Comment by mad76e** [comment] 2016-12-27 15:30
? Whaat..With double GPUS? Certainly NOT!

Here is my setup

Motherboard : ASRock H97 Anniversary
Kingston 4GB x 4GB KVR16N11S8/4
Intel Pentium G3258 Anniversary Edition
An little older 250gb harddrive
2x Sapphire Radeon R9 380X Nitro 4GB GPUs

**Comment by jsteube** [comment] 2016-12-27 19:43
Since I don't have a Windows+AMD system for test I wrote some code change blindly. Can you please try this version: https://hashcat.net/beta/hashcat-3.20%2b59%2bADLTEST.7z and post what it's doing?

**Comment by mad76e** [comment] 2016-12-29 09:45
Got some error trying to download it
Oooops

The Page you're looking for does not exist (Error 404, as in HTTP).
Cat #21 - Fail Cat
Cat #21 - Fail Cat

**Comment by jsteube** [comment] 2016-12-29 09:46
It's updated in the meanwhile, please manually pick latest version from here: https://hashcat.net/beta/

**Comment by mad76e** [comment] 2016-12-29 10:00
Yeah.. that one works fine, however i got some error message for you as you see.
 
![123456](https://cloud.githubusercontent.com/assets/24358047/21541358/ea4f0df2-cdb5-11e6-8e79-3769d672270f.png)
well

**Comment by jsteube** [comment] 2016-12-29 10:09
Press "s" and post the hwmon line please

**Comment by mad76e** [comment] 2016-12-29 10:18
Ok!
![123456](https://cloud.githubusercontent.com/assets/24358047/21541676/8eeddc10-cdb8-11e6-9032-4320cf3eb77d.png)

**Comment by jsteube** [comment] 2016-12-29 10:20
Looks good, the error is because hashcat needs to find out which
overdrive Version to use (5 or 6). Please close the issue if you think
it's ok.

**Comment by mad76e** [comment] 2016-12-29 10:21
Thanks for your help jsteube.. Closing now :)

**Closed** 2016-12-29 10:22 UTC
Labels: bug, help wanted
