### ISSUE TITLE
Hybrid attack with hex charset - hash not cracked, weird output

### ISSUE THREAD

**Issue by davidbolvansky** [hashcat/hashcat#3436] opened 2022-09-01 13:27 UTC
Assume dictionary:
```
abc
fdsa
test
1234
12345
qwerty
000000
```
Assume bcrypt (-m 3200) hash for string "fdsaf":
$2a$12$gCM6uwnORwFlxlIDUx4QY.biekL/K0rQkpnHV0wGaKsjBj7T0NnCq

```
./hashcat.bin -m 3200 h -a 6 dic -1 66 "?1" --hex-charset                          Exhausted
```
Strange, it should be cracked... f is 66, so fdsa+f=fdsaf

Now assume bcrypt (-m 3200) hash for string "abcf":
$2a$12$8t9/tMPvYO73X44GbEybyOxas3Kv.kN/RbYvO/7hPDcOeA.nB9OGy
```
./hashcat.bin -m 3200 h -a 6 dic -1 66 "?1" --hex-charset                        Cracked
```
Okay, this is OK. So we should check password candidates:
```
./hashcat.bin -m 3200 h -a 6 dic -1 66 "?1" --hex-charset  --stdout
B�H��i��1D
          򲑬4�W����܎�{�f
abcf
��f
��f
```

Weird.. and this output explains why the first one was not cracked and second was. Did I miss something or hashcat (tested "master" version) has a bug here?

**Comment by Chick3nman** [comment] 2022-09-01 14:46
It looks like something is wrong with your dictionary file. Can you open it with a hex editor and see what it looks like? Should be UTF8 plain text.

**Comment by paulouderkirk** [comment] 2022-09-01 15:08
I can reproduce this weirdness with a clean text file

`pdo@nemesis ~ % xxd < dict.txt
00000000: 6162 630a 3631 3632 3633 0a              abc.616263.`

`pdo@nemesis ~ % hashcat -m 3200 hash.txt -a 6 dict.txt -1 66 "?1" --hex-charset  --stdout
B�P�n�QR���.U�
              ��
L;7�w�f
abcf
abcf`

**Comment by davidbolvansky** [comment] 2022-09-01 15:14
I was wondering about a broken dictionary file too but it does not seems so.

Also for example use few lines of python to generate dictionary:

```
with open("dict", "w") as f:
    for i in ["abc", "fsda", "test"]:
        f.write(i + "\n")
```

```
xbolva00@xbolva00-G551JW:~/hashcat/hashcat$ cat h2
$2a$12$gCM6uwnORwFlxlIDUx4QY.biekL/K0rQkpnHV0wGaKsjBj7T0NnCq
xbolva00@xbolva00-G551JW:~/hashcat/hashcat$ python3 dicgen.py 
xbolva00@xbolva00-G551JW:~/hashcat/hashcat$ ./hashcat.bin -m 3200 h -a 6 dict -1 66 "?1" --hex-charset  --stdout
B�H��i��1D
          򲑬4�W����܎�{�f
abcf
��f
��f
```


Without hex-charset output is OK:
```
xbolva00@xbolva00-G551JW:~/hashcat/hashcat$ ./hashcat.bin -m 3200 h -a 6 dict -1 f "?1"   --stdout
$2a$12$8t9/tMPvYO73X44GbEybyOxas3Kv.kN/RbYvO/7hPDcOeA.nB9OGyf
abcf
fsdaf
testf
```

So it seems that hex-charset option affects more than just custom charsets.

**Comment by Chick3nman** [comment] 2022-09-01 15:24
> So it seems that hex-charset option affects more than just custom charsets.

Indeed, you are correct. I see the issue, it looks like we may be blanket setting OPTS_TYPE_PT_HEX with --hex-charset, which causes the wordlist to be considered as hex as well. Surprised this hasn't come up before, let me see if there's a simple way to avoid this.

**Comment by davidbolvansky** [comment] 2022-09-01 15:39
Yeah!

https://github.com/hashcat/hashcat/blob/a402e8dc2943bcd6d97a47aecfa99fb62ddd333d/docs/hashcat-plugin-development-guide.md

OPTS_TYPE_PT_HEX: Assume that all input data like wordlist and masks are always given in hex
OPTS_TYPE_ST_HEX: Same as OPTS_TYPE_PT_HEX but applied on the salt buffer.

So it probably make sense to do same and split OPTS_TYPE_PT_HEX for wordlist / masks

**Comment by Chick3nman** [comment] 2022-09-01 15:44
We may not need to do much work here, as we already have --hex-wordlist and --hex-charset. Currently both map to OPTS_TYPE_PT_HEX. I'm looking at best options right now and I'll PR a fix for this soon.

**Comment by davidbolvansky** [comment] 2022-09-02 15:31
@jsteube I think it would be great to get fix for this issue in as part of hashcat 6.2.6.
Quite a huge bug affecting hybrid attacks..

edit: probably too late..

**Comment by Chick3nman** [comment] 2022-09-02 16:04
I worked on this some yesterday, seems like it's a bit more complicated to fix than I had originally hoped. I sent a note to Atom about it earlier to get his thoughts on how to fix it.

**Comment by davidbolvansky** [comment] 2022-09-02 19:40
I am wondering if this could be OK. Fixes original cases, but not sure if does not break something else.

```
diff --git a/docs/hashcat-plugin-development-guide.md b/docs/hashcat-plugin-development-guide.md
index 3cee204ae..af88bb5cc 100644
--- a/docs/hashcat-plugin-development-guide.md
+++ b/docs/hashcat-plugin-development-guide.md
@@ -456,7 +456,7 @@ This configuration item is a bitmask field and is very similar to the module_opt
 * OPTS_TYPE_PT_ALWAYS_ASCII: This option prevents hashcat to automatically convert a password into the $HEX[...] encoding type. This automatic conversion is typically performed if the password itself contains the same character as the hash line separator character.
 * OPTS_TYPE_PT_ALWAYS_HEXIFY: This option forces all the cracked passwords to be written always in hex. In this case neither "$HEX[", nor "]", is added.
 * OPTS_TYPE_PT_LM: Special handling for LM passwords: all lower, 7 max, ...
-* OPTS_TYPE_PT_HEX: Assume that all input data like wordlist and masks are always given in hex
+* OPTS_TYPE_PT_HEX: Assume that wordlist is given in hex.
 * OPTS_TYPE_ST_UTF16LE: Same as OPTS_TYPE_PT_UTF16LE but applied on the salt buffer.
 * OPTS_TYPE_ST_UTF16BE: Same as OPTS_TYPE_PT_UTF16BE but applied on the salt buffer.
 * OPTS_TYPE_ST_UPPER: Same as OPTS_TYPE_PT_UPPER but applied on the salt buffer.
@@ -468,6 +468,7 @@ This configuration item is a bitmask field and is very similar to the module_opt
 * OPTS_TYPE_ST_ADDBITS15: Same as OPTS_TYPE_PT_ADDBITS15 but applied on the salt buffer.
 * OPTS_TYPE_ST_HEX: Same as OPTS_TYPE_PT_HEX but applied on the salt buffer.
 * OPTS_TYPE_ST_BASE64: Same as OPTS_TYPE_ST_HEX but using base64 encoding.
+* OPTS_TYPE_MT_HEX: Assume that mask is always given in hex.
 * OPTS_TYPE_HASH_COPY: This copies the original input hash line as it is into a buffer so that it can be used later. This is required if the original input hash line ships with the same data which is not copied into salt_t or esalt buffer because it is overhead data which is not used in any way. The hash line is copied to the buffer hash_info->orighash and can be used from the encoder function by simply returning hash_info->orighash. Please do not abuse this functionality, for two reasons: First, by being able to reconstruct the original hash line from only the hashcat data we verify that the correct amount of data has been stored in the hashcat memory structures (IOW, it is a good verification process). Second, the host memory requirement for saving this data increases drastically.
 * OPTS_TYPE_HASH_SPLIT: This needs to be used if the hash actually contains multiple hashes in the same hash line. A good example is the LM hash which is typically stored as a 128 bit hash, but actually is built on two 64 bit hashes.
 * OPTS_TYPE_LOOP_PREPARE: TBD
diff --git a/include/types.h b/include/types.h
index 8f390be90..7b2aeef87 100644
--- a/include/types.h
+++ b/include/types.h
@@ -413,7 +413,7 @@ typedef enum opts_type
   OPTS_TYPE_PT_ALWAYS_ASCII   = (1ULL << 12),
   OPTS_TYPE_PT_ALWAYS_HEXIFY  = (1ULL << 13),
   OPTS_TYPE_PT_LM             = (1ULL << 14), // special handling: all lower, 7 max, ...
-  OPTS_TYPE_PT_HEX            = (1ULL << 15), // input wordlist (and masks!) are always in hex
+  OPTS_TYPE_PT_HEX            = (1ULL << 15), // input wordlist is always in hex
   OPTS_TYPE_ST_UTF16LE        = (1ULL << 16),
   OPTS_TYPE_ST_UTF16BE        = (1ULL << 17),
   OPTS_TYPE_ST_UPPER          = (1ULL << 18),
@@ -425,6 +425,7 @@ typedef enum opts_type
   OPTS_TYPE_ST_ADDBITS15      = (1ULL << 24),
   OPTS_TYPE_ST_HEX            = (1ULL << 25),
   OPTS_TYPE_ST_BASE64         = (1ULL << 26),
+  OPTS_TYPE_MT_HEX            = (1ULL << 27), // mask is always in hex
   OPTS_TYPE_HASH_COPY         = (1ULL << 28),
   OPTS_TYPE_HASH_SPLIT        = (1ULL << 29),
   OPTS_TYPE_LOOP_PREPARE      = (1ULL << 30), // a kernel which is called each time before _loop kernel started.
diff --git a/src/interface.c b/src/interface.c
index 588aa6d05..1cba43229 100644
--- a/src/interface.c
+++ b/src/interface.c
@@ -294,7 +294,7 @@ int hashconfig_init (hashcat_ctx_t *hashcat_ctx)
 
   if (user_options->hex_charset)
   {
-    hashconfig->opts_type |= OPTS_TYPE_PT_HEX;
+    hashconfig->opts_type |= OPTS_TYPE_MT_HEX;
   }
 
   if (user_options->hex_wordlist)
diff --git a/src/mpsp.c b/src/mpsp.c
index b56653c81..05c7c3eb3 100644
--- a/src/mpsp.c
+++ b/src/mpsp.c
@@ -324,7 +324,7 @@ static int mp_expand (hashcat_ctx_t *hashcat_ctx, const char *in_buf, size_t in_
     }
     else
     {
-      if (hashconfig->opts_type & OPTS_TYPE_PT_HEX)
+      if (hashconfig->opts_type & OPTS_TYPE_MT_HEX)
       {
         in_pos++;
 
@@ -437,7 +437,7 @@ static int mp_gen_css (hashcat_ctx_t *hashcat_ctx, char *mask_buf, size_t mask_l
     }
     else
     {
-      if (hashconfig->opts_type & OPTS_TYPE_PT_HEX)
+      if (hashconfig->opts_type & OPTS_TYPE_MT_HEX)
       {
         mask_pos++;
 
@@ -519,7 +519,7 @@ static int mp_get_truncated_mask (hashcat_ctx_t *hashcat_ctx, const char *mask_b
     }
     else
     {
-      if (hashconfig->opts_type & OPTS_TYPE_PT_HEX)
+      if (hashconfig->opts_type & OPTS_TYPE_MT_HEX)
       {
         mask_pos++;
 
@@ -1168,7 +1168,7 @@ u32 mp_get_length (const char *mask, const u32 opts_type)
         ignore_next = true;
       }
 
-      if (opts_type & OPTS_TYPE_PT_HEX)
+      if (opts_type & OPTS_TYPE_MT_HEX)
       {
         ignore_next = true;
       }

```

**Comment by jsteube** [comment] 2022-09-06 08:24
There's two different problems and it's important to not mix them up to avoid confusion!

1. The main problem is that the OP did use --stdout but at the same time did not remove the hashlist. That forces hashcat to read the hashlist as being a wordlist. 

2. In combination the --hex-charset forced hashcat to read the *hashlist* using a hex decode and that causes the weird character output. The PR https://github.com/hashcat/hashcat/pull/3442 from @davidbolvansky seems fine to fix that so I'll merge.

**Closed as completed** 2022-09-06 08:24 UTC
Labels: bug
