### ISSUE TITLE
Request new algo: ESET ui client password

### ISSUE THREAD

**Issue by mike-code** [hashcat/hashcat#1992] opened 2019-04-11 00:02 UTC
I would like to request implementation of following algo (implementation in Delphi)

https://github.com/LFriede/eset-password-recovery/blob/master/algo.pas

**Comment by jsteube** [comment] 2019-04-16 08:27
Where is this used in?

**Comment by RealEnder** [comment] 2019-04-16 09:29
Looks like it's used just in ESET antivirus.

**Comment by philsmd** [comment] 2020-01-08 16:19
I just had a glance at this and it turns out that this is a plain and simple crc32 checksum. There is some minor variation to it: it uses utf16le (unicode encoding) and it has a final mask (maybe just used as an obfuscation etc).

The constant that is used to xor it (from the delphi/pascal code above) is: ` 0x68dbaf89`

Since it is crc32, we already support this with -m 11500 = CRC32.

For convenience, I just quickly developed a little converter script:
```
#!/usr/bin/env perl

# Author:  philsmd
# Date:    January 2020
# License: public domain, credits go to philsmd and hashcat

use strict;
use warnings;

use Digest::CRC qw (crc32);

#
# Constants:
#

my $ESET_MASK = 0x68dbaf89;

#
# Example hash:
#

my $hash = 3989484483; # 0xedcab3c3 (password is hashcat)

#
# Start:
#

# accept command line "hash"

if (scalar (@ARGV) == 1)
{
  if ($ARGV[0] =~ m/^[0-9]{1,10}$/)
  {
    my $num = int ($ARGV[0]);

    if ($num <= 0xffffffff)
    {
      $hash = $num;
    }
  }
  elsif ($ARGV[0] =~ m/^0x[0-9a-fA-F]{8}$/)
  {
    $hash = hex ($ARGV[0]);
  }
}

my $hash_for_hc = $hash ^ $ESET_MASK;

print STDERR "use with -m 11500 --encoding-to utf16le:\n";

print sprintf ("%08x:00000000\n", $hash_for_hc);
```

you can call it as simple as this (eset_to_hashcat.pl is the perl script above):
```
perl eset_to_hashcat.pl 3989484483
```

or with hexadecimal crc32 checksum:
```
perl eset_to_hashcat.pl 0xedcab3c3
```


To make it very clear how the code works, I also made this little "hashing" script:
```
#!/usr/bin/env perl

# Author:  philsmd
# Date:    January 2020
# License: public domain, credits go to philsmd and hashcat

use strict;
use warnings;

use Digest::CRC qw (crc32);
use Encode;

#
# Constants:
#

my $ESET_MASK = 0x68dbaf89;

#
# Example password:
#

my $word = "hashcat";

#
# Start:
#

# accept command line password

if (scalar (@ARGV) == 1)
{
  $word = $ARGV[0];
}

# utf16le encoding:

my $word_utf16le = encode ('UTF16LE', $word);

my $hash = crc32 ($word_utf16le);

my $hash_eset= $hash ^ $ESET_MASK;


# output:

print sprintf ("%i\n", $hash_eset);

print STDERR sprintf ("use with -m 11500 --encoding-to utf16le: %08x:00000000)\n", $hash);
```

this can be used to "hash" a password with this strange and dangerous (because very fast and many collisions possible) hashing algorithm. Use it like this:
```
perl eset_hash.pl password
```

where the first command paramter to the script (after the script name "eset_hash.pl") can be replaced by any password you would like to "hash with crc32" (LUL).

I think, since this format is so easy to convert and that quick to crack and we didn't really get a lot of user interest here, we do not need a separate hashcat module (you could just convert the "hash" with the scripts above and run them with -m 11500).

I think this is an acceptable way to convert the hashes before running them with hashcat and therefore I suggest that @mike-code or @jsteube close this issue. thx

btw: yeah, there are these 2 things that need to be considered: conversion (unmasking the hash with the constant 0x68dbaf89) and utf16le encoding... a new module/kernel could do both internally, but it's so fast to crack crc32 checksum and therefore it's probably not a good idea to use mask attack (even through it would be possible, you would just need to have a mask which uses zero-bytes every second byte for utf16le)... I think a dictionary attack (with rules) + --encoding-to utf16le is extremely fast and effective here and will return you very soon the password (or collision, hehe)

please close, thx

**Comment by jsteube** [comment] 2020-01-08 19:33
Great research and thanks for providing the script to crack this type of hashes with hashcat. Happy cracking!

**Closed as completed by jsteube** 2020-01-08 19:33 UTC

**Comment by exaghost** [comment] 2025-07-04 18:23
Hi!

I have a similar problem with ESET Endpoint Security 11.1.2039.2. The lock password hash can be extracted from the registry even with a normal user account. The problem is, the encrypted / hashed password is 82 hex bytes long, and there is a username, so it is obviously not the scheme discussed here. No info for the algorithm so far, but maybe someone has some more knowledge. Should/can I open a new ticket? This is recent password protection used in ESET software, so it can be relevant.
