### ISSUE TITLE
Not enough allocable device memory 

### ISSUE THREAD

**Issue by Aggelos11** [hashcat/hashcat#3996] opened 2024-04-28 08:08 UTC
Hello! When I try to run hashcat I get the following error: my gpu is intel hd graphics 4400
![IMG_8590](https://github.com/hashcat/hashcat/assets/62383412/a232351f-8d53-4733-a559-cbcc656cfebd)

**Comment by PenguinKeeper7** [comment] 2024-04-28 11:25
As stated at the top, it can only allocate 203MB, which isn't enough for most attacks. Try using `-D 1 -d 2` in your command to select the CPU instead. If you need any more help with this, please go to the Discord or the Forum as this is a resource issue, not a Hashcat issue

**Comment by Aggelos11** [comment] 2024-04-28 11:28
Well I downloaded an older version of hashcat and it works … the thing is that it is kinda slow … I mean in order to use the full rockyou.txt wordlists is need an hour … Is it because intel hd 4400 is an integrated gpu? That’s why it is slow ?

**Comment by PenguinKeeper7** [comment] 2024-04-28 11:33
Potentially, yes. Also, Hashcat needs a bit of VRAM in order to execute many tasks in parallel. Having very limited VRAM causes Hashcat to be unable to run many tasks in parallel, hence the very low speed. As I mentioned, using the CPU may actually be faster/more stable here but try it yourself and see

**Comment by Aggelos11** [comment] 2024-04-28 11:35
I did try but it’s still takes the same time … I hear there is a way to use both cpu and gpu… How to do that ?

**Comment by mohemiv** [comment] 2024-04-30 10:35
> I did try but it’s still takes the same time … I hear there is a way to use both cpu and gpu… How to do that ?

There is no proper way to do this. The only way to increase the speed in your case is to buy a GPU or rent it.

**Comment by PenguinKeeper7** [comment] 2024-05-03 10:43
> > I did try but it’s still takes the same time … I hear there is a way to use both cpu and gpu… How to do that ?
> 
> There is no proper way to do this. The only way to increase the speed in your case is to buy a GPU or rent it.

It is possible with `-D 1,2`, it's just strongly not recommended because the CPU is often too busy hashing instead of giving the significantly faster GPU work but yes, renting is good if possible

**Comment by Chick3nman** [comment] 2024-05-29 10:14
This is not a bug, user hardware appears to be inadequate for current hashcat resource requirements. Closing.

**Closed as completed by Chick3nman** 2024-05-29 10:14 UTC
