### ISSUE TITLE
Hashcat can't find the correct password for 7z.

### ISSUE THREAD

**Issue by 469312306** [hashcat/hashcat#3039] opened 2021-11-21 17:53 UTC
**Describe the bug**
Hashcat can't find the correct password.

**To Reproduce**
1. On windows, use hashcat-6.2.5, [7z2hashcat-1.5](https://github.com/philsmd/7z2hashcat/releases/tag/1.5).
2. Refer to https://github.com/469312306/debug_for_hashcat.

**Expected behavior**
Hashcat find the right password in word.txt.

**Hardware/Compute device (please complete the following information):**
- Compute device name: RTX 3060
- OpenCL/CUDA driver name: NVIDIA DRIVER
- OpenCL/CUDA driver version: 496.49
- OpenCL/CUDA driver source: [cuda_11.5.0_496.13_win10.exe](https://developer.download.nvidia.com/compute/cuda/11.5.0/local_installers/cuda_11.5.0_496.13_win10.exe)

**Hashcat version (please complete the following information):**
 - OS: Windows 10 Pro
 - Distribution: 21H1
 - Version: 19043.1348

**Diagnostic output compute devices:**

```
For NV: Post nvidia-smi output. This tool also exist on Windows
```
Mon Nov 22 01:33:48 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 496.49       Driver Version: 496.49       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
|  0%   32C    P8    15W / 170W |    999MiB / 12288MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       984    C+G   ...me\Application\chrome.exe    N/A      |
|    0   N/A  N/A      1352    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A      3340    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A      7364    C+G   ...icrosoft VS Code\Code.exe    N/A      |
|    0   N/A  N/A      7996    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A      8896    C+G   ...IA GeForce Experience.exe    N/A      |
|    0   N/A  N/A      9952    C+G   ...ekyb3d8bbwe\YourPhone.exe    N/A      |
|    0   N/A  N/A     10196    C+G   ...kyb3d8bbwe\Calculator.exe    N/A      |
|    0   N/A  N/A     10236    C+G   ...nputApp\TextInputHost.exe    N/A      |
|    0   N/A  N/A     10444    C+G   ...perience\NVIDIA Share.exe    N/A      |
|    0   N/A  N/A     10596    C+G   ...lPanel\SystemSettings.exe    N/A      |
|    0   N/A  N/A     10840    C+G   ...perience\NVIDIA Share.exe    N/A      |
|    0   N/A  N/A     11420    C+G   ...8wekyb3d8bbwe\Cortana.exe    N/A      |
|    0   N/A  N/A     11592    C+G   ...ram Files\LGHUB\lghub.exe    N/A      |
|    0   N/A  N/A     12028    C+G   ...batNotificationClient.exe    N/A      |
|    0   N/A  N/A     13168    C+G   ...4__8j3eq9eme6ctt\IGCC.exe    N/A      |
|    0   N/A  N/A     15672    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A     16252    C+G   ...obeNotificationClient.exe    N/A      |
+-----------------------------------------------------------------------------+

```
Post clinfo output
```
Number of platforms                               1
  Platform Name                                   NVIDIA CUDA
  Platform Vendor                                 NVIDIA Corporation
  Platform Version                                OpenCL 3.0 CUDA 11.5.76
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid cl_khr_pci_bus_info
  Platform Extensions with Version                cl_khr_global_int32_base_atomics                                 0x400000 (1.0.0)
                                                  cl_khr_global_int32_extended_atomics                             0x400000 (1.0.0)
                                                  cl_khr_local_int32_base_atomics                                  0x400000 (1.0.0)
                                                  cl_khr_local_int32_extended_atomics                              0x400000 (1.0.0)
                                                  cl_khr_fp64                                                      0x400000 (1.0.0)
                                                  cl_khr_3d_image_writes                                           0x400000 (1.0.0)
                                                  cl_khr_byte_addressable_store                                    0x400000 (1.0.0)
                                                  cl_khr_icd                                                       0x400000 (1.0.0)
                                                  cl_khr_gl_sharing                                                0x400000 (1.0.0)
                                                  cl_nv_compiler_options                                           0x400000 (1.0.0)
                                                  cl_nv_device_attribute_query                                     0x400000 (1.0.0)
                                                  cl_nv_pragma_unroll                                              0x400000 (1.0.0)
                                                  cl_nv_d3d10_sharing                                              0x400000 (1.0.0)
                                                  cl_khr_d3d10_sharing                                             0x400000 (1.0.0)
                                                  cl_nv_d3d11_sharing                                              0x400000 (1.0.0)
                                                  cl_nv_copy_opts                                                  0x400000 (1.0.0)
                                                  cl_nv_create_buffer                                              0x400000 (1.0.0)
                                                  cl_khr_int64_base_atomics                                        0x400000 (1.0.0)
                                                  cl_khr_int64_extended_atomics                                    0x400000 (1.0.0)
                                                  cl_khr_device_uuid                                               0x400000 (1.0.0)
                                                  cl_khr_pci_bus_info                                              0x400000 (1.0.0)
  Platform Numeric Version                        0xc00000 (3.0.0)
  Platform Extensions function suffix             NV
  Platform Host timer resolution                  0ns

  Platform Name                                   NVIDIA CUDA
Number of devices                                 1
  Device Name                                     NVIDIA GeForce RTX 3060
  Device Vendor                                   NVIDIA Corporation
  Device Vendor ID                                0x10de
  Device Version                                  OpenCL 3.0 CUDA
  Device UUID                                     63e4df28-0424-740d-5f96-68dd967f6c19
  Driver UUID                                     63e4df28-0424-740d-5f96-68dd967f6c19
  Valid Device LUID                               Yes
  Device LUID                                     5de3-000000000000
  Device Node Mask                                0x1
  Device Numeric Version                          0xc00000 (3.0.0)
  Driver Version                                  496.49
  Device OpenCL C Version                         OpenCL C 1.2 
  Device OpenCL C all versions                    OpenCL C                                                         0x400000 (1.0.0)
                                                  OpenCL C                                                         0x401000 (1.1.0)
                                                  OpenCL C                                                         0x402000 (1.2.0)
                                                  OpenCL C                                                         0xc00000 (3.0.0)
  Device OpenCL C features                        __opencl_c_fp64                                                  0xc00000 (3.0.0)
                                                  __opencl_c_images                                                0xc00000 (3.0.0)
                                                  __opencl_c_int64                                                 0xc00000 (3.0.0)
                                                  __opencl_c_3d_image_writes                                       0xc00000 (3.0.0)
  Latest conformance test passed                  v2021-02-01-00
  Device Type                                     GPU
  Device Topology (NV)                            PCI-E, 0000:01:00.0
  Device PCI bus info (KHR)                       PCI-E, 0000:01:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               28
  Max clock frequency                             1777MHz
  Compute Capability (NV)                         8.6
  Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x64
  Max work group size                             1024
  Preferred work group size multiple (device)     32
  Preferred work group size multiple (kernel)     32
  Warp size (NV)                                  32
  Max sub-groups per work group                   0
  Preferred / native vector sizes                 
    char                                                 1 / 1       
    short                                                1 / 1       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 0 / 0        (n/a)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              12884377600 (12GiB)
  Error Correction support                        No
  Max memory allocation                           3221094400 (3GiB)
  Unified memory for Host and Device              No
  Integrated memory (NV)                          No
  Shared Virtual Memory (SVM) capabilities        (core)
    Coarse-grained buffer sharing                 Yes
    Fine-grained buffer sharing                   No
    Fine-grained system sharing                   No
    Atomics                                       No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       4096 bits (512 bytes)
  Preferred alignment for atomics                 
    SVM                                           0 bytes
    Global                                        0 bytes
    Local                                         0 bytes
  Atomic memory capabilities                      relaxed, work-group scope
  Atomic fence capabilities                       relaxed, acquire/release, work-group scope
  Max size for global variable                    0
  Preferred total size of global vars             0
  Global Memory cache type                        Read/Write
  Global Memory cache size                        802816 (784KiB)
  Global Memory cache line size                   128 bytes
  Image support                                   Yes
    Max number of samplers per kernel             32
    Max size for 1D images from buffer            268435456 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   0 bytes
    Pitch alignment for 2D image buffers          0 pixels
    Max 2D image size                             32768x32768 pixels
    Max 3D image size                             16384x16384x16384 pixels
    Max number of read image args                 256
    Max number of write image args                32
    Max number of read/write image args           0
  Pipe support                                    No
  Max number of pipe args                         0
  Max active pipe reservations                    0
  Max pipe packet size                            0
  Local memory type                               Local
  Local memory size                               49152 (48KiB)
  Registers per block (NV)                        65536
  Max number of constant args                     9
  Max constant buffer size                        65536 (64KiB)
  Generic address space support                   No
  Max size of kernel argument                     4352 (4.25KiB)
  Queue properties (on host)                      
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Device enqueue capabilities                     (n/a)
  Queue properties (on device)                    
    Out-of-order execution                        No
    Profiling                                     No
    Preferred size                                0
    Max size                                      0
  Max queues on device                            0
  Max events on device                            0
  Prefer user sync for interop                    No
  Profiling timer resolution                      1000ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Non-uniform work-groups                       No
    Work-group collective functions               No
    Sub-group independent forward progress        No
    Kernel execution timeout (NV)                 Yes
    Concurrent copy and kernel execution (NV)     Yes
      Number of async copy engines                5
    IL version                                    (n/a)
    ILs with version                              (n/a)
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                (n/a)
  Built-in kernels with version                   (n/a)
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid cl_khr_pci_bus_info
  Device Extensions with Version                  cl_khr_global_int32_base_atomics                                 0x400000 (1.0.0)
                                                  cl_khr_global_int32_extended_atomics                             0x400000 (1.0.0)
                                                  cl_khr_local_int32_base_atomics                                  0x400000 (1.0.0)
                                                  cl_khr_local_int32_extended_atomics                              0x400000 (1.0.0)
                                                  cl_khr_fp64                                                      0x400000 (1.0.0)
                                                  cl_khr_3d_image_writes                                           0x400000 (1.0.0)
                                                  cl_khr_byte_addressable_store                                    0x400000 (1.0.0)
                                                  cl_khr_icd                                                       0x400000 (1.0.0)
                                                  cl_khr_gl_sharing                                                0x400000 (1.0.0)
                                                  cl_nv_compiler_options                                           0x400000 (1.0.0)
                                                  cl_nv_device_attribute_query                                     0x400000 (1.0.0)
                                                  cl_nv_pragma_unroll                                              0x400000 (1.0.0)
                                                  cl_nv_d3d10_sharing                                              0x400000 (1.0.0)
                                                  cl_khr_d3d10_sharing                                             0x400000 (1.0.0)
                                                  cl_nv_d3d11_sharing                                              0x400000 (1.0.0)
                                                  cl_nv_copy_opts                                                  0x400000 (1.0.0)
                                                  cl_nv_create_buffer                                              0x400000 (1.0.0)
                                                  cl_khr_int64_base_atomics                                        0x400000 (1.0.0)
                                                  cl_khr_int64_extended_atomics                                    0x400000 (1.0.0)
                                                  cl_khr_device_uuid                                               0x400000 (1.0.0)
                                                  cl_khr_pci_bus_info                                              0x400000 (1.0.0)

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              Success [NV]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  Invalid device type for platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform

```
Post hashcat -I output
```
hashcat (v6.2.5) starting in backend information mode

CUDA Info:
==========

CUDA.Version.: 11.5

Backend Device ID #1 (Alias: #2)
  Name...........: NVIDIA GeForce RTX 3060
  Processor(s)...: 28
  Clock..........: 1777
  Memory.Total...: 12287 MB
  Memory.Free....: 11282 MB
  PCI.Addr.BDFe..: 0000:01:00.0

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: NVIDIA Corporation
  Name....: NVIDIA CUDA
  Version.: OpenCL 3.0 CUDA 11.5.76

  Backend Device ID #2 (Alias: #1)
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: NVIDIA GeForce RTX 3060
    Version........: OpenCL 3.0 CUDA
    Processor(s)...: 28
    Clock..........: 1777
    Memory.Total...: 12287 MB (limited to 3071 MB allocatable in one block)
    Memory.Free....: 11520 MB
    OpenCL.Version.: OpenCL C 1.2 
    Driver.Version.: 496.49
    PCI.Addr.BDF...: 01:00.0

**Additional context**
Add any other context about the problem here. For instance, it was working with hashcat version X.X.X (also please post output from older versions).
Never works.

**Comment by jsteube** [comment] 2021-11-21 20:33
What is the password?

**Comment by 469312306** [comment] 2021-11-22 01:55
> What is the password?

Wakarimasu! Sat 06 Nov 2021 03:44:15 PM CST you-kali-vm x86_64 GNU/Linux 8

**Comment by jsteube** [comment] 2021-11-22 08:30
OK, at least I can reproduce the problem. You are right, Hashcat should crack the password, but it doesn't. Can you explain exactly how did you create the .7z? Maybe this helps debugging the problem. Especially the exact 7z version and flags/options you were using.

**Comment by 469312306** [comment] 2021-11-22 14:20
> OK, at least I can reproduce the problem. You are right, Hashcat should crack the password, but it doesn't. Can you explain exactly how did you create the .7z? Maybe this helps debugging the problem. Especially the exact 7z version and flags/options you were using.

The command was ```7za a flag2.7z flag2.wav -p"Wakarimasu! `date` `uname -nom` `nproc`"```, I can reproduce it on my ubuntu, which 7z output was:
```
7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (A0655),ASM,AES-NI)
```
The origin 7z was created on another Linux, which output was:
```
7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (806EC),ASM,AES-NI)
```

**Comment by 469312306** [comment] 2021-11-24 13:12
Anyone has any suggestion?

**Comment by philsmd** [comment] 2021-11-29 15:55
I guess we need to troubleshoot/debug this in detail and see if hashcat is producing the correct AES key etc... this will take some time, but I will hopefully come to a conclusion what the problem is and how to fix it within the next few days/weeks (when I get some free time to debug this carefully).

Thanks for reporting @469312306

**Comment by 469312306** [comment] 2021-11-29 21:34
Thanks, hope the bug can be found and be repaired.

**Comment by philsmd** [comment] 2021-12-03 15:57
Hey @469312306 ,
there is good (and maybe also a tiny fraction of bad) news. I've investigated this archive now and I've quickly come to the conclusion that this `7z archive` is very special (mainly because of the `.wav` content, the password doesn't matter at all, i.e. pass is NOT the culprit): the 7z archive does use `Delta encoding` (a data preprocessing filter, before the actual compression is performed, see https://en.wikipedia.org/wiki/Delta_encoding and https://en.wikipedia.org/wiki/7z#Pre-processing_filters).

I've found this out very quickly by just analyzing the archive (not even needed to debug the code, phew ! saved me a lot of work)... just have a look here:
"normal" 7z files
```
$ 7z l test.7z
...
Method = LZMA2:14 7zAES
...
```

your flag2.7z file:
```
$ 7z l flag2.7z
...
Method = Delta LZMA2:6m 7zAES
...
```

This means that the data can't be checksumed (CRC32) immediately after decompressing it, but needs to be run through a filter (as said `Delta Encoding/Decoding`, also see the `k_Delta` codec id in the 7z source code, and the functions like `Delta_Init ()` and `Delta_Decode ()`, this is actually also included in our dependencies, but not used: see https://github.com/hashcat/hashcat/blob/6d46185488ac21c53d6232d6c4132ce03d2612aa/deps/LZMA-SDK/C/Delta.c#L89).

So to sum it up (I've also mentioned some details within a `7z2hashcat` commit, see https://github.com/philsmd/7z2hashcat/pull/34, and the release notes for `7z2hashcat 1.6`, see https://github.com/philsmd/7z2hashcat/releases/tag/1.6), we had actually 2 problems:
1. `7z2hashcat` didn't have the correct information for hashcat to let `hashcat` know `Delta Encoding` would be needed (that let to your false negatives aka exhausted aka not cracking)
2. `hashcat` currently has no support for `preprocessing filters` (neither `Delta`, nor `BCJ` or others).

My suggestion now is, that because we have this additional information and a new version of `7z2hashcat`, we would need to deal with this new situation by testing the `7z2hashcat 1.6` release version carefully (it should block the output and say that `hashcat` doesn't support it for now) and we could also think about adding support by opening a NEW hashcat github issue (if we decide to add `Delta Encoding` / preprocessor support).

How important is this support for `Delta` for you ? It might need some extra time for coding and troubleshooting how this extra `Delta_Decode ()` call works... It's also not clear to me now, if we really need an extra (large) output buffer for the manipulated data or if the same data buffers (AES decrypted, LZMA decompressed data) that we already have can be used also for DELTA (or other preprocessors... I mean the data length could eventually change a lot !) .... It would also be interesting which combinations we should support LZMA1 + Delta and LZMA2 + Delta (not sure what else we need) ?

So my suggestion is to close this issue and test the new `7z2hashcat` release (ATTENTION: it should now just say that `DELTA` isn't supported by hashcat yet) and maybe later on try to add `Delta support` in a completely new github issue for `hashcat` (to request the Delta encoding/decoding support for 7z archives). What do you think ?

I will close this for now and let you decide if it's important enough to open a new feature request, the hash now should be different and look somethink like this (you can just change this line in the `7z2hashcat.pl` file to output these hashes
```
my @PASSWORD_RECOVERY_TOOL_SUPPORTED_PREPROCESSORS = ( 0, 8 );
``` 

8 is the new value that means `Delta encoding` is supported (but be aware that these hashes can't be cracked yet, we would need to add support within `hashcat`

[hash.txt](https://github.com/hashcat/hashcat/files/7650739/hash.txt)

Thanks for reporting @469312306 , I think this is the best solution to make it clear that this would require to add support for a new feature, but you still found an important bug in `7z2hashcat`. That's great. Thx

Let me know here if the new version of `7z2hashcat` "fixes" the problem of an invalid hash (=> false negatives) and if you are interested in the support for `Delta encoding`

**Closed as completed by philsmd** 2021-12-03 15:57 UTC
Labels: bug
