### ISSUE TITLE
Kernel Build Failure when running -m 16800

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [hashcat/hashcat#2269] opened 2020-01-09 16:07 UTC
Kernel build fails with these details and this message:
Mesa 13.0.6
Linux 4.9.0
gcc 4:6.3.0

    * Device #1: build_options '-D KERNEL_STATIC -I OpenCL -I /usr/share/hashcat/OpenCL -D LOCAL_MEM_TYPE=1 -D VENDOR_ID=16 -D CUDA_ARCH=0 -D HAS_ADD=0 -D HAS_ADDC=0 -D HAS_SUB=0 -D HAS_SUBC=0 -D HAS_VADD=0 -D HAS_VADDC=0 -D HAS_VADD_CO=0 -D HAS_VADDC_CO=0 -D HAS_VSUB=0 -D HAS_VSUBB=0 -D HAS_VSUB_CO=0 -D HAS_VSUBB_CO=0 -D HAS_VPERM=0 -D HAS_VADD3=0 -D HAS_VBFE=0 -D HAS_BFE=0 -D HAS_LOP3=0 -D HAS_MOV64=0 -D HAS_PRMT=0 -D VECT_SIZE=1 -D DEVICE_TYPE=4 -D DGST_R0=0 -D DGST_R1=1 -D DGST_R2=2 -D DGST_R3=3 -D DGST_ELEM=4 -D KERN_TYPE=16800 -D ATTACK_EXEC=10 -D ATTACK_KERN=3 -D _unroll '
    * Device #1: build_options_module '-D KERNEL_STATIC -I OpenCL -I /usr/share/hashcat/OpenCL -D LOCAL_MEM_TYPE=1 -D VENDOR_ID=16 -D CUDA_ARCH=0 -D HAS_ADD=0 -D HAS_ADDC=0 -D HAS_SUB=0 -D HAS_SUBC=0 -D HAS_VADD=0 -D HAS_VADDC=0 -D HAS_VADD_CO=0 -D HAS_VADDC_CO=0 -D HAS_VSUB=0 -D HAS_VSUBB=0 -D HAS_VSUB_CO=0 -D HAS_VSUBB_CO=0 -D HAS_VPERM=0 -D HAS_VADD3=0 -D HAS_VBFE=0 -D HAS_BFE=0 -D HAS_LOP3=0 -D HAS_MOV64=0 -D HAS_PRMT=0 -D VECT_SIZE=1 -D DEVICE_TYPE=4 -D DGST_R0=0 -D DGST_R1=1 -D DGST_R2=2 -D DGST_R3=3 -D DGST_ELEM=4 -D KERN_TYPE=16800 -D ATTACK_EXEC=10 -D ATTACK_KERN=3 -D _unroll  '
    * Device #1: Kernel m16800-pure.6df017dc.kernel not found in cache! Building may take a while...
    clBuildProgram(): CL_BUILD_PROGRAM_FAILURE
    
    <unknown>:0:0: in function gpu_decompress void (%struct.pw_idx addrspace(1)*, i32 addrspace(1)*, %struct.pw addrspace(1)*, i64): unsupported initializer for address space
    
    * Device #1: Kernel /usr/share/hashcat/OpenCL/m16800-pure.cl build failed - proceeding without this device.

**Comment by philsmd** [comment] 2020-01-10 08:45
please try to not use pocl and/or mesa for testing.

What hardware do you have ? Can you please try to use the vendors driver ?

What version of hashcat do you use ? The git/beta version ?

Could you also try with other devices like --opencl-device-types 1 (short -D) for using your CPU etc.

It is known that both pocl and mesa are very buggy and even fail to build the most easiest OpenCL-compatible kernels for us :(
This is very unfortunate, but there was/is little progress in those open-source drivers in what regards to correctly compile some basic OpenCL code :(

If you agree that this is a mesa problem only and it works with the proprietary drivers, please do not forget to close the issue. Thx

**Comment by philsmd** [comment] 2020-01-13 09:56
@TanyaEleventhGoddess any update here ? we need some user feedback here on whether this is only a problem of buggy open source driver or if there is also a problem with the vendor driver (probably not, but you never know).
If we get no answer within the next days/weeks, we probably need to close this issue as invalid soon (because it doesn't seem to be a hashcat issue at all, just a setup/installation/driver issue).

**Comment by TanyaEleventhGoddess** [comment] 2020-01-19 00:17
Mon, 13 Jan 2020 09:56:16 +0000 (UTC) philsmd <notifications@github.com>:
> @TanyaEleventhGoddess any update here ? we need some user feedback here on whether this is only a problem of buggy open source driver or if there is also a problem with the vendor driver (probably not, but you never know).
> If we get no answer within the next days/weeks, we probably need to close this issue as invalid soon (because it doesn't seem to be a hashcat issue at all, just a setup/installation/driver issue).

I'm using debian oldstable and nonfree drivers firmware-amd-graphics-20161130
I've tried both the development and the stable latest version
I guess it should work like this

**Comment by philsmd** [comment] 2020-01-22 08:25
2016 doesn't really sound very new... sounds like it is about 4 years old. that's a lot of time when it comes to software.

Did you try to remove all this old and "wrong" drivers and install the vendor (proprietary) driver instead ?

You didn't really answer my question about which hardware/GPU you have... this is really important to make any recommendations. i.e. some AMD hardware works with ROCm (https://rocm.github.io/ROCmInstall.html#hardware-and-software-support), other  needs the ("older") amdgpu driver from https://www.amd.com/en/support

in any case, this doesn't really sound like a hashcat bug... but rather like an user problem with very, very old drivers (and probably hardware too), but I could be wrong here.

I think it makes more sense to discuss this user experiences/problems in the hashcat forum... we can't really change anything in code here, if we don't even no what the problem is and if the latest vendor driver works (or rather: might work) without problem etc (the hashcat forum over https://hashcat.net/forum has already many threads about this and if nothing pops up you can always ask your questions there).

Should we close this ? Or do you think a (simple) change in code would make this (or your old driver) work ?

**Comment by jsteube** [comment] 2020-01-22 08:33
> unsupported initializer for address space

Is a known problem in MESA not hashcat

**Closed as completed by jsteube** 2020-01-22 08:33 UTC

**Comment by TanyaEleventhGoddess** [comment] 2020-01-27 16:16
Wed, 22 Jan 2020 00:25:47 -0800 philsmd <notifications@github.com>:
> 2016 doesn't really sound very new... sounds like it is about 4 years old. that's a lot of time when it comes to software.
> 
> Did you try to remove all this old and "wrong" drivers and install the vendor (proprietary) driver instead ?
> 
> You didn't really answer my question about which hardware/GPU you have... this is really important to make any recommendations. i.e. some AMD hardware works with ROCm (https://rocm.github.io/ROCmInstall.html#hardware-and-software-support), other  needs the ("older") amdgpu driver from https://www.amd.com/en/support
> 
> in any case, this doesn't really sound like a hashcat bug... but rather like an user problem with very, very old drivers (and probably hardware too), but I could be wrong here.
> 
> I think it makes more sense to discuss this user experiences/problems in the hashcat forum... we can't really change anything in code here, if we don't even no what the problem is and if the latest vendor driver works without problem etc (the hashcat forum over https://hashcat.net/forum has already many threads about this and if nothing pops up you can always ask your questions there).
> 
> Should we close this ? Or do you think a (simple) change in code would make this (or your old driver) work ?
> 
I think you can close this, thanks for asking
