### ISSUE TITLE
Custom charset is undefined *BUG*

### ISSUE THREAD

**Issue by poutsarxidis** [hashcat/hashcat#3568] opened 2023-01-07 18:35 UTC
I try to crack a md5 hash with hashcat using a brute force mask attack.
The file containing the mask looks like this:

?1?1?1?1?d?d?d?d
?1?1?1?1?1?d?d?d?d
?1?l?l?l?l?l?d?d?d?d
?1?l?l?l?l?l?l?d?d?d?d

When I type this command it works perfectly:
hashcat -a 3 -m 0 target.txt -1 ?u?l ?1?1?1?1?1?1?1

BUT when I type this command:
hashcat -a 3 -m 0 target.txt -1 ?u?l mask_file.txt

Hashcat can't define the custom charset so I get an error ''custom charset 1 is undefined''

Anyone that knows whats this?

**Comment by Chick3nman** [comment] 2023-01-07 19:00
Custom character sets need to be defined inline in the mask file. Please read the wiki page here: https://hashcat.net/wiki/doku.php?id=mask_attack#hashcat_mask_files

Closing as not a bug.

**Closed as completed by Chick3nman** 2023-01-07 19:00 UTC
Labels: bug
