### ISSUE TITLE
-m20500 doesn't work with -i -a3

### ISSUE THREAD

**Issue by magnumripper** [hashcat/hashcat#2939] opened 2021-08-16 22:49 UTC
This (using `-i`) bugs out right after getting to length 2 while it works fine without `-i` manually trying various lengths of mask:
```
$ ./hashcat -w3 -m20500 c4490e28b414a23d91404b31 -i -a3 ?a?a?a?a?a?a
hashcat (v6.2.3-235-g49117745c) starting

CUDA API (CUDA 11.3)
====================
* Device #1: NVIDIA GeForce RTX 2080 Ti, 10848/11018 MB, 68MCU

OpenCL API (OpenCL 3.0 CUDA 11.3.55) - Platform #2 [NVIDIA Corporation]
=======================================================================
* Device #3: NVIDIA GeForce RTX 2080 Ti, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

(...)

Approaching final keyspace - workload adjusted.           

Session..........: hashcat                                
Status...........: Exhausted
Hash.Name........: PKZIP Master Key
Hash.Target......: c4490e28b414a23d91404b31
Time.Started.....: Tue Aug 17 00:25:25 2021 (0 secs)
Time.Estimated...: Tue Aug 17 00:25:25 2021 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Mask.......: ?a [1]
Guess.Queue......: 1/6 (16.67%)
Speed.#1.........:    23857 H/s (0.02ms) @ Accel:256 Loops:95 Thr:512 Vec:1
Recovered........: 0/1 (0.00%) Digests
Progress.........: 95/95 (100.00%)
Rejected.........: 0/95 (0.00%)
Restore.Point....: 1/1 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-95 Iteration:0-95
Candidate.Engine.: Device Generator
Candidates.#1....: s ->  
Hardware.Mon.#1..: Temp: 43c Fan: 29% Util:  9% Core:1740MHz Mem:6800MHz Bus:8

cuEventSynchronize(): an illegal memory access was encountered

cuEventSynchronize(): an illegal memory access was encountered
(...)
```
Many more same or similar errors until it stops (crashes?)

Trying 20510 instead, all works fine:
```
$ ./hashcat -w3 -m20510 c4490e28b414a23d91404b31 -i -a3 ?a?a?a?a?a?a
(...)
c4490e28b414a23d91404b31:W4sF0rgotten
```

The problem seems to having been introduced by d4997d125: That point in history fails while the previous one (namely d85a9b602) works fine.

**Comment by Xanadrel** [comment] 2021-08-16 22:54
Can confirm, for me it's a bunch of:
```
cuEventSynchronize(): unspecified launch failure
cuLaunchKernel(): unspecified launch failure
cuMemcpyHtoDAsync(): unspecified launch failure
cuMemFree(): unspecified launch failure
...
```

**Comment by jsteube** [comment] 2021-08-17 13:47
OK yeah can reproduce, too. What is that you bring here @magnumripper :) Nice find..

**Comment by jsteube** [comment] 2021-08-17 13:55
I think is an OOB read here, in case of password 0.

```
  for (u32 pos = pw_len - 1; pos >= 4; pos--)
  {
    const u32 t = hc_bfe_S (pws[gid].i[pos / 4], (pos & 3) * 8, 8);
```

The kernel should be resistant to zero length passwords, so this needs a fix by simply switching the "u32 pos" to "int pos". 

There's also the question why it has to handle a zero length password and I think is related to the autotune changes. So the bug was in there all the time, it was just never triggered.

**Comment by jsteube** [comment] 2021-08-17 15:56
OK, this should be fixed with commit https://github.com/hashcat/hashcat/commit/92546039606bd82650dc77c5fa3e84b7cd01d7fc thanks for reporting!

There's two bugs actually. The first one was the OOB read as described above, but there was more to it.

The bug popped up after the kernel thread auto tune feature was added. So something happend that the kernel received zero length passwords due to this change. And the reason for this was that the per device hardware_power variable (and also kernel_power variable which depends on hard_power, too) needs an update after every iteration since it's no longer a fixed value. The reason is here:

```
    const u32 kernel_power_max = device_param->hardware_power * kernel_accel_max;
```

In the  first iteration (and you could see it never crashed in the first iteration), hardware_power had the real hardware_power and autotune initialized them all to password length 7 before calling the kernel (so it will not crash) here:

```
      if (run_cuda_kernel_atinit (hashcat_ctx, device_param, device_param->cuda_d_pws_buf, kernel_power_max) == -1) return -1;
```

Then autotune engine does its thing, and may decide to lower the thread count from the maximum to a lower value. If that happens, then this has an effect on hardware_power a bit later:

```
  device_param->kernel_threads = kernel_threads;

  const u32 hardware_power = ((hashconfig->opts_type & OPTS_TYPE_MP_MULTI_DISABLE) ? 1 : device_param->device_processors) * device_param->kernel_threads;

  device_param->hardware_power = hardware_power;
```

In the next iteration, this first line now comes to a different resulting value:

```
    const u32 kernel_power_max = device_param->hardware_power * kernel_accel_max;
```

and then, this line initializes only half of the candidates with length 7:

```
      if (run_cuda_kernel_atinit (hashcat_ctx, device_param, device_param->cuda_d_pws_buf, kernel_power_max) == -1) return -1;
```

However, when the kernel is actually called to measure the time, it is called with the correct hardware_power:

```
static double try_run (hashcat_ctx_t *hashcat_ctx, hc_device_param_t *device_param, const u32 kernel_accel, const u32 kernel_loops, const u32 kernel_threads)
...
  const u32 hardware_power = ((hashconfig->opts_type & OPTS_TYPE_MP_MULTI_DISABLE) ? 1 : device_param->device_processors) * kernel_threads;
...

---

  u32 kernel_threads = kernel_threads_max;
...
      double exec_msec = try_run (hashcat_ctx, device_param, xxx, xxx, kernel_threads);
...

```

So it was processing zero length passwords. This is now also fixed by resetting hardware_power before calling autotune engine.

**Closed as completed by jsteube** 2021-08-17 15:56 UTC
Labels: bug
