### ISSUE TITLE
UTF16LE Conversion Failure Leading to Pseudo-False Positives/Negatives

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#3228] opened 2022-03-17 23:23 UTC
Several of our kernels make use of UTF8 -> UTF16LE conversions during candidate processing. For optimized kernels, such as -m 1000 NTLM, we make use of an optimized but incomplete conversion step to gain speed at the cost of a small amount of coverage for out of range characters. This incomplete conversion currently works as intended however the following commit attempted to add a complete or "true" conversion for use in pure kernels where the coverage is more valuable than the speed.

First commit with this issue: https://github.com/hashcat/hashcat/commit/d343e2c4a0699bb8a6fd8d47b06fe4f5a157c5e8

There is a bug here that appears to be affecting a handful of character sets. During processing, the candidate buffer is replaced with null bytes before the hashing step. This leads to a pseudo-false positive in the case where the target is an empty(null) hash, and a pseudo-false negative where the target is the hash of the properly converted candidate.

This issue is simple to reproduce using the empty NTLM hash.

Empty hash: `31d6cfe0d16ae931b73c59d7e0c089c0`

test.txt: `$HEX[f4f2f2f43134]` which appears as `фттф14` when decoded from hex

```
hashcat -a 0 -m 1000 31d6cfe0d16ae931b73c59d7e0c089c0 test.txt --potfile-disable

31d6cfe0d16ae931b73c59d7e0c089c0:$HEX[f4f2f2f43134]

Session..........: hashcat
Status...........: Exhausted
Hash.Mode........: 1000 (NTLM)
Hash.Target......: 31d6cfe0d16ae931b73c59d7e0c089c0 
Time.Started.....: Thu Mar 17 18:13:30 2022 (0 secs)
Time.Estimated...: Thu Mar 17 18:13:30 2022 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: File (test.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:     3513 H/s (0.01ms) @ Accel:2048 Loops:1 Thr:32 Vec:1
Recovered........: 1/1 (100.00%) Digests
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 1/1 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidate.Engine.: Device Generator
Candidates.#1....: $HEX[f4f2f2f43134] -> $HEX[f4f2f2f43134]
Hardware.Mon.#1..: Temp: 36c Fan: 45% Util: 25% Core:1725MHz Mem:9501MHz Bus:16

Started: Thu Mar 17 18:13:28 2022
Stopped: Thu Mar 17 18:13:32 2022
```

The cracking/comparison are not incorrect, which makes this not a "true" false positive. Internally, it hashes the null buffer and compares it to the null hash, producing a match. But because the candidate was incorrectly transformed into a null buffer, it still produces a pseudo false positive result and the output is even assigned to the offending candidate.

Due to the usage of MD4 UTF16LE in NTLM and the usage of NTLM as the basis for many of the Windows related hashes, all pure kernels invoking this function are affected making this a fairly high impact issue. This includes NetNTLM, Kerberos, DCC/2, and potentially other modes.

**Comment by jsteube** [comment] 2022-03-18 07:22
Are you sure that is the correct screenshot from the status screen? I find it concerning that the status output from hashcat here states "exhausted". If the hash is cracked (no matter if false positive or not) it has to say cracked.

However, if I reproduce this locally it works fine:

```
root@ht:~/hashcat# ./hashcat -a 0 -m 1000 31d6cfe0d16ae931b73c59d7e0c089c0 test.txt --potfile-disable
hashcat (v6.2.5-340-g98b89e43d) starting

CUDA API (CUDA 11.4)
====================
* Device #1: NVIDIA GeForce RTX 2080 Ti, 10855/11019 MB, 68MCU

OpenCL API (OpenCL 3.0 CUDA 11.4.56) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: NVIDIA GeForce RTX 2080 Ti, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Zero-Byte
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Hash
* Single-Salt
* Raw-Hash

ATTENTION! Pure (unoptimized) backend kernels selected.
Pure kernels can crack longer passwords, but drastically reduce performance.
If you want to switch to optimized kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 1194 MB

Dictionary cache hit:
* Filename..: test.txt
* Passwords.: 1
* Bytes.....: 19
* Keyspace..: 1

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.           

31d6cfe0d16ae931b73c59d7e0c089c0:$HEX[f4f2f2f43134]       
                                                          
Session..........: hashcat
Status...........: Cracked
Hash.Mode........: 1000 (NTLM)
Hash.Target......: 31d6cfe0d16ae931b73c59d7e0c089c0
Time.Started.....: Fri Mar 18 08:19:04 2022 (0 secs)
Time.Estimated...: Fri Mar 18 08:19:04 2022 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: File (test.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:     5202 H/s (0.01ms) @ Accel:2048 Loops:1 Thr:32 Vec:1
Recovered.Total..: 1/1 (100.00%) Digests
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 0/1 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidate.Engine.: Device Generator
Candidates.#1....: $HEX[f4f2f2f43134] -> $HEX[f4f2f2f43134]
Hardware.Mon.#1..: Temp: 52c Fan: 31% Util:  1% Core:1950MHz Mem:6800MHz Bus:16

Started: Fri Mar 18 08:18:59 2022
Stopped: Fri Mar 18 08:19:05 2022
```

**Comment by realSnoopy** [comment] 2022-03-18 10:07
but 31d6cfe0d16ae931b73c59d7e0c089c0 is the NTLM for an empty input, so basically hashcat states that
`NTLM('') == NLTM($HEX[f4f2f2f43134])`
which isn't correct

anyway shouldn't hashcat recognize this empty hash and skip it? when starting a cracking job i believe hashcat tells XXX hashes removed, empty hashes or found in potfile?

**Comment by Chick3nman** [comment] 2022-03-18 14:28
> Are you sure that is the correct screenshot from the status screen? I find it concerning that the status output from hashcat here states "exhausted". If the hash is cracked (no matter if false positive or not) it has to say cracked.

Good spot, I had added --keep-guessing but accidentally did not add it to the command in the original issue. That's why it says exhausted.

As realSnoopy has already pointed out, however, that doesn't change the highlighted issue. To answer your question @realSnoopy, --potfile-disable intentionally skips that check so the hash is not dropped.

**Comment by jsteube** [comment] 2022-03-30 18:15
The real problem here is the very beginning in this thread. The $HEX[f4f2f2f43134] byte stream is simply not a valid UTF8. In fact, it's not even a valid ISO-8859-[1-15]. I don't even know how you come up from this byte stream to `фттф14`. 

This is how valid UTF8 would look like:

```
$ echo -n фттф14 | xxd
00000000: d184 d182 d182 d184 3134                 ........14
```

But let me explain what's happening. At some point the string is getting processed by hc_enc_validate_utf8() (or depending on hash-mode it's wrapping function hc_enc_validate_utf8_global()). This function checks if this is a valid utf8 stream and it correctly tests this to be negative.

So now the questions is, how should hashcat react. Because this is done in a parallel computing world we can't win anything by skipping the candidate (to make it faster), because it has to wait for the other threads to finish and would be just sit there and wait. That's why we return a zero length string as a result and not a negative value.

But a zero length string that is what the `31d6cfe0d16ae931b73c59d7e0c089c0` is, so it gets cracked. Another problem is that it's not possible for a password cracker to return the password candidate in the original form on GPU back to the host, because that would require too much memory. We need to assume that (in a worst case) every password candidate would crack a hash, so for instance on a 2080Ti we need the following buffer: 260 (pw_t) * 68 (mcu) * 1024 * 1024 = 18.538.823.680 byte, but we don't have that much memory on GPU. So hashcat host has to reproduce exactly what hashcat gpu did.

Obviously, that is not the case. So we could investigate and find the reason and fix that. But the question is if that's actually the best fix or would it better to mark the password candidate as invalid. That would actually lead to a small performance degradation.

**Comment by jsteube** [comment] 2022-03-30 18:54
OK I fixed this with another solution (3). If the input is invalid, instead of returning a candidate length 0 it will return a candidate length -1. That will result in an invalid hash, so it will not crack it. See commit https://github.com/hashcat/hashcat/commit/753994bfe04fc8a23dabf0be9fd0637beebc25d3

Please close the issue if that's fine for you.

**Comment by Chick3nman** [comment] 2022-03-30 19:04
Ok, so I understand the issue as two fold. Something caused an external issue in the candidate that lead to it not being UTF-8 encoded properly so the original testing for a false negative was indeed incorrect. The false positive resulted from hashcat handling this incorrect candidate since it was not a valid UTF-8 input, and was misinterpreted due to it resulting in a 0 length string. If the commit fixes this issue for all kernels depending on this conversion, then yes I think that solves the core problem(s) and you can close this. This was originally spotted as the false positive on an empty NTLMv1/v2, which depends on the NTLM code which then depends on the conversion.

**Comment by jsteube** [comment] 2022-03-31 10:59
Should be fixed

**Closed as completed by jsteube** 2022-03-31 10:59 UTC
Labels: bug
