### ISSUE TITLE
tests: verify of -m 25400 = PDF edit password is broken

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#2838] opened 2021-06-19 09:10 UTC
I tested to run our verification script (`tools/test.pl`) with the example hash:
```
$pdf$2*3*128*-3904*1*16*631ed33746e50fba5caf56bcc39e09c6*32*5f9d0e4f0b39835dace0d306c40cd6b700000000000000000000000000000000*32*842103b0a0dc886db9223b94afe2d7cd63389079b61986a4fcf70095ad630c24
```

(the password should be `hashcat`)

I've tested it like this:
```
perl tools/test.pl verify 25400 hash in out && cat out
```

the file `out` should now contain the `cracked  hashes`, but it does not. (the input was the above hash within the `hash` file and the hash and password - separated by : - within the `in` file) 

I've investigated this a little bit and it seems that the `user` vs `owner` password for this hash are different (but I don't think that is the reason or "fix" for this problem).

```
user password ($u variable in `tools/test_modules/m25400.pm`) different:
37747ccd83e3fceccdc1c06de41a0904 for password hashcat
5f9d0e4f0b39835dace0d306c40cd6b7 for empty password (zero length)
```

I think the main problem here is that whenever we want to verify one type of hash (`user` vs `owner`) , the other one needs to be kind of ignored/skipped and therefore send to the output/print AS-IS... i.e. whenever the `owner` password is correct, we shouldn't generate a "different"/"new" `user` hash with the same password... we should just marked the password as correct by passing the other part AS-IS (even if different password)...

Later on (different topic), we could think about changing the default example hash to a hash that uses `hashcat`  as the password for both `user` and `owner` part, but that's a different story !

cc:  @thatux

Thanks a lot guys

---

update: I also noted a strange/useless variable within the test script,  that we should remove:
https://github.com/hashcat/hashcat/blob/05125eb67c9da98e349dabea50f81f24080f6347/tools/test_modules/m25400.pm#L143

**Comment by thatux** [comment] 2021-06-23 20:43
Hi @philsmd,


Nice find, I'm not a 100% sure whether I can follow you compeletly but I think I agree.

Have you seen these comments: https://github.com/hashcat/hashcat/pull/2739#issuecomment-816998851
#2739 
In short the best idea as @jsteube suggested is to add the password required as a kind of salt, do you agree @philsmd?

Am I correct that these are the files you use?


```
cat hash
$pdf$2*3*128*-3904*1*16*631ed33746e50fba5caf56bcc39e09c6*32*5f9d0e4f0b39835dace0d306c40cd6b700000000000000000000000000000000*32*842103b0a0dc886db9223b94afe2d7cd63389079b61986a4fcf70095ad630c24

cat in #first hash then password
$pdf$2*3*128*-3904*1*16*631ed33746e50fba5caf56bcc39e09c6*32*5f9d0e4f0b39835dace0d306c40cd6b700000000000000000000000000000000*32*842103b0a0dc886db9223b94afe2d7cd63389079b61986a4fcf70095ad630c24:hashcat
```

I'll try to run hashcat to see whether I can reproduce.
I'm guessing this is from the test results directory?
```
user password ($u variable in `tools/test_modules/m25400.pm`) different:
37747ccd83e3fceccdc1c06de41a0904 for password hashcat
5f9d0e4f0b39835dace0d306c40cd6b7 for empty password (zero length)
```

**Comment by thatux** [comment] 2021-06-29 19:05
Some stuff I've tried, but I can't get the test.pl script working yet; it won't return any output :S
I'm reading up on how to use test.pl and test.sh

```
sudo -EH ./tools/install_modules.sh

rm hash
rm in

#generate a hash
IN=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-16};echo;); echo $IN

echo $IN | perl tools/test.pl passthrough 25400 >> hash
echo $IN | perl tools/test.pl potthrough 25400 >> in

cat hash
186002588751273779265710026*32*c9f192a62944f01342c4c4ccf1d327a200000000000000000000000000000000*32*5e61fffa087f04c85b5d7529a90c94bc717e51594dbbdac2427023aed74efa2f
cat in
566429542147829307704965600*32*33bc9e5e4eecced4f41e0d1cc1694ee800000000000000000000000000000000*32*5e61fffa087f04c85b5d7529a90c94bc717e51594dbbdac2427023aed74efa2f:JUCN7J_uZuP-ouQj
perl tools/test.pl verify 25400 hash in out && cat out
```

However I'm unable to get back any output from test.pl, and I'm not sure why.

Test.sh does work:
```
./tools/test.sh -m 25400 -t single -o win
[ test_1624993314 ] > Init test for hash type 25400.
[ test_1624993314 ] [ Type 25400, Attack 0, Mode single, Device-Type Gpu, Kernel-Type Optimized, Vector-Width 1 ] > OK : 0/8 not found, 0/8 not matched, 0/8 timeout
[ test_1624993314 ] [ Type 25400, Attack 0, Mode single, Device-Type Gpu, Kernel-Type Optimized, Vector-Width 4 ] > OK : 0/8 not found, 0/8 not matched, 0/8 timeout
```

**Comment by thatux** [comment] 2021-06-29 20:54
After adding some debug statements to test.pl I now understand what you mean

```
diff --git a/tools/test.pl b/tools/test.pl
index 380673d9e..ead6d8548 100755
--- a/tools/test.pl
+++ b/tools/test.pl
@@ -270,6 +270,9 @@ sub verify

     my ($hash, $word) = module_verify_hash ($line);

+    print("input\n".$line."\n");
+    print("output\n".$hash."\n");
+
     # possible if the hash:password pair does not match
     next unless defined $hash;
```

Again, for the attack it'd probably best to add an optional salt to the attack which would represent the user password.

However of the unit-test it'd make sense not to take the user-part into account, for m24500 and not to take the owner-part into account for m10500. How'd you think about that @philsmd?

If I can find the time I may try to do both starting with the latter.

I'm still interested where you got this from??:
```
user password ($u variable in `tools/test_modules/m25400.pm`) different:
37747ccd83e3fceccdc1c06de41a0904 for password hashcat
5f9d0e4f0b39835dace0d306c40cd6b7 for empty password (zero length)
```
That seems to be a useful script



Previously I've made these reference files

```
1.pdf:$pdf$4*4*128*-2368*1*16*b4064c3bfadb82499ff132659e328f83*32*c457dcff68f826d325168409941803e900000000000000000000000000000000*32*1f13ff0ecfd3a290a3da5ecd95d4ea30630d8c74c2c5d23dddfce0ae59866514
2.pdf:$pdf$4*4*128*-3392*1*16*9d7d71ded9a28046a3f1e6e2c3dc3496*32*329b921f92976311e72e46e4a7af28ca00000000000000000000000000000000*32*02111cd7c40df33e9d7b6e2d1e92d277df578772280e182c04d48abfd5b7caa9
3.pdf:$pdf$4*4*128*-3392*1*16*f9605e2e1cf343459896ed195965ece2*32*23425b3c6b9f2487a1bea970d8c1522100000000000000000000000000000000*32*4b77affc4f4f70415dd8b00a3122db623425a14f0bf5d06a62924d5011c96a05
```

This cracks them:
```
echo '$pdf$4*4*128*-2368*1*16*b4064c3bfadb82499ff132659e328f83*32*c457dcff68f826d325168409941803e900000000000000000000000000000000*32*1f13ff0ecfd3a290a3da5ecd95d4ea30630d8c74c2c5d23dddfce0ae59866514\n
$pdf$4*4*128*-3392*1*16*9d7d71ded9a28046a3f1e6e2c3dc3496*32*329b921f92976311e72e46e4a7af28ca00000000000000000000000000000000*32*02111cd7c40df33e9d7b6e2d1e92d277df578772280e182c04d48abfd5b7caa9\n
$pdf$4*4*128*-3392*1*16*f9605e2e1cf343459896ed195965ece2*32*23425b3c6b9f2487a1bea970d8c1522100000000000000000000000000000000*32*4b77affc4f4f70415dd8b00a3122db623425a14f0bf5d06a62924d5011c96a05' > m24500.hash
./hashcat.exe --potfile-disable -O -d1 -a3 -m25400 'm24500.hash' '?d'
```

**Comment by thatux** [comment] 2021-06-30 20:16
We cannot _not_ take the user part into account, as the owner-hash-part is based on the user password, hence we'd never be able to generate the correct owner-hash-part  without knowing the correct user pass.

Hence the only solution is to add the user password to the hash of the edit password, and take that into account when it's present, and when it's not present use the empty user (as we do now). As stated in more detail in https://github.com/hashcat/hashcat/pull/2739#issuecomment-817102701

**Comment by philsmd** [comment] 2021-07-01 06:19
sorry for the delay.

yeah, the input for the `verify` script (test.pl verify 25400) is exactly the same as the input / output of hashcat (you can also read this in the dev guide under docs/). hashcat outputs hashes always in the format `hash[:salt]:pass` (i.e. the hash is printed and the password is appended with a colon before it). this is the so-called `crack file` (`in` for verify).

> I'm still interested where you got this from??:

This is not a script or anything, I've just debugged/printed the `$u` variable here:
https://github.com/hashcat/hashcat/blob/2a5300a5d65143dcf8a9977e1e353b7073a9b3a2/tools/test_modules/m25400.pm#L199

(note: I've just noticed that github.com just shows an empty line here without the context, but just click on the link and you will see where I've inserted the code)

I've inserted this to debug it:
```perl
print unpack ("H*", $u) . "\n";
```

When I run this command:
```
perl tools/test.pl verify 25400 hash in out && cat out
```

with the `in` file's content of:
```
$pdf$2*3*128*-3904*1*16*631ed33746e50fba5caf56bcc39e09c6*32*5f9d0e4f0b39835dace0d306c40cd6b700000000000000000000000000000000*32*842103b0a0dc886db9223b94afe2d7cd63389079b61986a4fcf70095ad630c24:hashcat
```

I get `37747ccd83e3fceccdc1c06de41a0904` for `$u`

but if I run it with this `in` file:
```
$pdf$2*3*128*-3904*1*16*631ed33746e50fba5caf56bcc39e09c6*32*5f9d0e4f0b39835dace0d306c40cd6b700000000000000000000000000000000*32*842103b0a0dc886db9223b94afe2d7cd63389079b61986a4fcf70095ad630c24:
```

i.e. empty (zero length) password, I get `5f9d0e4f0b39835dace0d306c40cd6b7` for the `$u` variable (the important thing is that `5f9d0e4f0b39835dace0d306c40cd6b7` is the part within the input/original hash in the `hash` file, that would be checked against, while the `hash` file does not contain `37747ccd83e3fceccdc1c06de41a0904`)


I don't remember the whole details about user and owner password (but I remember investigating it back then when I was replying to some forum posts), but I only can say here that it's important that the `verify` script acts similar to hashcat, i.e. whenever `hashcat` marks a password as cracked, also `verify` should be able to do the same (except the correct password whenever the `crack`/`in` is correct... currently only `hashcat` cracks the hash, but `verify` doesn't mark the `crack`/`in` as correct. I think this is the real problem/bug).

I'm not sure if we need to add a salt.... we could just say that hashcat for now only supports the `user` part not set (or empty password)... but I'm not sure if this could lead to problems for the user. How does JTR (John The Ripper) solve this ? Does it try to crack both parts together ?

I think as a first step we should just make `verify` act similar to `hashcat` (every `crack` that hashcat output should be correctly verified by the `test.pl` script), later on we could discuss how to improve the `user` vs `owner` cracking. What do you think about this strategy. thanks

**Comment by thatux** [comment] 2021-07-12 22:54
Thanks! Sure hashcat cracks the hash, as for this attack it only takes the owner-hash-part into account in the attack, it doesn't even look at the user password. However m25400.pl did, as it tries to generate the user-hash-part again, based on the input., yet it is doesn't the user-password (it just reused the owner-password for that): https://github.com/hashcat/hashcat/blob/master/tools/test_modules/m25400.pm#L174

That should be fixed now.

I've looked a bit more in detail how to fix the actual attack and made a funny/interesting observation:  actually we don't really need the correct user-password, if we guess the correct owner-password, we're returned the correct user-password for free, as it's encrypted with RC4 and not hashed see: https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/pdf_reference_archives/PDFReference.pdf
algorithm 3.7 "the result of step 2 purports to be the user password". However we could supply the user-password such that we don't have to calculate it's $u value again from the decrypted $o value, but instead we can directly compare it.

If this'd work the way I think it does, this attack should be able to provide both the correct owner password as the correct user password for pdf files.


**Some notes:**
I'm not sure how JTR this does, I'm not sure whether it's even able to?
Here https://github.com/openwall/john/blob/bleeding-jumbo/src/pdf_fmt_plug.c#L389 the password to be cracked is input into the first md5, hence that'd be the user (opening the file) password, not the edit password.


This also seems interesting: https://web.archive.org/web/20140330174346/http://esec-lab.sogeti.com/post/The-undocumented-password-validation-algorithm-of-Adobe-Reader-X

**Closed as completed** 2021-09-11 18:56 UTC
Labels: bug
