### ISSUE TITLE
CL_OUT_OF_RESOURCES without X11

### ISSUE THREAD

**Issue by adrastee** [hashcat/hashcat#2356] opened 2020-04-08 09:56 UTC
Hi,
I have the error:

> Device #1: WARNING! Kernel exec timeout is not disabled.
> This may cause "CL_OUT_OF_RESOURCES" or related errors.
> To disable the timeout, see: https://hashcat.net/q/timeoutpatch
> https://hashcat.net/wiki/doku.php?id=timeout_patch

In this link:
> Linux: Add a line “Interactive” in /etc/X11/xorg.conf:

As X11 is not installed, /etc/X11/xorg.conf is not found.
Server is headless, I don't want to install X11.

Any solution?
Thanks.

**Comment by philsmd** [comment] 2020-04-19 04:24
good question . but I have no answer to that, because most hashcat users just use X11, because it normally doesn't reduce the speed that much etc.

I think that it could depend on the hardware you use (nvidia/amd) if this is even possible... but I do not think that even the driver vendors care a lot about headless systems and they kind of require to have X11 running for some settings.

Anyway, I think this is hardly a hashcat bug/problem... maybe we should close this issue and try to find the solution from the hardware vendor sites and post it on the hashcat forum (and if confirmed also on the wiki) ?

**Comment by jsteube** [comment] 2020-04-20 09:57
Yeah, it's not a hashcat issue at all. The Nvidia driver requires X11 to run in order to change this setting. Nothing we can do.

**Closed as completed by jsteube** 2020-04-20 09:57 UTC
