### ISSUE TITLE
Electrum salt type 5 support

### ISSUE THREAD

**Issue by LostPWHelp** [hashcat/hashcat#2047] opened 2019-05-29 00:23 UTC
I have been trying to recover my wallet for a long time. The issue is that it is electrum salt type 5 according to electrum2john. It would be amazing if this was added to hashcat at some point. Is there any intention to add it?

**Comment by philsmd** [comment] 2019-05-29 07:10
This seems to be a duplicate of https://github.com/hashcat/hashcat/issues/1806 ?!

**Closed as completed** 2019-06-05 07:02 UTC
