### ISSUE TITLE
Slowdown When Cracking NetNTLMv2

### ISSUE THREAD

**Issue by emwinkler** [hashcat/hashcat#1519] opened 2018-02-13 16:40 UTC
I noticed a severe slowdown when running crack against NetNTLMv2 hashes on 4.1.0 vs 3.6.0.  See below.  I am seeing the same issue with NTLM and LM hashes. 

./hashcat -m 5600 ../ntlmv2_amer.txt -a 3 -1 ?l?d?u ?1?1?1?1?1?1?1?1 -d 3

hashcat 4.1.0:
Session..........: hashcat
Status...........: Running
Hash.Type........: NetNTLMv2
Hash.Target......: ../ntlmv2_amer.txt
Time.Started.....: Tue Feb 13 11:26:27 2018 (28 secs)
**Time.Estimated...: Thu Mar 28 11:11:38 2019 (1 year, 42 days)**
Guess.Mask.......: ?1?1?1?1?1?1?1?1 [8]
Guess.Charset....: -1 ?l?d?u, -2 Undefined, -3 Undefined, -4 Undefined 
Guess.Queue......: 1/1 (100.00%)
**Speed.Dev.#3.....: 12389.2 kH/s (10.62ms) @ Accel:8 Loops:2 Thr:256 Vec:1**
Recovered........: 0/2 (0.00%) Digests, 0/2 (0.00%) Salts
Progress.........: 340770816/436680211169792 (0.00%)
Rejected.........: 0/340770816 (0.00%)
Restore.Point....: 0/916132832 (0.00%)
Candidates.#3....: Sorerane -> Bla4l434

hashcat 3.6.0:
Session..........: hashcat
Status...........: Running
Hash.Type........: NetNTLMv2
Hash.Target......: ../ntlmv2_amer.txt
Time.Started.....: Tue Feb 13 11:27:51 2018 (0 secs)
**Time.Estimated...: Sat Feb 24 21:08:27 2018 (11 days, 9 hours)**
Guess.Mask.......: ?1?1?1?1?1?1?1?1 [8]
Guess.Charset....: -1 ?l?d?u, -2 Undefined, -3 Undefined, -4 Undefined 
Guess.Queue......: 1/1 (100.00%)
**Speed.Dev.#3.....:   443.2 MH/s (9.27ms)**
Recovered........: 0/2 (0.00%) Digests, 0/2 (0.00%) Salts
Progress.........: 387053568/436680211169792 (0.00%)
Rejected.........: 0/387053568 (0.00%)
Restore.Point....: 0/56800235584 (0.00%)
Candidates.#3....: FUe00000 -> tV5kq000

**Comment by jsteube** [comment] 2018-02-13 16:41
Use -O and/or -w 3

**Comment by emwinkler** [comment] 2018-02-13 20:28
Using -O solved the problem.

**Comment by philsmd** [comment] 2018-02-14 06:44
Thanks for confirming that the problem was fixed.
Please do not forget to close the issue if the problem is fixed (since only you and the repository owner can do so).
Thx

**Closed as completed** 2018-02-14 10:40 UTC
