### ISSUE TITLE
Entropy for macOS (OSX) unexpectedly long: Token length exception

### ISSUE THREAD

**Issue by loren-osborn** [hashcat/hashcat#2346] opened 2020-03-29 23:21 UTC
The following existing ticket addressing this issue was previously closed "needs information / data": https://github.com/hashcat/hashcat/issues/1697

I'm trying to recover the admin password on a Mac OS X 10.13.6 (aka macOS High Sierra) that should have been set in a previous OS version. (The password was set by my late mother-in-law who passed 3 years ago. I'm trying to perform some routine maintenance, and forcibly changing the password would not be particularly convenient.)

In the embedded .plist file, the algorithm is annotated as: SALTED-SHA512-PBKDF2, but the data I'm getting in the entropy field is 1024 bits long. In previously related posts, there was conjecture that the 128 bytes might each be a hex digit, and therefore 4 bits each, but the data I'm seeing doesn't support that. (To help rule this out, I've only scrambled the salt and entropy in chunks of 32 bits.) Another poster suggested the 1024 bit value should be truncated to 512 bits. This solution neither sounds plausible, nor do I see any responses suggesting that this actually worked. 

I'm wondering:
* why am I seeing this double-length entropy value?
* does this have something to do with the password being set on an older version of macOS?
* Can I massage the hash that I have to work with some permutation of this entropy field?
* Can hashcat be updated to support this apparent edge case?

To ensure I haven't done some silly invalid hash transform, I automated the hash extraction for your review in this gist: https://gist.github.com/loren-osborn/220418e773d90faf405e87607bf4cafc (I am obviously not using the scrambled version to recover the password. Be aware that this is running on macOS, so some of the command line tool options are BSD-style, so different than on Linux... especially `sed`) A scrambled version of the hash this script gives me is as follows:

```
$ml$29498$17524cc1843e7c7d5b80f0e254edebca8bb3e4f68c55f09046d31fddaa01ce40$debf91315a02a3f0ae057874a1d03b39033efc1e983cf6984721aeff22bd912ab3432fe60a048ad7268c53b10623daae96af704d544b5bc7e2c922fbbe5028368625b8217b60537905a403871b7ebb41467e217eaf8c342cd42e34bfcec3b58337a40a034a44907f225e33626c8bff55f023903f49651af9213cedee56033254
```

**Comment by loren-osborn** [comment] 2020-03-30 01:16
I had a rather involved follow up half-written, before I was interrupted to do something else: cest la vie.

The gist of it was, that the computer in question shipped with Mac OS X 10.6 (Snow Leopard) and that a similar password hash can likely be generated by setting the password in Snow Leopard before upgrading to macOS 10.13 High Sierra. Of course this is simply a working theory.

**Comment by Banaanhangwagen** [comment] 2020-03-30 07:56
The token-length issue has been fixed recently, as mentioned here https://github.com/hashcat/hashcat/issues/1697 (fix: https://github.com/hashcat/hashcat/commit/a6cf7caf4a522dba39b7b8d9a144b86f7a0a5415)

In the examples that I have in my possession, the entropy in the user-plist has always a length of 0x80 (or 128 in dec) bytes. 
Some scripts extract those 128 bytes, some only 64 bytes. Hashcat was - till the fix - only compatible with 64 bytes length, because it could be cracked with this length.

Install the latest beta (https://hashcat.net/beta/), and Hashcat won't give you the token-length error any more.

**Comment by loren-osborn** [comment] 2020-03-30 14:25
Very good to hear. I will try this later today.

Do you expect that the hash-extraction script in the gist I provided will be of use to anyone? The XML parsing isn’t as robust as I’d prefer, but it seems much more so than any other examples I’ve seen. (And I think this helps make it a bit more readable.)

I’m not sure if `hashcat` has any collection of utility tools, but this script may be appropriate there.

**Comment by Banaanhangwagen** [comment] 2020-03-30 16:59
Consider writing a script which works on Linux and macOS

I use this one: https://github.com/JMagers/MacinHash/blob/master/machash.py

You may also look at [this one](https://gist.github.com/nueh/8252572).
JtR uses [this one](https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/run/mac2john.py) or [this one](https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/run/mac2john-alt.py). (some formatting needs to be done)

**Comment by loren-osborn** [comment] 2020-03-30 23:20
I'll see what I can do, but I'm currently using `plutil` to convert from Apple's proprietary binary plist format to their all text XML plist format, which is macOS/Darwin only (as far as I'm aware). I haven't seen any other tools that can perform this conversion. If I can find a cross-platform tool or library that does this conversion, the rest is quite trivial to port.

Otherwise, I don't have the bandwidth to port `plutil` at this time, assuming the source code is even available.

**Comment by Banaanhangwagen** [comment] 2020-03-31 14:46
`plistutil` does the conversion of plist to xml on Linux

**Comment by philsmd** [comment] 2020-04-19 04:49
Could you please close this issue @loren-osborn if the problem is fixed also for you (with latest beta) ?

I don't see any reason why we should keep this issue open.

I think hashcat just used the `dave` format when first trying to support this algo: https://github.com/octomagon/davegrohl#using-dave-with-hashcat (but maybe it's a chicken or egg problem and hashcat invented the format and dave adapted to that format... I don't think JTR had the same format that hashcat uses, at the time of implementing it... and jtr still uses a slightly different format as default format as far as I know.... normally we try to just use the same format between jtr <-> hashcat, just to not add any further obstacles and confusion... at least for any new hash format).

I think the dave tool could be a reference if you really want to see how to extract the hashes etc... but at the end all of these tools use some kind of plist parsing library or code.

**Comment by sadreck** [comment] 2020-06-16 15:50
I've just come across this issue with a 7100 hash and v5.1. ($ml$ hash)

Can confirm that upgrading to v6.0.0 has fixed the token length exception issue.

**Closed as completed** 2020-06-17 08:59 UTC
