### ISSUE TITLE
deleted/missing release git tags

### ISSUE THREAD

**Issue by anthraxx** [hashcat/hashcat#342] opened 2016-05-17 16:34 UTC
Hi, I'm a package maintainer and wanted to ask why the git tags were removed for the old versions?
Even when the goal is that your upstream website's tarballs should be picked instead, it would still be great if we can preserve the git tags in the git repository.

Can we please get back the v2.00 and v2.01 pointers?
cheers

**Comment by jsteube** [comment] 2016-05-17 18:17
The goal is to have the users download it from Github, not from the website. I just removed them because we're soon to release hashcat v3.00 (fusion of hashcat and oclHashcat)

**Comment by anthraxx** [comment] 2016-05-17 18:27
Ok thats cool, but then i especially recommend to never delete tags, they don't really hurt and depending on distributions they don't always ship the newest version. Removing tags breaks building those packages or reproducibly building old packages.

**Comment by jsteube** [comment] 2016-05-18 07:41
The reason for removing the tags is because we're using this in our Makefile:

```
git describe --tags --dirty=+
```

When I've added a new tag 3.00-beta it was there, but it still was using 2.01. We need a solution for that (maybe misuse?).

**Comment by anthraxx** [comment] 2016-05-18 08:45
Yeah we definitively need a solution that preserves all tags if you don't want to break any kind of user builds like arch AUR, gentoo etc etc :stuck_out_tongue: So I hope once we resolve this issue we could hopefully get back the old tags, plzzz :smile_cat: 

Well now I know the reason, what i'm using when I package GIT versions to have a meaningful string:

```
printf "%s.%s.%s" "$(git tag|sort|tail -n1)" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
```

this gets the semantically same output:

```
v0.15.7.786.1dd1f3d%
```

**Comment by jsteube** [comment] 2016-05-18 11:36
I think you don't understood what I mean. I have to remove old tags to make the process using git describe --tags for compilation. That's why it's propably a bad idea to use this kind of information for packaging.

**Comment by anthraxx** [comment] 2016-05-18 11:42
I guess you did not really understand what i mean :smile: 
removing tags is really a  bad habit, what i mean is that i offered an alternative approach to git describe that outputs you a usefull version string but uses the most current tag.
git tags should always be preserved, in my opinion its a failure on the code base if it requires to remove tags (really no offense, I try to find a solution that fits both sides)

Removing tags also removes the tarballs here: https://github.com/hashcat/oclHashcat/releases

I also understand what you mean, but doing it that way destroys the whole possibility building from source tarballs. Also if you jump back to a commit that is equivalent to 2.01 version, then this git describe command will still show you version 3.00. I remember there was a way to extract the current git tag version into a file for the release tarballs, I think radare is doing, let me search a bit around and i can show you what I mean

**Comment by jsteube** [comment] 2016-05-18 12:04
OK. Do you have any idea how to restore the deleted tags?

**Comment by anthraxx** [comment] 2016-05-18 12:14
That's great to hear... and please don't get me wrong, I really try to also solve your problem that you may face and I'm really not blaming or offending :smiley_cat: 
- restoring the old tags:
  
  git tag v2.00 5065474b4e5ed59add2d5af6e2e9cf3857969fe3
  git tag v2.01 490ff03fe18b3966ab591e859a79e29eab5ea386
  git push --tags

Can you help me trying to reproduce your problem why it still showed v2.01 for you? I have recreated the tags on a local checkout but i could not make git to output v2.01 for the current master HEAD when the v3.00-beta tag was in place :sob: 

I assume you want to avoid having a VERSION file in the root? It would of cause require to manually maintain that file, but that would solve some of the issues and the version in the Makefile could be a concat of that VERSION file + optionally (if its a git checkout and not a tarball extraction) a git describe without tags so the version will reflect also the git hash.

**Comment by anthraxx** [comment] 2016-05-18 12:26
Ok, I have found what i meant. Its called export-subst and allows to set a file via .gitattributes where a git version identifier is exported into a marker in the file. This allows to have a switch for non git checkouts (tarballs). If you like this solution, I could create a pull request for that. This would solve that 'git describe' is not available for tarballs.

**Comment by jsteube** [comment] 2016-05-18 16:17
I've restored the old tags as you described, that worked fine, thanks for that!

I then tried to reproduce the problem I had -- but I can't anymore. I'm sure it was like that it always showed the oldest tag. In this case that is 3.00-beta because from git's view it's the oldest at this moment. When I'm right, then that means when we'll move to 3.00 release it should still show 3.00-beta.

I'm not getting fully the other idea you had. What I'm basically looking for is that it uses the latest git tag plus the git describe hash (important for beta versions)

**Comment by anthraxx** [comment] 2016-05-18 16:27
normally git describe should traverse the history graph and pick the latest tag that is linked to the current HEAD when using describe, that's why I'm quite confused. You can try a test repository and play around with tagging and describe, I'm pretty sure it uses the nearest tag to a specific commit.

Ok, I think I get your idea, I will create a pull request with the switch I explained and you can have a look at it.
The idea is that it then supports both, 'git describe' (like now) if the current directory is a git checkout (contains .git directory) or as a fallback (if it is a github release tarball) it uses a static version identifier that will be inserted into the Makefile automagically by git-archive.

Really **big thanks** that you restored the old tags, I'm very thankful (and I'm sure a lot more people also).
Will link the pull request when I have time.... maybe in some hours or the following days.

**Comment by anthraxx** [comment] 2016-05-18 17:35
I have attached a pull-request with detailed explanation. This will allow to build from a release tarball again but will require that the tarball is either downloaded from github or created locally via 'git archive' command. However note that without such change the 'git describe' will fail in a non git-checkout.

If at any point your 'git describe' issues will reappear, feel free to ping me and I'm still willing to help solving that one for you.

**Comment by jsteube** [comment] 2016-05-19 07:16
Thanks for help. I think we can close this as the original issue with the deleted tags is close. Continue on PR

**Closed as completed by jsteube** 2016-05-19 07:16 UTC
