### ISSUE TITLE
Abort was called at 42 line in file

### ISSUE THREAD

**Issue by madonuko** [hashcat/hashcat#2584] opened 2020-10-17 09:47 UTC
```
$ hashcat "my_hash" -1 abcdefgh\?d \?1\?1\?1\?1 -a 3 -D 1
hashcat (v6.1.1) starting...

Abort was called at 42 line in file:
../neo/shared/source/built_ins/built_ins.cpp
[1]    14832 abort (core dumped)  hashcat "also_my_hash_stuff" -1 abcdefgh\?d \?1\?1\?1\?1 -a 3 -
```
GDB:
```
(gdb) file /usr/bin/hashcat
Reading symbols from /usr/bin/hashcat...
(No debugging symbols found in /usr/bin/hashcat)
(gdb) run --benchmark
Starting program: /usr/bin/hashcat --benchmark
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
hashcat (v6.1.1) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

[New Thread 0x7fffec141640 (LWP 18068)]
Abort was called at 42 line in file:
../neo/shared/source/built_ins/built_ins.cpp

Thread 1 "hashcat" received signal SIGABRT, Aborted.
0x00007ffff7c4b615 in raise () from /usr/lib/libc.so.6
```
same with `-d 1` and `-d 2`
intel cpu, opencl installed
```
$ yay -Qe | grep opencl
intel-opencl-runtime 1:20.26.17199-1
opencl-headers 2:2.2.20170516-3
```

**Comment by philsmd** [comment] 2020-10-20 15:46
hey,
from your first output it is quite obvious that this is not a hashcat problem, but an error in `NEO`.

Please install the drivers for the hardware that you have (and always mention the hardware, otherwise we really can't do anything).

The recommended drivers are mentioned at https://hashcat.net/hashcat (as you can see there is no `NEO` suggestion there).

We also try to have and answer user questions like this in the hashcat forum @ https://hashcat.net/forum/ . This is not a bug/problem in hashcat, but just a driver setup/configuration problem, without any details at all about your setup.

Please try to search and find answers in the hashcat forum for user questions like this. It's quite obvious that this is not some problem with hashcat from your output. You just didn't install the correct driver for your hardware.

One problem could be that you don't use a operating system that the driver vendors support (ubuntu uses `apt` for instance)... but there are some workarounds even for that situation, depending on the hardware and operating system you have.

Please do **not** forget to close this issue.

Thx

**Closed as completed** 2020-10-21 10:42 UTC

**Comment by jarp0l** [comment] 2021-01-05 14:46
I had the exact same problem as OP for months.
In my case the problem was caused by the package `intel-opencl-runtime`. But uninstalling that and installing another package `intel-compute-runtime`* solved it for me. 
However, I have to use the flag `--force` to suppress the warning:
`* Device #1: Unstable OpenCL driver detected!`

> * intel-compute-runtime: a.k.a. the Neo OpenCL runtime, the open-source implementation for Intel HD Graphics GPU on Gen8 (Broadwell) and beyond.

> See the arch wiki article: https://wiki.archlinux.org/index.php/GPGPU#OpenCL_Runtime

---

```bash
$ ls /etc/OpenCL/vendors

intel.icd
```

```bash
$ pacman -Qs opencl

local/clinfo 3.0.20.11.20-1
    Simple OpenCL application that enumerates all available platform and device properties
local/intel-compute-runtime 20.48.18558-1
    Intel(R) Graphics Compute Runtime for oneAPI Level Zero and OpenCL(TM) Driver
local/intel-graphics-compiler 1:1.0.5435-1
    Intel Graphics Compiler for OpenCL
local/intel-opencl-clang 11.0.0-1
    Wrapper library around clang that can compile OpenCL C kernels to SPIR-V modules
local/ocl-icd 2.2.13-1
    OpenCL ICD Bindings
local/opencl-headers 2:2020.06.16-1
    OpenCL (Open Computing Language) header files
```
