### ISSUE TITLE
windows hashcat using absolute paths reports errors `./OpenCL/: No such file or directory`

### ISSUE THREAD

**Issue by wgf4242** [hashcat/hashcat#4094] opened 2024-10-20 12:09 UTC
```
"D:\hashcat-6.2.6\hashcat.exe"  -m 1000 5bf4cb79033c48ce90a613a2c04aa6d3 -a 3 ?l?l?l?a?d?d?d?d --force

hashcat (v6.2.6) starting

You have enabled --force to bypass dangerous warnings and errors!
This can hide serious problems and should only be done when debugging.
Do not report hashcat issues encountered when using --force.

./OpenCL/: No such file or directory

Started: Sun Oct 20 20:08:44 2024
Stopped: Sun Oct 20 20:08:44 2024
```

**Comment by PenguinKeeper7** [comment] 2024-10-20 14:40
See https://github.com/hashcat/hashcat/issues/3365

**Comment by matrix** [comment] 2024-10-31 17:34
duplicate of #3365

**Closed as completed by matrix** 2024-10-31 17:34 UTC
Labels: bug
