### ISSUE TITLE
multibit classic (MD5 3 Iteration)

### ISSUE THREAD

**Issue by derlange2k** [hashcat/hashcat#2303] opened 2020-02-03 14:59 UTC
As already discussed in the forum, i would highly like to have support for multibit classic wallets. There are some formats out there for multibit, i'm talking about the MD5 hashed KDF variant of that wallet.

Encrypted wallet backup from multibit classic:

`U2FsdGVkX1/Gt5+4m/DQUaahjZ1bZvpbehbiJ8RlZgScHycsuhU6vxfLMpWR1LSHoTJma6igo6eG
CnMqbPYXw9drUjK3BZ2Qo1ZVvWD8pLcaIPM3rcTLAouZjurxZE32`

hash generated by multibit2john.py (from john):

`hashcat-20200128133332.key:$multibit$1*c6b79fb89bf0d051*a6a18d9d5b66fa5b7a16e227c46566049c1f272cba153abf17cb329591d4b487`

The wallet itself is encrypted with SCRYPT, but the key-backup files uses MD5 KDF. So I'm asking only for those wallet backups, and not for the original wallet file. multibit2john.py sets a 1 after $multibit$ to identify it was a key backup file, otherwise there would be a 3.

unencrypted wallet backup from multibit classic:

`KzWpNf4JJC8StHZE9nYtQZpXbhDyxWypxKBUaZMcBEJSZ2oYTiZd 2020-01-28T12:36:13Z`

the used password is "test".

Decrypting can be done with openssl:

`openssl enc -d -p -aes-256-cbc -a -in hashcat.key -md md5 -out hashcat-decrypt.key -pass pass:test`

Decrypted content with openssl:

`KzWpNf4JJC8StHZE9nYtQZpXbhDyxWypxKBUaZMcBEJSZ2oYTiZd 2020-01-21T21:58:35Z`

Link to the discussion on the forum:

[https://hashcat.net/forum/thread-8928.html](url)

**Comment by philsmd** [comment] 2020-02-04 08:36
We already have an open issue for this and also got a lot of duplicates already:
https://github.com/hashcat/hashcat/issues?q=is%3Aissue+multibit

The problem here is that some users just answer/post "I also need this" but they actually need a different algorithm (because there is the confusion of at least 3 very different versions/algorithms). The algorithms seem to be:
- $multibit$1* MD5 (.key)
- $multibit$2* scrypt HD (mbhd.wallet.aes)
- $multibit$3* scrypt Classic (.wallet)

Not only do we have the problem and (user) confusion of these 3+ algorithms (the users probably are not that technical and only know they have a "MultiBit Wallet"), but even just for the MD5 algorithm ($multibit$1*) we have 3 different implementations (MultiBit/MultiDoge, KnCGroup Bitcoin Wallet, bitcoinj) and a quite error-prone (collisions likely/possible ?!) verification step (as mentioned in the forum).

The algorithm itself would be quite easy to understand (POC below):

```
#!/usr/bin/env perl

# Author: philsmd
# Date: February 2020
# License: public domain (credits go to philsmd and hashcat)

use strict;
use warnings;

use Digest::MD5 qw (md5);
use Crypt::CBC;

#
# Constant:
#

my $BASE58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";

#
# Examples:
# (several from JTR's multibit_fmt_plug.c: https://github.com/magnumripper/JohnTheRipper/blob/60df51a2a318267ad1edf42e71da748ff81511f9/src/multibit_fmt_plug.c#L58-L74)
#

my ($pass, $salt, $encrypted_block);

# $multibit$1*c6b79fb89bf0d051*a6a18d9d5b66fa5b7a16e227c46566049c1f272cba153abf17cb329591d4b487:test
$pass = "test";
$salt = pack ("H*", "c6b79fb89bf0d051");
$encrypted_block = pack ("H*", "a6a18d9d5b66fa5b7a16e227c46566049c1f272cba153abf17cb329591d4b487");

# // MultiBit Classic 0.5.18
# $multibit$1*0908a1bd44147709*c82b6d0409c1e46a4660ea6d4fa9ae12e4e234c98a71a51ced105c7e66a57ca3:openwall
#$pass = "openwall";
#$salt = pack ("H*", "0908a1bd44147709");
#$encrypted_block = pack ("H*", "c82b6d0409c1e46a4660ea6d4fa9ae12e4e234c98a71a51ced105c7e66a57ca3");

# $multibit$1*2043ebb14b6d9670*24284a38a62b6a63fb0912ebc05aa9d26d6fd828134d20b9778d8d841f65f584:openwall123
#$pass = "openwall123";
#$salt = pack ("H*", "2043ebb14b6d9670");
#$encrypted_block = pack ("H*", "24284a38a62b6a63fb0912ebc05aa9d26d6fd828134d20b9778d8d841f65f584");

# // MultiBit Classic 0.5.19
# $multibit$1*39eac524fccaf7f2*c325ba3be05990e787904bc9d3603f035c3ed1bd673f87513765eefb5befda7e:openwall123
#$pass = "openwall123";
#$salt = pack ("H*", "39eac524fccaf7f2");
#$encrypted_block = pack ("H*", "c325ba3be05990e787904bc9d3603f035c3ed1bd673f87513765eefb5befda7e");

# $multibit$1*21ecedddebcb4ca8*8777067e8109e71ccdcda54817eed8615d8dea85f363829c0c78d61da9e1268e:\xe4b
#$pass = "\xe4b";
#$salt = pack ("H*", "21ecedddebcb4ca8");
#$encrypted_block = pack ("H*", "8777067e8109e71ccdcda54817eed8615d8dea85f363829c0c78d61da9e1268e");

my $pass_salt = $pass . $salt;

my $key1 = md5 (        $pass_salt);
my $key2 = md5 ($key1 . $pass_salt);
my $iv   = md5 ($key2 . $pass_salt);

my $aes_cbc = Crypt::CBC->new ({
  cipher      => "Crypt::Rijndael",
  iv          => $iv,
  key         => $key1 . $key2,
  keysize     => 32,
  literal_key => 1,
  header      => "none",
});

my $key = $aes_cbc->decrypt ($encrypted_block);

for (my $i = 0; $i < 32; $i++)
{
  my $c = substr ($key, $i, 1);
  my $idx = index ($BASE58, $c);

  if ($idx < 0)
  {
    print STDERR "ERROR: decryption failure. Wrong password ?\n";

    exit (1);
  }
}

print "password found: '$pass'\n";

exit (0);
```

note: this code does not check for the initial [LK|5|Q|\n|#] characters and also doesn't check for the KnCGroup Bitcoin Wallet or bitcoinj alternatives (this must be done otherwise we would risk to have false negatives :( ).

I think this is technically a duplicate of #1538. The OP in #1538 explicitly mentioned an example hash of $multibit$1* there:

```
$multibit$1*935f8d9b235bff03*e25936c998d095467b727db1028d9d6e4a6660bb8c48b4b6fb43ab8c348c45f2:WinSuxx
```

btw: the above forum link doesn't work, it should work like this: https://hashcat.net/forum/thread-8928.html

**Comment by brucebarnes** [comment] 2020-02-04 09:55
If we need to merge the issues, that seems reasonable.  I would also like to see the OpenSSL decryption method for the multibit .key file.  Need the GPU power to get some real chance at figuring out my unremembered password.

**Comment by jsteube** [comment] 2020-02-04 13:01
Duplicate of  #1538

**Closed as completed by jsteube** 2020-02-04 13:01 UTC
