### ISSUE TITLE
Strange performance drop with custom sha1 mode

### ISSUE THREAD

**Issue by einaros** [hashcat/hashcat#1458] opened 2017-11-22 10:47 UTC
While testing a new mode, `sha1(sha1($pass.$salt))`, with long salts, I've found that adding the salt to the dictionary entries doubles the performance .. and this strikes me as somewhat strange.

In other words, 
```
sha1_update_global_swap ("foobar")
```
..is twice as fast as..
```
sha1_update_global_swap ("foo");
sha1_update ("bar");
```

Any thoughts on how I have, in likely the most fundamental way, messed something up?

**Comment by jsteube** [comment] 2017-11-22 13:41
There's three difference cases:

1. If the total data size to hash is larger than the blocksize of the hash (64 for SHA1), then the performance drops that many times by 100% as much of the blocksize fits into the total data size, where the last blocksize is also decreased by 9. For example a total data size of 55 creates 100% performance drop compared to 54.

2. Each time you run sha1_update_* you create a branch caused by the switch() behind. GPU really do not like branches which creates a performance drop

3. GPU do not have support for 8bit processing, therefore you can not do sha1_update_global_swap ("foobar"), you must use a 32 bit datatype array with the size of the hash blocksize, so W[16]. If you use an array smaller than that, the JiT creates buffer overruns that are not intercepted but create performance drops.

All cases can add up to create an even larger drop which is hard to predict. Howerver, this looks like a normal behavior, therefore closing issue

**Closed as completed by jsteube** 2017-11-22 13:41 UTC

**Comment by einaros** [comment] 2017-11-22 13:53
1. Max length of $pass.$hash is >32, <64.

2. I did try writing a new sha1_update_ function, which takes both the global pass and salt, but the perf dropped just as much as with two calls.

3. That was pseudocode of sorts. Both pass and salt are u32[64].

Edit: Guessing the difference comes from there being two calls to update from within sha1_update_global_swap_blah mentioned in (2), as the dictionary approach will cause all data to be within a single u32[64].

**Comment by jsteube** [comment] 2017-11-23 08:28
> Max length of $pass.$hash is >32, <64.

Well that could be one (of multiple) reason, since 55 < 64

> I did try writing a new sha1_update_ function

It's already on the maximum of performance. The only way to improve performance is to workaround the call itself.

> Both pass and salt are u32[64]

If you have 64 bit value the performance will drop massively since GPU are still 32 bit construct. There are no native 64 bit integers and they are just emulated by 2 times 32 bit integers. Typically this results in two or three times the number of instructions than on 32 bit values.
