### ISSUE TITLE
Help with mask please 2 months no1 try to help

### ISSUE THREAD

**Issue by moko12123** [hashcat/hashcat#3512] opened 2022-11-18 16:52 UTC
I have all posible letters and numbers that is in password hash abctulmqp ABCTULMQP and the numbers from 1 to 36. I dont know where the letter is low letter or up. The password have 11 long characters, and use 6 letters and 5 number, 2 pairs of numbers that can be from 10 to 36, and 1 lonly its one from 1 to 9. I put
!hashcat - a 3 - m 11300 - 1 all letters and numbers "hash"? 1?1?1?1?1?1?1?1?1?1?1 but I have problems with numbers because letters yes checo all good, but numbers take all as 1 I mean 1234567891011 etc until 36. How I fix this to check each number and when star from 10 just check to 36. Hope some1 van help thank you.

**Comment by philsmd** [comment] 2022-11-19 10:56
I would advise to use hashcat mask files for this (hcmask, https://hashcat.net/wiki/?id=mask_attack#hashcat_mask_files).
Alternatively, giving that you use a **slow** algo like the -m 11300 you could also think of using an external fast password generator (but you need to code/script it yourself) and use it in stdin/pipe mode.

Always make sure to do the math and make sure it if feasible. At the end, as far as I can see, you are trying to crack a 11 character long password.

I think that questions like this should be asked in the hashcat forum or just use the forum search or hashcat wiki/faq. Will close this issue here, because it's just a general user doubt/question (not a bug report/issue/feature request etc). Thx

**Closed as completed by philsmd** 2022-11-19 10:56 UTC
