### ISSUE TITLE
bug in resume after permissions error on hash target file when using --remove

### ISSUE THREAD

**Issue by Shooter3k** [hashcat/hashcat#2704] opened 2021-02-05 14:00 UTC
Bug: restore point is not being saved correctly when --remove flag is used and permissions error is encountered on hash file

I believe these are the steps to reproduce this: 

step 1) Run hashcat in a long running (ex; something that is going to take a day) -a0 attack mode. Example: 

hashcat -m100 -w4 -a0 hashesleft.hash wordlist.txt -r rules.rule -o cracked.txt  --potfile-path potfile.pot --session=testsession --bitmap-max 24 -O --remove --debug-mode=4 --debug-file=matched.rule.txt --loopback 

step 2) next, place a file lock on hashesleft.hash. This can be done by running a second hashcat which is referencing the same hashesleft.hash or by another application that locks/blocks access to files

step 3) have step 1 get found results, so that it attempts to update the hashesleft.hash file (due to the --remove flag being used). Ie; it takes hashesleft.hash and creates hashesleft.hash.new and then attempts to rename that back to hashesleft.hash. 

step 4) hashcat should now throw a permissions error on hashesleft.hash. Note your restore point % (ie; 5%) from step 1's current progress.  error should read: Rename file 'hashesleft.hash' to 'hashesleft.hash.old': Permission denied

step 5) let your hashcat run from step 1 continue on a significant amount of time so that your restore point percent is notably past what it was on step 4. 

Step 6) Hit "c" in hashcat to create a checkpoint and wait for it to complete successfully. Note final checkpoint percentage (ie; 67%)

step 7) restore hashcat session ie: hashcat --restore --session testsession

step 8) note restore point percentage is not the 67% that was created in step 6 and instead is somewhere around the step 4's percentage.

**Comment by jsteube** [comment] 2021-06-03 20:24
I really have a hard time reproducing this. The problem is that the lock is only active while the file is written and that is typically a very short time. So a second hashcat process would lock the hashfile only if it write to it in remove mode. So I used flock to lock the hashfile shortly after the hashcat process with --remove was started, but before it was actually cracking something. But then the lock from flock on the hashfile was simply ignored, thus no permission denied error and thus no problem with the restore. What kind of filesystem are you using and what mount options are in place? Do you actually use hashcat to lock the hashfile in 2?

**Comment by Shooter3k** [comment] 2021-06-03 20:53
I'm running Windows 10 with multiple copies of hashcat (in multiple folders). This happens when I run two hashcats against the same hashfile at the same time. If I open the hashfile in ultraedit at the same time as the 2 hashcat's are running, it only makes it worse. 

Does that help?

**Comment by jsteube** [comment] 2021-06-04 07:24
I started to write an external script just to get the file locked on windows

```
$fileName = "d:\tools\hashcat-6.2.1\hash.txt"

$file = [System.io.File]::Open($fileName, 'Open', 'Read', 'None')

$null = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")

$file.Close()
```

I think I have a suspect for the problem, which is in src/monitor.c when remove feature takes action:

```
          const int rc = save_hash (hashcat_ctx);

          if (rc == -1) return -1;
```

So in case of error (permission denied) it returns the entire monitor thread. This thread is responsible for writing the remove hashfile, but also the restore file and some other stuff stuff like temperature monitoring. That means from the moment this error occurs it will not update the restore file anymore and whatever status it had at that time is frozen. That's all only theoretical thinking, but from what you describe it matches.

**Comment by jsteube** [comment] 2021-06-04 07:49
OK, this should be fixed with commit https://github.com/hashcat/hashcat/commit/918a621506249213eed7fe06af5dd097b69b2f66

Thanks for reporting!

**Closed as completed by jsteube** 2021-06-04 07:49 UTC
Labels: needs information / data
