### ISSUE TITLE
hashcat not removing hashes from hashfile with --remove

### ISSUE THREAD

**Issue by Xanadrel** [hashcat/hashcat#4] opened 2015-12-03 22:37 UTC
Hey guys,

Hashcat seems to be doing something a bit strange with the --remove functionality. We're implementing an AI that relies on removing cracks from the potfile each round, however, it seems that as the cracks become fewer and fewer that hashes are still removed from the hashfile but are not the correct ones. I think that this might be a threading issue. If we limit hashcat to a single thread, we don't have this problem.

This is set to low priority, don't worry, we've implemented a workaround for now but just thought we'd report it in case!

Great work as always,
tehnlulz

Migrated from: https://hashcat.net/trac/ticket/661

**Comment by philsmd** [comment] 2015-12-17 10:17
Is anybody able to reproduce this ?

Something very important missing from the trac ticket, is that the OP was instructed to use sort -u before he uses cpu hashcat with --remove and see if this problem still occurs. Unfortunately, there was no answer to that request (atom was trying to convince the OP that it could have to do with an unsorted input file).

The reason and details of that idea can also be found here: https://hashcat.net/wiki/frequently_asked_questions#when_i_use_--remove_with_hashcat_cpu_the_hash_sometimes_remains_even_if_it_was_cracked

or several times on the hashcat forum.

If that was (likely) the reason or we get no further description how to reproduce, I suggest that we close this issue for now.
Thx

(btw I was able to reproduce with non-unique hash file. But this is a known "limitation"  and I would not suggest that we implement a sorting & unique feature directly with this bug report, but if we see the need for it, we should at least open a new feature/enhancement request)

**Comment by philsmd** [comment] 2015-12-20 18:40
update: I contacted tehnlulz (OP) on IRC and he confirmed that the problem did not show up again when using sort -u before using hashcat with --remove option.
I would suggest that we close this bug and maybe consider to add a feature request (enhancement) with the goal to implement a sort & unique feature (that should trigger at least when --remove was enabled).
Thx

**Closed** 2015-12-20 20:19 UTC
Labels: bug
