### ISSUE TITLE
Logging clang options

### ISSUE THREAD

**Issue by FireCulex** [hashcat/hashcat#2330] opened 2020-03-16 08:33 UTC
Can't figure out how to disable it. Looks way worse in a terminal than in this post. Ubuntu 19.10 Hashcat 5.1.0

```
culex@Desktop:~$ hashcat -b --force | more
hashcat (v5.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: The pocl project
====================================
* Device #1: pthread-Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz, 4096/13834 MB allocatable, 4MCU

Benchmark relevant options:
===========================
* --force
* --optimized-kernel-enable

Hashmode: 0 - MD5

[Logging clang options] "/usr/bin/ld" "--eh-frame-hdr" "-m" "elf_x86_64" "-shared" "-o" "/home/culex/.cache/pocl/uncached/tempfile-3e-b3-3c-83-76.so" "-L/usr/lib/gcc/x86_64-linux-gnu/9" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib64" "-L/lib/x86_64-linux-gnu" "-L/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu" "-L/usr/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu/../../lib64" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../.." "-L/usr/lib/llvm-6.0/bin/../lib" "-L/lib" "-L/usr/lib" "/home/culex/.cache/pocl/uncached/tempfile-a7-f0-88-1d-68.so.o" "-lm" "-lm" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "-lc" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed"
[Logging clang options] "/usr/bin/ld" "--eh-frame-hdr" "-m" "elf_x86_64" "-shared" "-o" "/home/culex/.cache/pocl/uncached/tempfile-1a-00-a9-8b-6f.so" "-L/usr/lib/gcc/x86_64-linux-gnu/9" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib64" "-L/lib/x86_64-linux-gnu" "-L/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu" "-L/usr/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu/../../lib64" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../.." "-L/usr/lib/llvm-6.0/bin/../lib" "-L/lib" "-L/usr/lib" "/home/culex/.cache/pocl/uncached/tempfile-38-09-8a-f4-f9.so.o" "-lm" "-lm" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "-lc" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed"
[Logging clang options] "/usr/bin/ld" "--eh-frame-hdr" "-m" "elf_x86_64" "-shared" "-o" "/home/culex/.cache/pocl/uncached/tempfile-c7-bc-03-6f-76.so" "-L/usr/lib/gcc/x86_64-linux-gnu/9" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib64" "-L/lib/x86_64-linux-gnu" "-L/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu" "-L/usr/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu/../../lib64" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../.." "-L/usr/lib/llvm-6.0/bin/../lib" "-L/lib" "-L/usr/lib" "/home/culex/.cache/pocl/uncached/tempfile-49-df-d0-c5-43.so.o" "-lm" "-lm" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "-lc" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed"
[Logging clang options] "/usr/bin/ld" "--eh-frame-hdr" "-m" "elf_x86_64" "-shared" "-o" "/home/culex/.cache/pocl/uncached/tempfile-0a-1e-9e-e5-42.so" "-L/usr/lib/gcc/x86_64-linux-gnu/9" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib64" "-L/lib/x86_64-linux-gnu" "-L/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu" "-L/usr/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu/../../lib64" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../.." "-L/usr/lib/llvm-6.0/bin/../lib" "-L/lib" "-L/usr/lib" "/home/culex/.cache/pocl/uncached/tempfile-88-09-9a-21-68.so.o" "-lm" "-lm" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "-lc" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed"
[Logging clang options] "/usr/bin/ld" "--eh-frame-hdr" "-m" "elf_x86_64" "-shared" "-o" "/home/culex/.cache/pocl/uncached/tempfile-92-69-bf-3d-09.so" "-L/usr/lib/gcc/x86_64-linux-gnu/9" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib64" "-L/lib/x86_64-linux-gnu" "-L/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu" "-L/usr/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu/../../lib64" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../.." "-L/usr/lib/llvm-6.0/bin/../lib" "-L/lib" "-L/usr/lib" "/home/culex/.cache/pocl/uncached/tempfile-80-a3-ca-63-ad.so.o" "-lm" "-lm" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "-lc" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed"
Speed.#1.........:   249.4 MH/s (15.66ms) @ Accel:1024 Loops:1024 Thr:1 Vec:8

Hashmode: 100 - SHA1

[Logging clang options] "/usr/bin/ld" "--eh-frame-hdr" "-m" "elf_x86_64" "-shared" "-o" "/home/culex/.cache/pocl/uncached/tempfile-bf-85-91-00-b0.so" "-L/usr/lib/gcc/x86_64-linux-gnu/9" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib64" "-L/lib/x86_64-linux-gnu" "-L/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu" "-L/usr/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu/../../lib64" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../.." "-L/usr/lib/llvm-6.0/bin/../lib" "-L/lib" "-L/usr/lib" "/home/culex/.cache/pocl/uncached/tempfile-cc-1a-cf-53-99.so.o" "-lm" "-lm" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "-lc" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed"
[Logging clang options] "/usr/bin/ld" "--eh-frame-hdr" "-m" "elf_x86_64" "-shared" "-o" "/home/culex/.cache/pocl/uncached/tempfile-40-65-a2-40-5d.so" "-L/usr/lib/gcc/x86_64-linux-gnu/9" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib64" "-L/lib/x86_64-linux-gnu" "-L/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu" "-L/usr/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu/../../lib64" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../.." "-L/usr/lib/llvm-6.0/bin/../lib" "-L/lib" "-L/usr/lib" "/home/culex/.cache/pocl/uncached/tempfile-a9-a7-f8-ca-3a.so.o" "-lm" "-lm" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "-lc" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed"
[Logging clang options] "/usr/bin/ld" "--eh-frame-hdr" "-m" "elf_x86_64" "-shared" "-o" "/home/culex/.cache/pocl/uncached/tempfile-70-81-87-94-1c.so" "-L/usr/lib/gcc/x86_64-linux-gnu/9" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib64" "-L/lib/x86_64-linux-gnu" "-L/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu" "-L/usr/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu/../../lib64" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../.." "-L/usr/lib/llvm-6.0/bin/../lib" "-L/lib" "-L/usr/lib" "/home/culex/.cache/pocl/uncached/tempfile-91-c1-65-37-6e.so.o" "-lm" "-lm" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "-lc" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed"
[Logging clang options] "/usr/bin/ld" "--eh-frame-hdr" "-m" "elf_x86_64" "-shared" "-o" "/home/culex/.cache/pocl/uncached/tempfile-b0-e8-25-d5-c3.so" "-L/usr/lib/gcc/x86_64-linux-gnu/9" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib64" "-L/lib/x86_64-linux-gnu" "-L/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu" "-L/usr/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu/../../lib64" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../.." "-L/usr/lib/llvm-6.0/bin/../lib" "-L/lib" "-L/usr/lib" "/home/culex/.cache/pocl/uncached/tempfile-f5-c5-a7-8e-7d.so.o" "-lm" "-lm" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "-lc" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed"
[Logging clang options] "/usr/bin/ld" "--eh-frame-hdr" "-m" "elf_x86_64" "-shared" "-o" "/home/culex/.cache/pocl/uncached/tempfile-9f-96-54-dd-24.so" "-L/usr/lib/gcc/x86_64-linux-gnu/9" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib64" "-L/lib/x86_64-linux-gnu" "-L/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu" "-L/usr/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu/../../lib64" "-L/usr/lib/gcc/x86_64-linux-gnu/9/../../.." "-L/usr/lib/llvm-6.0/bin/../lib" "-L/lib" "-L/usr/lib" "/home/culex/.cache/pocl/uncached/tempfile-33-4b-4c-2d-04.so.o" "-lm" "-lm" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "-lc" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed"

```

**Comment by jsteube** [comment] 2020-03-17 09:08
Can you please try this and report back if something changed? I cannot reproduce locally.

```
$ export POCL_DEBUG=0
$ export POCL_DEBUG_LLVM_PASSES=0
```

**Comment by FireCulex** [comment] 2020-03-19 02:20
There was no effect. Both my 19.10 machines displayed this issue. Upgrading one of them to 20.04 made the messages disappear. Perhaps it isn't hashcat specific.

**Comment by jsteube** [comment] 2020-03-19 06:58
OK, thanks for the update. I'll close the issue then. Btw it was clear that this is not a hashcat issue, we just try to workaround any problems as good as possible. If there's an environment variable which lets us disable the llvm logging that wouldn't hurt us.

**Closed as completed by jsteube** 2020-03-19 06:58 UTC
