### ISSUE TITLE
Password from dictionary not matched with KeePass hash

### ISSUE THREAD

**Issue by MichalStaruch** [hashcat/hashcat#479] opened 2016-08-29 13:17 UTC
I've encountered a situation when hashcat didn't match password from dictionary with KeePass hash.

Steps to reproduce the problem:
1. Create new KeePass database, use "admin1" as password.
2. Use keepass2john (included in [John the Ripper](http://www.openwall.com/john/) jumbo package) to extract the hash, remove the leading ".*:" from it and save as test.hashes file.
3. Download [10k_most_common.txt](https://github.com/danielmiessler/SecLists/blob/master/Passwords/10k_most_common.txt) dictionary from SecLists. It includes "admin1" password.
4. Run `hashcat -m 13400 -a 3 test.hashes admin1` - results in 1/1 recovered. :+1:
5. Remove recovered hashes file (hashcat.pot).
6. Run `hashcat -m 13400 -a 0 test.hashes 10k_most_common.txt` - results in 0/1 recovered. :-1:

Content of the test.hashes file used in test:

```
$keepass$*2*6000*222*dd6d95d690fabcf88a664173f03d03b70af03d66274cdfb3d9af30d6e29fe7a6*df2e5700e0a87349ce83409457f1aa93711083e372ab815285e784d720b56379*23229838c8d9a788d90ff30e78117375*fec0fddc19892aca5623f8d807c409b88b6894dfa7d56d1dc2d7f51447880a59*3e012dea9a6b440729db5d14e0fabe9dde8668ce3e2ce68e4087853d0b0b2043
```

Problem observed in hashcat v3.10.

**Comment by Fist0urs** [comment] 2016-08-29 13:37
Hi,

I'll try to take a look this week-end. Could you give me some more information please: 
- is it using CPU, GPU or both
- what is your driver version
- have you tried with a password with another length/character class

Thank you

**Comment by MichalStaruch** [comment] 2016-08-29 14:18
Test was performed on i3-4150 platform, using built-in HD Graphics 4400 GPU. CPU was skipped.
Driver version displayed in Device Manager is 20.19.15.444, dated 2016-04-22.

When I've manually forced CPU by adding `--opencl-device-type 1` parameter it worked fine.

I've done one more test, just replacing "admin1" with "abc123" (also included in 10k_most_common.txt), and it worked fine using both attack modes.

Content of test2.hashes (made using "abc123" password):

```
$keepass$*2*6000*222*7501bd1b923c97da9ab30b1f0ef384103635f7185ff9d13ab2867681eb92b2ac*fdc43070eb472cbb176633fa0859cb58da9006b6e5f15134d8c4c138eafefc65*fc51008560d5d422e4b84305ba24e1b2*7dd6b8b6320ca34ee462840dcda81ac59240b046a9eaf7e488102e3b095e9fa5*8a622ef5ab03d2ff235ba314fc3080012d7ba6bc1047be5618aba21b9d55873c
```

So it seems problem can be observed only for some passwords, and only when using GPU (default device type picked by hashcat).

**Comment by Fist0urs** [comment] 2016-08-29 15:40
Actually I've experienced the same problems (password not cracked) using the exact same embeded GPU (issue #287 )

I'll try to look this week-end but I don't know if I can find something about if it is really optimization related :/

**Comment by MichalStaruch** [comment] 2016-08-29 17:37
On i5-6600K (driver 20.19.15.4463, dated 2016-05-25) with GTX 960 (driver 21.21.13.7254, dated 2016-08-11) and enforced NVIDIA platform (`--opencl-platforms 1`) both test.hashes and test2.hashes work fine in brute-force mode and fail in dictionary mode. I've got exactly the same results with enforced Intel platform and CPU mode (`--opencl-platforms 2 --opencl-device-type 1`).

Trying to use Intel platform and GPU mode results in crash when building kernel:

```
./hashcat64 --potfile-disable -m 13400 -a 0 test.hashes 10k_most_common.txt --opencl-platforms 2 --opencl-device-type 2
hashcat (v3.10) starting...

OpenCL Platform #1: NVIDIA Corporation, skipped

OpenCL Platform #2: Intel(R) Corporation
========================================
- Device #1: Intel(R) HD Graphics 530, 1624/6496 MB allocatable, 24MCU
- Device #2: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz, skipped

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1
Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
Watchdog: Temperature abort trigger disabled
Watchdog: Temperature retain trigger disabled

- Device #1: Kernel m13400.e0cdb833.kernel not found in cache! Building may take a while...
0x00007FFACE1F76E8 (0x0000000000000001 0x000000002A2C2DE0 0x0000000000000000 0x0000000000000001), freeBlock() + 0xCE178 bytes(s)
0x00007FFACE1F9173 (0x0000000000883C20 0x0000000000884060 0x000000002D362CC8 0x0000000000884060), freeBlock() + 0xCFC03 bytes(s)
0x00007FFACE1B748B (0x0000000000883C20 0x000000002D362CC8 0x000000002D362CC8 0x0000000000883C98), freeBlock() + 0x8DF1B bytes(s)
0x00007FFACE1B99FF (0x00007FFACE1C4D40 0x00007FFACE5D1388 0x0000000000883C20 0x000000002D362CC8), freeBlock() + 0x9048F bytes(s)
0x00007FFACE1BA208 (0x000000002D362CC8 0x000000002A4DB7C0 0x0000000028A28880 0x00000000311C0B01), freeBlock() + 0x90C98 bytes(s)
0x00007FFACE16946F (0x000000002903E440 0x000000002D362CC8 0x000000002903E440 0x0000000000884060), freeBlock() + 0x3FEFF bytes(s)
0x00007FFACE12C65B (0x00000000282C2330 0x00007FFACE4E5AE4 0x000000002903DA90 0x0000003100000030), freeBlock() + 0x30EB bytes(s)
0x00007FFACE0CF390 (0x000000002903DA80 0x000000002903DA90 0x0000000028670EC0 0x000000002903DA80), ?IsVectorInst@DX9@@YA_NW4_D3DSHADER_INSTRUCTION_OPCODE_TYPE@@@Z() + 0xE8250 bytes(s)
0x00007FFACE07873B (0x0000000027B3B601 0x0000000028670EC0 0x0000000029A58200 0x0000000000000124), ?IsVectorInst@DX9@@YA_NW4_D3DSHADER_INSTRUCTION_OPCODE_TYPE@@@Z() + 0x915FB bytes(s)
0x00007FFACE4594F6 (0x0000000028670EC0 0x0000000027B3B600 0x0000000028815501 0x0000000028815500), OpenCompiler12() + 0x237916 bytes(s)
0x00007FFACE45964F (0x0000000000000000 0x00000000284FEA01 0x0000000000000000 0x0000000028815500), OpenCompiler12() + 0x237A6F bytes(s)
0x00007FFACE4598BA (0x0000000000000005 0x0000000027B3B640 0x0000000000884BA0 0x00000000008844C0), OpenCompiler12() + 0x237CDA bytes(s)
0x00007FFACE458FD1 (0x0000000028A228E0 0x00000000008845A9 0x0000000000884568 0x0000000000884568), OpenCompiler12() + 0x2373F1 bytes(s)
0x00007FFACDFEE0EC (0x0000000027DEBA90 0x0000000029A58210 0x00000000266AAB10 0x0000000026688EE0), ?IsVectorInst@DX9@@YA_NW4_D3DSHADER_INSTRUCTION_OPCODE_TYPE@@@Z() + 0x6FAC bytes(s)
0x00007FFACDFF8014 (0x0000000027B2FEB8 0x00007FFACE5A194C 0x0000000000000004 0x0000000000884BA0), ?IsVectorInst@DX9@@YA_NW4_D3DSHADER_INSTRUCTION_OPCODE_TYPE@@@Z() + 0x10ED4 bytes(s)
0x00007FFACDF0BF84 (0x0000000000000001 0x0000000027617970 0x0000000027B0A520 0x0000000027B0A520)
0x00007FFACDF0AC2E (0x0000000000B034F0 0x00007FFA00080004 0x00000000264D6BC0 0x00007FFACF3921B1)
0x00007FFACF39EE17 (0x00000000264D6BC0 0x00000000008856C9 0x0000000000B1ED70 0x0000000000000000), clGetCLObjectInfoINTEL() + 0x27D77 bytes(s)
0x00007FFACF393541 (0x000000002342D950 0x00000000FFFFFFF5 0x0000000000000001 0x00000000264D6BC0), clGetCLObjectInfoINTEL() + 0x1C4A1 bytes(s)
0x00007FFACF3927FB (0x0000000000080001 0x0000000000B1C660 0x0000000000080000 0x00007FFACF337E00), clGetCLObjectInfoINTEL() + 0x1B75B bytes(s)
0x00007FFACF382C8A (0x0000000000B2AF40 0x0000000000885878 0x00000000FFFFFFD4 0x00000000264D66C0), clGetCLObjectInfoINTEL() + 0xBBEA bytes(s)
0x00007FFACF3286BC (0x0000000000B2AB00 0x000000002633C810 0x0000000000000000 0x00007FFA00000000)
0x00007FFACF370A78 (0x000000000C000000 0x0000000023BD1040 0x000000000048F540 0x0000000000003458), clBuildProgram() + 0xC8 bytes(s)
0x0000000000462C6A (0x000000000000000A 0x0000000000961400 0x0000000000690D18 0x0000000000000000)
0x00000000004013ED (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x000000000040152B (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFAFA268364 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFAFBCC5E91 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
```

It doesn't look like something specific to particular OpenCL driver.

**Comment by jsteube** [comment] 2016-08-29 17:43
If you use --opencl-platforms 1, so that it uses your NVIDIA device, and it cracks, then it's propably as @Fist0urs said, an OpenCL runtime problem. Not a hashcat problem.

**Comment by MichalStaruch** [comment] 2016-08-29 17:51
@jsteube: please read carefully. I've said those 2 test cases don't work in dictionary mode when using both NVIDIA GTX 960 GPU and Intel i5-6600K CPU.

**Comment by jsteube** [comment] 2016-08-29 17:54
@MichalStaruch You said so, but you posted a quote where you used --opencl-platforms 2. This makes it pretty hard to understand because it's confusing. Please post the output of --opencl-platforms 1 as well.

**Comment by MichalStaruch** [comment] 2016-08-29 18:08
@jsteube My bad. Logs with full results below:
[hashcat issue 479, brute-force mode.txt](https://github.com/hashcat/hashcat/files/443129/hashcat.issue.479.brute-force.mode.txt)
[hashcat issue 479, dictionary mode.txt](https://github.com/hashcat/hashcat/files/443130/hashcat.issue.479.dictionary.mode.txt)

**Comment by MichalStaruch** [comment] 2016-08-29 18:16
@jsteube My bad, logs with full results below:
[hashcat issue 479, brute-force mode.txt](https://github.com/hashcat/hashcat/files/443154/hashcat.issue.479.brute-force.mode.txt)
[hashcat issue 479, dictionary mode.txt](https://github.com/hashcat/hashcat/files/443156/hashcat.issue.479.dictionary.mode.txt)

**Comment by jsteube** [comment] 2016-08-29 18:20
I can not reproduce this, see here:

```
root@ht:~/hashcat# echo admin1 | ./hashcat -m 13400 x --potfile-disable                                               
hashcat (v3.10-10-g18d6a7a+) starting...

OpenCL Platform #1: NVIDIA Corporation  
======================================
- Device #1: GeForce GTX 750 Ti, 499/1998 MB allocatable, 5MCU

OpenCL Platform #2: The pocl project
====================================
- Device #2: pthread-AMD FX(tm)-8120 Eight-Core Processor, skipped

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1
Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger set to 75c

Starting attack in stdin mode...         

$keepass$*2*6000*222*dd6d95d690fabcf88a664173f03d03b70af03d66274cdfb3d9af30d6e29fe7a6*df2e5700e0a87349ce83409457f1aa93711083e372ab815285e784d720b56379*23229838c8d9a788d90ff30e78117375*fec0fddc19892aca5623f8d807c409b88b6894dfa7d56d1dc2d7f51447880a59*3e012dea9a6b440729db5d14e0fabe9dde8668ce3e2ce68e4087853d0b0b2043:admin1

Session.Name...: hashcat
Status.........: Cracked
Input.Mode.....: Pipe
Hash.Target....: $keepass$*2*6000*222*dd6d95d690fabcf88a66...
Hash.Type......: Keepass 1 (AES/Twofish) and Keepass 2 (AES)
Time.Started...: 0 secs
Speed.Dev.#1...:        0 H/s (1.18ms)
Recovered......: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.......: 1
Rejected.......: 0

Started: Mon Aug 29 20:17:52 2016
Stopped: Mon Aug 29 20:17:57 2016 
```

Also it's strange that it says this in your output:

```
Cache-hit dictionary stats 10k_most_common.txt: 1953599 bytes, 20342 words, 20342 keyspace
```

While in mine it says:

```
... 73017 bytes, 10000 words, 10000 keyspace   
```

So maybe "admin1" is just not in your wordlist?

**Comment by MichalStaruch** [comment] 2016-08-29 18:22
@jsteube I just re-check everything on i5-6600K and NVIDIA. Exactly as you've said, I've made a mistake when performing dictionary test on another PC, wrong file. It fully works using i5-6600K CPU and GTX 960 GPU.

**Comment by jsteube** [comment] 2016-08-29 18:24
Please close the issue if you think it's fixed.

**Comment by MichalStaruch** [comment] 2016-08-29 18:26
I will verify i3-4150 with latest Intel driver tomorrow. Original tests were performed using proper dictionary.

**Comment by MichalStaruch** [comment] 2016-08-30 07:18
Problem is still there: using Intel i3-4150 with latest stable driver (20.19.15.4463, dated 2016-05-25) dictionary mode using GPU launched against "admin1" hash fails.

Summary of tests in table below:

| Mode | "admin1" hash | "abc123" hash |
| --- | --- | --- |
| brute-force on CPU | OK | OK |
| brute-force on GPU | OK | OK |
| dictionary on CPU | OK | OK |
| dictionary on GPU | fail | OK |

Full logs from test:
[hashcat #479, i3-4150 driver 20.19.15.4463, brute-force mode.txt](https://github.com/hashcat/hashcat/files/444218/hashcat.479.i3-4150.driver.20.19.15.4463.brute-force.mode.txt)
[hashcat #479, i3-4150 driver 20.19.15.4463, dictionary mode.txt](https://github.com/hashcat/hashcat/files/444219/hashcat.479.i3-4150.driver.20.19.15.4463.dictionary.mode.txt)

**Comment by jsteube** [comment] 2016-08-30 10:33
OK, but now we're back on the following situation that @Fist0urs explained here: https://github.com/hashcat/hashcat/issues/479#issuecomment-243162405

This is a known error inside Intel's GPU OpenCL runtime, not a hashcat error. We can't do anything on it, that's why I'm closing this issue now.

Note that we also do intensive unit tests, including for keepass and no error have been reported with it.

**Closed as completed by jsteube** 2016-08-30 10:33 UTC

**Comment by MichalStaruch** [comment] 2016-08-30 12:35
@jsteube If you're 100% sure it's a runtime problem, then I guess it's in Intel hands, now. Could you please share a link to error report describing this particular problem on Intel side? Hashcat users affected by this issue could vote on it to help things moving.

**Comment by jsteube** [comment] 2016-08-30 12:38
Of course I am sure, otherwise I wouldn't close the issue. However, because the experience I made in the past, vendors don't care about bugs in OpenCL runtime, because it affects too less users. Whenever I report a full bug report, including poc etc, the vendors never reponse to this. Maybe it's because it's "hashcat", I don't know. However, I'm tired of reporting bugs to them, so there's no one. Feel free to open one yourself.
