### ISSUE TITLE
potfile is not written with hash mode 13721 (veracrypt)

### ISSUE THREAD

**Issue by ilyapashuk** [hashcat/hashcat#3093] opened 2021-12-30 09:08 UTC
bug description:

when I use 13721 mode to crack veracrypt volume, hashcat says that it is cracked, but potfile is not written.

--potfile-path option is ignored.

hashcat v 6.2.5, archlinux, NVIDIA GeForce GTX 1660 Ti, used with OpenCL

hear is a used veracrypt volume

https://drive.google.com/open?id=1O9EOR0qcIxd0ndgmjM99VQri9wB6nYzo

password is zxjpa

steps to reproduce:
run this command:
hashcat -m 13721 --potfile-path t.pot -a 3 tv.hc zx?lpa

expected behavior:
session should be cracked quickly, and password should be written to the potfile

actual behavior:
session is cracked, I sea "cracked" in the status line, but nothing is written to the potfile.

**Comment by matrix** [comment] 2021-12-31 12:11
duplicate of #2554

**Closed as completed by matrix** 2021-12-31 12:11 UTC
Labels: bug

**Comment by ilyapashuk** [comment] 2021-12-31 12:27
is it means that I can overcome this issue with "-o" option?
