### ISSUE TITLE
first byte silently used when multi-byte separator is requested

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#2893] opened 2021-07-22 03:25 UTC
**Current behavior**
Multi-bye separator arguments are silently accepted, truncating to the first byte.

**Expected behavior**
When a multi-byte separator is requested (probably accidentally), Instead of silently discarding the rest of the string, either throw an error, or use the entire string.

Discovered accidentally by a user. If someone tries to specify a different potfile:

```
./hashcat -m 99999 -a 3 a a --potfile-disable -o output.txt --quiet; cat output.txt
a:a
```
... but accidentally leaves off the second dash in `--potfile-disable`, the `-p` (specifying an alternate separator) will silently use the next specified byte (o), and discard the rest:

```
./hashcat -m 99999 -a 3 a a -potfile-disable -o output.txt --quiet; cat output.txt
aoa
```

**Comment by Chick3nman** [comment] 2021-07-22 10:47
I can reproduce, this looks like its due to a bit of a naive parse for that option/arg. 

Relevant line:
https://github.com/hashcat/hashcat/blob/master/src/user_options.c#L485

We should be handling this like we are with other user options, setting a changed bool and then verifying that the input is only 1 byte if it has been changed by the user.

**Comment by jsteube** [comment] 2021-07-22 16:55
Fixed with commit https://github.com/hashcat/hashcat/commit/f9e74045b5284b1317fa01271138cd10ce853516

**Closed as completed by jsteube** 2021-07-22 16:55 UTC
Labels: bug
