### ISSUE TITLE
[DNSSEC/NSEC3] Wrong hash for guesses containing '.' (dot)

### ISSUE THREAD

**Issue by y8ttsbftabfvty9g** [hashcat/hashcat#2365] opened 2020-04-18 11:18 UTC
# Issue

Hash 8300 (DNSSEC/NSEC3) does not properly handle guesses with a '.' (dot) inside.

# How to reproduce

Here is a reproducer (`in.hashcat`):
```
gkcc80t1o5u65na4dm6u7av84udgqfel:.example.com:0011223344556677:1
737js3b9qp7uiq3sm3d3lk30ce6gdujq:.example.com:0011223344556677:1
```

Spoiler: `gkcc80t1o5u65na4dm6u7av84udgqfel` is `aa` (control) and `737js3b9qp7uiq3sm3d3lk30ce6gdujq` is `a.a` (buggy one).

And a small dictionary (`mylist.dict`):
```
a
aa
a.a
```

I try to crack it with `hashcat --potfile-disable --force -O -w 4 -m 8300 in.hashcat -a 0 mylist.dict`

Hashcat only finds `aa` (`aa.example.com`), and *not* `a.a` (`a.a.example.com`).

However, if I add the following line to the input list (notice the extra `.a`):
`737js3b9qp7uiq3sm3d3lk30ce6gdujq:.a.example.com:0011223344556677:1`
then hashcat successfully find `a` (`a.a.example.com`).

# Why it happens

Dots need a special treatment. This is done properly for the 'domain' part (here `example.com` or `a.example.com`), as seen in https://github.com/hashcat/hashcat/blob/f96594ef878b367cfa0ef7098ed24f362757528f/src/modules/module_08300.c#L115-L127 . This treatment is however not done on the guess in the OpenCL code.

For reference, JohnTheRipper handles this correctly
```
$NSEC3$1$0011223344556677$8518c403a1c17c62dd446d8de3abe8279b0d3dd5$example.com.
$NSEC3$1$0011223344556677$38cf3e0d69d64fe9687cb0da3ad060638d06fa7a$example.com.
john --wordlist=mylist.dict in.john
```

# Next steps?

I am seeing this issue in the wild, and I would love to be able to use my GPU instead of my CPU here.

To be honest, I have never written any OpenCL code, so I am not sure I can help fix the issue.
Is anyone willing to fix this?

Thanks!

**Comment by philsmd** [comment] 2020-04-22 10:24
as far as I understand, you are saying that we need to also replace each and every dot (".") within the password with the length of the following part ("\x01a" instead of ".a", for instance)

... while currently we only do this for the fixed/static (non-password-involving) domain part ? 

I guess your assumption (if I understood this correctly) is correct and we would need to do this within the OpenCL/CUDA kernel, because it involves the password.

I think it wouldn't be impossible to do this, but could make the cracking a little bit slower :(

I just tested with our perl code from the test framework under tools/test_modules/... and indeed the a.a.example.com seems to work only with the first dots also replaced with the dots replaced with the "length".

This is indeed an annoying search-and-replace algorithm and if true (are there any specs ?) we would need to add this replace after the password is constructed. Fortunately, the length of the password shouldn't change because a dot could easily be replaced by the length with just one byte change (0x01-0xff !?)

**Comment by hops** [comment] 2020-04-22 12:30
@y8ttsbftabfvty9g Can you give an example where you found this in the wild?
I'm asking because if you walk the `example.com` zone you should only get NSEC3 hashes of this zone. Meaning you will only get `gkcc80t1o5u65na4dm6u7av84udgqfel` or `aa.example.com`.
`737js3b9qp7uiq3sm3d3lk30ce6gdujq` or `a.a.example.com` is in the zone `a.example.com` and have to be walked separately.

I just tested to add `a.a.example.com` in the `example.com` in a Knot DNS test environment. It does give the warning `ignoring out-of-zone data, owner a.a.example.com.` and it doesn't end up in the zone file.

**Comment by philsmd** [comment] 2020-05-04 08:37
@y8ttsbftabfvty9g we need an answer from you. for now, as @hops mentioned, it really seems that you are doing something wrong and the password vs domain/salt part is just not used correctly (dots in the domain part of an URLs always delimit root, domains and subdomains... so it doesn't seem like a password with dots is a valid password).

Please answer soon, otherwise we might need to close this issue as invalid

**Comment by exander77** [comment] 2020-05-16 12:11
I can confirm that this does not work.

@hops Your comment is incorrect. The zone contains what it contains, basically anything:
```
example.com.
www.example.com.
subdomain.example.com.
www.subdomain.example.com.
```
Are in 99.9% part of the same zone example.com., you have some misunderstanding on how zones work. Everything is part of the zone parent zone unless it is delegated to some child zone.

**Comment by exander77** [comment] 2020-05-16 12:17
@philsmd He didn't answer, but I reproduce it as well and explanation is above.

I wild it is on almost every single zone. All of my personal zones are affected. In minimum every single zone with  `www.subdomain.` and `subdomain.` is affected.

**Comment by philsmd** [comment] 2020-05-16 12:57
A quick fix could be to do something like this:
```
diff --git a/OpenCL/m08300_a0-pure.cl b/OpenCL/m08300_a0-pure.cl
index 7bf1156f..1d6474cf 100644
--- a/OpenCL/m08300_a0-pure.cl
+++ b/OpenCL/m08300_a0-pure.cl
@@ -63,11 +63,33 @@ KERNEL_FQ void m08300_mxx (KERN_ATTR_RULES ())
 
     tmp.pw_len = apply_rules (rules_buf[il_pos].cmds, tmp.i, tmp.pw_len);
 
+    // replace . with the length:
+
+    u32 len = 0;
+
+    for (int pos = tmp.pw_len - 1; pos >= 0; pos--)
+    {
+      const u32 div = pos  / 4;
+      const u32 mod = pos  % 4;
+      const u32 sht = mod << 3;
+
+      if (((tmp.i[div] >> sht) & 0xff) == 0x2e) // '.'
+      {
+        tmp.i[div] += (len - 0x2e) << sht;
+
+        len = 0;
+
+        continue;
+      }
+
+      len++;
+    }
+
     sha1_ctx_t ctx1;
 
     sha1_init (&ctx1);
 
-    ctx1.w0[0] = (tmp.pw_len & 0xff) << 24;
+    ctx1.w0[0] = (len & 0xff) << 24;
 
     ctx1.len = 1;
 
@@ -182,11 +204,33 @@ KERNEL_FQ void m08300_sxx (KERN_ATTR_RULES ())
 
     tmp.pw_len = apply_rules (rules_buf[il_pos].cmds, tmp.i, tmp.pw_len);
 
+    // replace . with the length:
+
+    u32 len = 0;
+
+    for (int pos = tmp.pw_len - 1; pos >= 0; pos--)
+    {
+      const u32 div = pos  / 4;
+      const u32 mod = pos  % 4;
+      const u32 sht = mod << 3;
+
+      if (((tmp.i[div] >> sht) & 0xff) == 0x2e) // '.'
+      {
+        tmp.i[div] += (len - 0x2e) << sht;
+
+        len = 0;
+
+        continue;
+      }
+
+      len++;
+    }
+
     sha1_ctx_t ctx1;
 
     sha1_init (&ctx1);
 
-    ctx1.w0[0] = (tmp.pw_len & 0xff) << 24;
+    ctx1.w0[0] = (len & 0xff) << 24;
 
     ctx1.len = 1;
 
```

This is only for the pure -a 0 kernel.... the other files need to be changed accordingly.

of course it would be better to avoid this additional code, but if it is needed, we problably need to add it.

What do you think about these changes ?
do they work for you ? (just test with removing the kernel file kernels/ (rm -r kernels/) and applying the patch (git apply a.diff)).

Thanks for the update/confirmation... we really need users that help us with these specs etc... we can't really know everything and investigate every little detail... so this is very good/appreciated input. thx

**Comment by hops** [comment] 2020-05-16 12:59
@exander77 Thank you for the thorough explanation! I made the wrong assumption that you have to delegate all zones. Sorry about that.

**Comment by exander77** [comment] 2020-05-16 13:47
@hops Not a problem. DNS surprises me every day.

Your patch seems to improve the results significantly!
```
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:      767 H/s (0.18ms) @ Accel:1024 Loops:1 Thr:1 Vec:8
Recovered........: 66/67 (98.51%) Digests, 0/1 (0.00%) Salts
Progress.........: 67/67 (100.00%)
Rejected.........: 0/67 (0.00%)
Restore.Point....: 67/67 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
```
But I am still missing a single record. I have a feeling it is the empty string. Is it possible you throw out empty string from the dictionary?

**Comment by exander77** [comment] 2020-05-16 20:58
Also, have found a minor unrelated bug, if salt is not used, having `::` in input leads to error and I need to set it as `:0:`, but the hashcat actually produces `::` in the output. So its output is actually not compatible with its input.

**Comment by philsmd** [comment] 2020-05-18 08:31
can you provide some example hashes with password such that we can reproduce this? I'm also not sure if this is a related problem or off-topic... but I guess it's close enough to discuss this here too (but we should at least be very clear that the "dot-replace-issue" could probably be fixed with the above fix applied to each and every dnssec kernel file).

For the first problem with the `example.com` zone "itself", it's a little bit difficult for me to understand how the hashes would look like (with dots included ?) and how to distinguish this with a hash that only contains `.com`  in the hash:
```
perl -MNet::DNS::RR::NSEC3 -MNet::DNS::SEC -e 'print Net::DNS::RR::NSEC3::name2hash (1, ".example.com", 1, "ab1413cf")'
empty domain label at /usr/local/share/perl/5.28.1/Net/DNS/RR/NSEC3.pm line 287.
```

for this command for instance I get an error, so this is probably not a valid input, not even for the DNSSEC perl module.

Instead like this
```
perl -MNet::DNS::RR::NSEC3 -MNet::DNS::SEC -e 'print Net::DNS::RR::NSEC3::name2hash (1, "example.com", 1, "ab1413cf")'
```
it works, but here of course the module things that `example` is the "password"/word and only `.com` is the domain part. So how do you say it's an empty zone ? I think the problem is only that the hash only can contain `.com` and the password candidate list must contain `example`, right ? so your hashes are not correct.. otherwise I can't come up with any means how to separate a empty zone from a zone where the first part is the password (if there is really only a dot in between) !

For the second problem with the empty salt, I also can't reproduce it. Have a look at the example hashes on https://hashcat.net/wiki/example_hashes
The format is like this:
```
$digest:$domain:$salt_in_hex:$iterations
```

of course the iterations must be 0 or greater, the salt can be empty... I just tested it (if it doesn't work for you maybe the beta version already fixed a problem: https://hashcat.net/beta/ ) ?

Would be great if you give some example and explain the problems in detail... I didn't find any major problem in hashcat here, but maybe I'm wrong. Thx again

**Comment by exander77** [comment] 2020-05-18 09:36
Currently, I am on v5.1.0, official Ubuntu 20.04 version. I can open another issue if needed.

It may be related to dot or may not.

This is from my personal zone, I am able to resolve all hashes, but this one:
```
kbjciv07olhj0aqkv3fvdr1rm3u6gqal:.shy.cz:67f147cfdd3825b3:10
```
When I compare results with the contents of my zone, everything seems to be there, any possibility I see is the domain itself.

I am able to reproduce this hash by the command you supplied:
```
$  perl -MNet::DNS::RR::NSEC3 -e 'print Net::DNS::RR::NSEC3::name2hash (1, "shy.cz", 10, "67f147cfdd3825b3")'
```
```
kbjciv07olhj0aqkv3fvdr1rm3u6gqal
```

Meaning `shy.cz` is part of the `shy.cz` zone.

The other problem:

Fails for input:
```
h14liptvm5blkpbh9ficselop01agilb:.protonmail.com::0
```
I need to input:
```
h14liptvm5blkpbh9ficselop01agilb:.protonmail.com:::0
```
But the output is:
```
h14liptvm5blkpbh9ficselop01agilb:.protonmail.com::0:www
```

**Comment by exander77** [comment] 2020-05-18 09:48
This is the output when I try to use an empty dictionary:

```
Session..........: hashcat                       
Status...........: Exhausted
Hash.Type........: DNSSEC (NSEC3)
Hash.Target......: kbjciv07olhj0aqkv3fvdr1rm3u6gqal:.shy.cz:67f147cfdd...5b3:10
Time.Started.....: Mon May 18 11:47:02 2020 (0 secs)
Time.Estimated...: Mon May 18 11:47:02 2020 (0 secs)
Guess.Base.......: File (empty.dict)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:       17 H/s (0.04ms) @ Accel:1024 Loops:1 Thr:1 Vec:8
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 1/1 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidates.#1....:  -> 
```

I actually detects a line as 1 item but fails somewhere.

**Comment by exander77** [comment] 2020-05-18 10:01
Out of the topic question, what do you guys think of NSEC5?
http://www.cs.bu.edu/~goldbe/papers/nsec5faq.html

**Comment by philsmd** [comment] 2020-05-18 17:02
yeah, that's exactly what I was wondering i.e. what is the difference between `kbjciv07olhj0aqkv3fvdr1rm3u6gqal:.shy.cz:67f147cfdd3825b3:10:` and empty password and `kbjciv07olhj0aqkv3fvdr1rm3u6gqal:.cz:67f147cfdd3825b3:10:` and password `shy` . There is basically no way to differentiate an empty zone from a `shy` zone.

Therefore I was asking why not just use a different hash with a domain "one layer above" ? I guess it's just user convenience / experience.

If we need to support this empty password feature, we would probably need to add again further code to check for the password length (otherwise there are 2 lengths next to each other - zero pass length and subdomain length - which is wrong according to your examples).

I have some working code for -a 0 pure (not yet changed for optimized -O kernels or other attack types different from dictionary attack), but we really need to see if the speed drop isn't too much and it's really needed:
```
diff --git a/OpenCL/m08300_a0-pure.cl b/OpenCL/m08300_a0-pure.cl
index 7bf1156f..0c8b5933 100644
--- a/OpenCL/m08300_a0-pure.cl
+++ b/OpenCL/m08300_a0-pure.cl
@@ -67,11 +67,36 @@ KERNEL_FQ void m08300_mxx (KERN_ATTR_RULES ())
 
     sha1_init (&ctx1);
 
-    ctx1.w0[0] = (tmp.pw_len & 0xff) << 24;
+    // replace . with the length:
 
-    ctx1.len = 1;
+    if (tmp.pw_len > 0)
+    {
+      u32 len = 0;
+
+      for (int pos = tmp.pw_len - 1; pos >= 0; pos--)
+      {
+        const u32 div = pos  / 4;
+        const u32 mod = pos  % 4;
+        const u32 sht = mod << 3;
+
+        if (((tmp.i[div] >> sht) & 0xff) == 0x2e) // '.'
+        {
+          tmp.i[div] += (len - 0x2e) << sht;
+
+          len = 0;
+
+          continue;
+        }
 
-    sha1_update_swap (&ctx1, tmp.i, tmp.pw_len);
+        len++;
+      }
+
+      ctx1.w0[0] = (len & 0xff) << 24;
+
+      ctx1.len = 1;
+
+      sha1_update_swap (&ctx1, tmp.i, tmp.pw_len);
+    }
 
     sha1_update (&ctx1, s_pc, salt_len_pc + 1);
 
@@ -186,11 +211,36 @@ KERNEL_FQ void m08300_sxx (KERN_ATTR_RULES ())
 
     sha1_init (&ctx1);
 
-    ctx1.w0[0] = (tmp.pw_len & 0xff) << 24;
+    // replace . with the length:
 
-    ctx1.len = 1;
+    if (tmp.pw_len > 0)
+    {
+      u32 len = 0;
+
+      for (int pos = tmp.pw_len - 1; pos >= 0; pos--)
+      {
+        const u32 div = pos  / 4;
+        const u32 mod = pos  % 4;
+        const u32 sht = mod << 3;
+
+        if (((tmp.i[div] >> sht) & 0xff) == 0x2e) // '.'
+        {
+          tmp.i[div] += (len - 0x2e) << sht;
+
+          len = 0;
+
+          continue;
+        }
 
-    sha1_update_swap (&ctx1, tmp.i, tmp.pw_len);
+        len++;
+      }
+
+      ctx1.w0[0] = (len & 0xff) << 24;
+
+      ctx1.len = 1;
+
+      sha1_update_swap (&ctx1, tmp.i, tmp.pw_len);
+    }
 
     sha1_update (&ctx1, s_pc, salt_len_pc + 1);
 
``` 

The other problem should already be fixed since several months with the beta version (https://hashcat.net/beta), see: https://github.com/hashcat/hashcat/commit/e724e0dadc3ebda7c7864543519328875d8ab927

Thx

**Comment by exander77** [comment] 2020-05-18 19:16
> yeah, that's exactly what I was wondering i.e. what is the difference between kbjciv07olhj0aqkv3fvdr1rm3u6gqal:.shy.cz:67f147cfdd3825b3:10: and empty password and kbjciv07olhj0aqkv3fvdr1rm3u6gqal:.cz:67f147cfdd3825b3:10: and password shy . There is basically no way to differentiate an empty zone from a shy zone.

It is not only that... The problem is, how would you know? All of these hashes were found in `shy.cz.` zone and they belong to a `shy.cz.` zone. It would mean to run all of the hashes with `cz.` zone which seems like an extreme waste if it can be handled correctly.  It also confuses the issue greatly.

You are absolutely correct that `` in `shy.cz.` zone is the same thing as `shy` in `cz.` or even `shy.cz` in `.` Because it is the same thing for the client. A client does not care if the zone was delegated or not. And hashes for the specific FQDN has to be the same.

I suggest checking empty string outside the GPU code if it is a performance issue.

All of these should work:
```
kbjciv07olhj0aqkv3fvdr1rm3u6gqal:.shy.cz:67f147cfdd3825b3:10:
kbjciv07olhj0aqkv3fvdr1rm3u6gqal:.cz:67f147cfdd3825b3:10:
kbjciv07olhj0aqkv3fvdr1rm3u6gqal::67f147cfdd3825b3:10:
```

**Comment by exander77** [comment] 2020-05-18 19:47
From your point of view, you can think that `.` is actually a part of the generated password:
empty string with static salt `shy.cz.` as suffix
`shy.` with static salt `cz.` as suffix
`cz.` with static salt empty as suffix

Is this helpful?

**Comment by philsmd** [comment] 2020-05-20 08:27
when you say `Currently first one failes, others work.` do you refer to the patch above ? this is very confusing to me.

It would make sense to be very clear which version you are talking about and also mention what is fixed with the below fix/patch (dnssec_fix.diff):
```
diff --git a/OpenCL/m08300_a0-pure.cl b/OpenCL/m08300_a0-pure.cl
index 7bf1156f..0c8b5933 100644
--- a/OpenCL/m08300_a0-pure.cl
+++ b/OpenCL/m08300_a0-pure.cl
@@ -67,11 +67,36 @@ KERNEL_FQ void m08300_mxx (KERN_ATTR_RULES ())
 
     sha1_init (&ctx1);
 
-    ctx1.w0[0] = (tmp.pw_len & 0xff) << 24;
+    // replace . with the length:
 
-    ctx1.len = 1;
+    if (tmp.pw_len > 0)
+    {
+      u32 len = 0;
+
+      for (int pos = tmp.pw_len - 1; pos >= 0; pos--)
+      {
+        const u32 div = pos  / 4;
+        const u32 mod = pos  % 4;
+        const u32 sht = mod << 3;
+
+        if (((tmp.i[div] >> sht) & 0xff) == 0x2e) // '.'
+        {
+          tmp.i[div] += (len - 0x2e) << sht;
+
+          len = 0;
+
+          continue;
+        }
 
-    sha1_update_swap (&ctx1, tmp.i, tmp.pw_len);
+        len++;
+      }
+
+      ctx1.w0[0] = (len & 0xff) << 24;
+
+      ctx1.len = 1;
+
+      sha1_update_swap (&ctx1, tmp.i, tmp.pw_len);
+    }
 
     sha1_update (&ctx1, s_pc, salt_len_pc + 1);
 
@@ -186,11 +211,36 @@ KERNEL_FQ void m08300_sxx (KERN_ATTR_RULES ())
 
     sha1_init (&ctx1);
 
-    ctx1.w0[0] = (tmp.pw_len & 0xff) << 24;
+    // replace . with the length:
 
-    ctx1.len = 1;
+    if (tmp.pw_len > 0)
+    {
+      u32 len = 0;
+
+      for (int pos = tmp.pw_len - 1; pos >= 0; pos--)
+      {
+        const u32 div = pos  / 4;
+        const u32 mod = pos  % 4;
+        const u32 sht = mod << 3;
+
+        if (((tmp.i[div] >> sht) & 0xff) == 0x2e) // '.'
+        {
+          tmp.i[div] += (len - 0x2e) << sht;
+
+          len = 0;
+
+          continue;
+        }
 
-    sha1_update_swap (&ctx1, tmp.i, tmp.pw_len);
+        len++;
+      }
+
+      ctx1.w0[0] = (len & 0xff) << 24;
+
+      ctx1.len = 1;
+
+      sha1_update_swap (&ctx1, tmp.i, tmp.pw_len);
+    }
 
     sha1_update (&ctx1, s_pc, salt_len_pc + 1);
 
diff --git a/src/modules/module_08300.c b/src/modules/module_08300.c
index c5fc7f35..fe7f7e16 100644
--- a/src/modules/module_08300.c
+++ b/src/modules/module_08300.c
@@ -56,7 +56,7 @@ int module_hash_decode (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSE
   token.attr[0]    = TOKEN_ATTR_VERIFY_LENGTH;
 
   token.sep[1]     = ':';
-  token.len_min[1] = 1;
+  token.len_min[1] = 0;
   token.len_max[1] = 32;
   token.attr[1]    = TOKEN_ATTR_VERIFY_LENGTH;
 
@@ -104,9 +104,12 @@ int module_hash_decode (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSE
 
   u8 *salt_buf_pc_ptr = (u8 *) salt->salt_buf_pc;
 
-  memcpy (salt_buf_pc_ptr, domain_pos, domain_len);
+  if (domain_len > 0)
+  {
+    if (domain_pos[0] != '.') return (PARSER_SALT_VALUE);
 
-  if (salt_buf_pc_ptr[0] != '.') return (PARSER_SALT_VALUE);
+    memcpy (salt_buf_pc_ptr, domain_pos, domain_len);
+  }
 
   u8 *len_ptr = salt_buf_pc_ptr;
 
```


test it like this:
```
git checkout https://github.com/hashcat/hashcat hashcat_dnssec_fix
cd hashcat_dnssec_fix
make clean
git pull
git apply dnssec_fix.diff
make
./hashcat -b -m 8300
```

after that instead of the last hashcat command, perform the following test:
1. test if the empty salt works (with -a 0)
2. test if empty domain works (with -a 0)
3. test all the hashes above `kbjciv07olhj0aqkv3fvdr1rm3u6gqal:.shy.cz:67f147cfdd3825b3:10` ,
`kbjciv07olhj0aqkv3fvdr1rm3u6gqal:.cz:67f147cfdd3825b3:10` ,
`kbjciv07olhj0aqkv3fvdr1rm3u6gqal::67f147cfdd3825b3:10` with a dict containing `` , `shy` and `shy.cz` each on a separate file with (-a 0)

The diff again is only for -a 0 (and also no changes yet for optimized kernel -O), the other kernel files have to be changed similarly if we know the changes work and everything is cracking as expected.

Thank you very much for your time and testing

**Comment by exander77** [comment] 2020-05-20 08:31
Sorry for the confusion, I was referring the **current version as without any patches** and describing the behaviour and behaviour I would expect.

I will test the patch and report back. I have not done so yet.

**Closed** 2020-06-09 08:45 UTC

**Comment by y8ttsbftabfvty9g** [comment] 2020-08-09 09:32
Sorry for not replying earlier, I did not set-up email notifications properly.

Thanks @philsmd for the patch!

This issue had been found while working on https://dnssection.ovh.
