### ISSUE TITLE
Bruteforce is slower than before on osx with latest 2 updates of hashcat 

### ISSUE THREAD

**Issue by Virgula0** [hashcat/hashcat#1530] opened 2018-02-24 12:51 UTC
after the latest updates  (current version: 4.0.1 and then to 4.1) I saw that the brute force speed is slower than before...

Example.... (versions before 4.0.1)
I use hash cat utils to convert .cap to hccpax and devices available are the following:

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz, skipped.
* Device #2: HD Graphics 4000, 384/1536 MB allocatable, 16MCU
* Device #3: GeForce GT 650M, 256/1024 MB allocatable, 2MCU

Now... the devices speeds are very lower than before, example:

now:

```
Speed.Dev.#2.....:     2345 H/s (5.11ms)
Speed.Dev.#3.....:     4944 H/s (5.10ms)
Speed.Dev.#*.....:     7286 H/s
```

but before the update (to 4.0.1) speed was about (I don't remember precisely):

```
Speed.Dev.#1.....:     3500 H/s 
Speed.Dev.#2.....:     5800 H/s 
Speed.Dev.#3.....:     16890 H/s
```

If I try to increase the speed of brute force , my computer lags so much:

`hashcat -m 2500 net.hccapx /dict -w 4 -O --session different`

hashcat also show me a warning:

`/usr/local/Cellar/hashcat/4.1.0/share/hashcat/OpenCL/m02500-optimized.cl: Optimized OpenCL kernel requested but not needed - falling back to pure OpenCL kernel`

More information about this problem on the forum: https://hashcat.net/forum/thread-7324-post-39436.html

What happens and how resolve?

**Comment by philsmd** [comment] 2018-02-25 12:04
This could be a duplicate of https://github.com/hashcat/hashcat/issues/1290 and https://github.com/hashcat/hashcat/issues/1497 . For both issues the current impression is that the driver is just very bad on macos, not supporting byte_align () and furthermore doing weird optimizations that lead to bad speed while the non-macos drivers (windows/linux) have no propblem with the identical kernel code.

**Comment by Virgula0** [comment] 2018-02-25 12:12
> This could be a duplicate of #1290 and #1497 . For both issues the current impression is that the driver is just very bad on macos, not supporting byte_align () and furthermore doing weird optimizations that lead to bad speed while the non-macos drivers (windows/linux) have no propblem with the identical kernel code.

but before with previous versions problem didn't exist... only with latest updates of hashcat and of osx

**Comment by philsmd** [comment] 2018-02-25 18:10
I do not have the same hardware but it should be easy to test if the same problems occur with these tests:
https://github.com/hashcat/hashcat/issues/1290#issuecomment-338306987
https://github.com/hashcat/hashcat/issues/1290#issuecomment-367243381

If the problem is the same as mentioned within the 2 other issues, it should be easy for you to find out and see why. Hint: the new feature of supporting password lengths of > 31 (or 55) bytes/characters lead to the introduction of new kernel functions. There was basically no performance loss with good drivers but for macos drivers without byte_align support etc, there seems to be a problem (and therefore the 2 other issues are still open and help/testers are wanted with this specific hardware... but if this is a duplicate, we probably should close it, because we do not need 3 github issues for the same problem).

**Comment by Virgula0** [comment] 2018-02-25 18:37
> I do not have the same hardware but it should be easy to test if the same problems occur with these tests:
#1290 (comment)
#1290 (comment)

I have some problems to check with some commands...

`make clean 
make: *** No rule to make target clean'.  Stop.`

and

`git checkout 52c1e15f3f5b0f50c8ccce3b8b9c604941fe8a57
fatal: reference is not a tree: 52c1e15f3f5b0f50c8ccce3b8b9c604941fe8a57`

and 

`make
make: *** No targets specified and no makefile found.  Stop.`

**Comment by philsmd** [comment] 2018-02-27 07:53
It should be needless to say that whenever you use the git version (or use the git command) you need to use the git version.

To use the source code from git/github you need to clone the repo with this command:
```
git clone https://github.com/hashcat/hashcat
```

you also need to enter the newly created hashcat directory and fetch the submodules/dependencies:
```
cd hashcat
git submodule update --init
```

all of these setup instructions are mentioned within BUILD.md

**Comment by Virgula0** [comment] 2018-02-27 10:07
Test 1

```
hashcat (v3.6.0-48-g52c1e15f) starting in benchmark mode...

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz, skipped.
* Device #2: HD Graphics 4000, 384/1536 MB allocatable, 16MCU
* Device #3: GeForce GT 650M, 256/1024 MB allocatable, 2MCU

Hashtype: WPA/WPA2

Speed.Dev.#2.....:     3098 H/s (81.68ms)
Speed.Dev.#3.....:     6228 H/s (80.26ms)
Speed.Dev.#*.....:     9326 H/s

Started: Tue Feb 27 11:11:52 2018
Stopped: Tue Feb 27 11:12:11 2018
```

Test 2

```
OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz, skipped.
* Device #2: HD Graphics 4000, 384/1536 MB allocatable, 16MCU
* Device #3: GeForce GT 650M, 256/1024 MB allocatable, 2MCU

Hashtype: WPA/WPA2

Speed.Dev.#2.....:     3097 H/s (81.68ms)
Speed.Dev.#3.....:     6236 H/s (80.05ms)
Speed.Dev.#*.....:     9333 H/s

Started: Tue Feb 27 11:13:26 2018
Stopped: Tue Feb 27 11:14:02 2018
```

If I try to do benchmark test with hashcat installed via homebrew it shows me errors of devices

```
hashcat (v4.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz, skipped.
* Device #2: HD Graphics 4000, 384/1536 MB allocatable, 16MCU
* Device #3: GeForce GT 650M, 256/1024 MB allocatable, 2MCU

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 2500 - WPA/WPA2 (Iterations: 4096)

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

<program source>:12:1: error: unknown type name 'DECLSPEC'
DECLSPEC void generate_pw (u32 pw_buf[64], __global const cs_t *root_css_buf, __global const cs_t *markov_css_buf, const u32 pw_l_len, const u32 pw_r_len, const u32 mask80, const u32 bits14, const u32 bits15, u64 val)
^
<program source>:12:10: error: expected identifier or '('
DECLSPEC void generate_pw (u32 pw_buf[64], __global const cs_t *root_css_buf, __global const cs_t *markov_css_buf, const u32 pw_l_len, const u32 pw_r_len, const u32 mask80, const u32 bits14, const u32 bits15, u64 val)
         ^

* Device #2: Kernel /usr/local/Cellar/hashcat/4.1.0/share/hashcat/OpenCL/markov_le.cl build failed - proceeding without this device.

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

<program source>:12:1: error: unknown type name 'DECLSPEC'
DECLSPEC void generate_pw (u32 pw_buf[64], __global const cs_t *root_css_buf, __global const cs_t *markov_css_buf, const u32 pw_l_len, const u32 pw_r_len, const u32 mask80, const u32 bits14, const u32 bits15, u64 val)
^
<program source>:12:10: error: expected identifier or '('
DECLSPEC void generate_pw (u32 pw_buf[64], __global const cs_t *root_css_buf, __global const cs_t *markov_css_buf, const u32 pw_l_len, const u32 pw_r_len, const u32 mask80, const u32 bits14, const u32 bits15, u64 val)
         ^
<program source>:55:3: warning: implicit declaration of function 'generate_pw' is invalid in C99
  generate_pw (pw_buf, root_css_buf, markov_css_buf, pw_l_len, pw_r_len, mask80, bits14, bits15, off + gid);
  ^

* Device #3: Kernel /usr/local/Cellar/hashcat/4.1.0/share/hashcat/OpenCL/markov_le.cl build failed - proceeding without this device.

Started: Tue Feb 27 11:15:00 2018
Stopped: Tue Feb 27 11:15:01 2018
```

**Comment by philsmd** [comment] 2018-02-27 14:58
To me it seems to be the exact same problem (because the same patches fix the speed problem also for you)
This issue should be marked as a duplicate and closed. The discussion about a possibe fix can continue here: https://github.com/hashcat/hashcat/issues/1290

**Comment by Virgula0** [comment] 2018-02-27 15:17
So i will wait for next patches and updates from Homebrew to resolve, or download and execute hashcat with the latest patch manually

**Closed as completed** 2018-02-28 09:15 UTC
