### ISSUE TITLE
hashcat crashes when attempting to crack DCC2

### ISSUE THREAD

**Issue by thesle3p** [hashcat/hashcat#125] opened 2016-01-13 20:56 UTC
On the latest git version of oclHashcat as well as cudahashcat 2.0.1 the following error message is returned when attempting to run a straight attack with rules on a Mscache2 dump 

```
oclHashcat v2.10 starting...

Device #1: GeForce GTX 980 Ti, 1535/6143 MB allocatable, 1190Mhz, 22MCU

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 8452
Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger disabled

Device #1: WARNING! Kernel exec timeout is not disabled, it might cause you errors of code 702
           See the wiki on how to disable it: https://hashcat.net/wiki/doku.php?id=timeout_patch
Device #1: Kernel /home/bob/Toolz/oclHashcat/kernels/m02100.17e58bd3.kernel (400289 bytes)
Device #1: Kernel /home/bob/Toolz/oclHashcat/kernels/amp_a0.17e58bd3.kernel (477967 bytes)


ERROR: clSetKernelArg() -48

```

Here are the parameters I provided to hashcat 

```
sudo ./oclHashcat -m 2100 -a 0 -r ../princeprocessor/rules/prince_generated.rule path/to/hash/file/ /path/to/word/file 
```

**Comment by jsteube** [comment] 2016-01-13 21:25
Please retry with latest GitHub version, I think this change should solve it:

https://github.com/hashcat/oclHashcat/commit/49d0767aa8118b60d4caba64ebd808b5e64baa4e

You can also try the latest beta build 44 from https://hashcat.net/beta/

**Comment by thesle3p** [comment] 2016-01-13 21:27
It works but I am now getting 0 hashes a second, which never happened
before.

**Comment by philsmd** [comment] 2016-01-13 22:13
We should close this, please reopen a new ticket if you think there is another problem.
(BTW: I can't reproduce the 0 H/s problem, please make sure you have a clean directory - new download, no cached kernels and that your command line is okay, test just -m 2100 -b for instance. If this is still a problem, please open a new issue, because this seems to be unrelated here)

**Comment by thesle3p** [comment] 2016-01-13 22:52
It's solved, had the hash in a incorrect format (missing $10240)

**Comment by jsteube** [comment] 2016-01-14 08:03
Fixed

**Closed as completed by jsteube** 2016-01-14 08:03 UTC
