### ISSUE TITLE
keepass module (13400) may be wrong

### ISSUE THREAD

**Issue by Setplus01** [hashcat/hashcat#2195] opened 2019-09-25 09:44 UTC
I 've decided to review module 13400 and discovered that using script from [site](https://gist.github.com/HarmJ0y/116fa1b559372804877e604d7d367bbc) and hashcat:

`hashcat -a 0 -m 13400 test.hash example.dict`

cause an error:

> Hashfile 'test.hash' on line 1 ($keepa...becc74fd6ba40c7254d1c47f672d5bbf): 
> Token length exception
> No hashes loaded.

Inner of test.hash:

`$keepass$*2*0*253*e73cfb2502b6e543902ec7db45c751195c3dd8b8531b744537cbeebd8c641ecd**59ac17e7e0a201e1fae906371d65f6c6**8753d87e52c88988d168c9a4c75e76febecc74fd6ba40c7254d1c47f672d5bbf`

I asked a question [here](https://security.stackexchange.com/questions/218642/new-format-of-keepass-2-database-file-and-hashcat#218642)

May be i am wrong?

**Comment by philsmd** [comment] 2019-09-26 07:56
did you try to compare the output hash with the keepass2john binary from https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/src/keepass2john.c

I think those
```
**
```
that you have several times in your hash are very suspicious.

Did you try to crack this hash with john ?

I would say you should try keepass2john from the magnumripper github project (and remove the file names to get a hash similar to the one mentioned here: https://hashcat.net/wiki/example_hashes or as seen in hashcat -m 13400 --example-hashes)

It could easily be the case that "just" that python port is kinda buggy. if this is the case you should probably comment it on that gist and start using the keepass2john binary instead (from magnumripper directly, because that python port is a port anyways)

**Comment by Setplus01** [comment] 2019-09-26 12:10
1. Yes, i 've compared and no, my hash string is different with recommended by hashcat. 
2. I 've used keepass2john.c following way (John the Ripper 1.9.0-jumbo-1 OMP [linux-gnu 64-bit x86_64 AVX AC]):
john-the-ripper.keepass2john test.kdbx

and got following error:

File version '40000' is currently not supported!

3. And i still think that KeePassX changed format of their `.kdbx' DB files so source code need to be changed. Or i may be wrong and not attentive enough.

**Comment by philsmd** [comment] 2019-09-26 18:24
I see you also posted here: https://security.stackexchange.com/questions/218642/new-format-of-keepass-2-database-file-and-hashcat (I assume here that "MrSetplus" is you).

keepass2john comments say that only up to keepass 2.36 (not included) are supported:

https://github.com/magnumripper/JohnTheRipper/blob/ea33667eb5e1a650ecb6b4985125f4efa0955594/src/keepass2john.c#L81

newer versions (could) use argon2 or chacha20
(also see some related posts on the jtr github issue: https://github.com/magnumripper/JohnTheRipper/issues/2502 )

this is also related: 
https://github.com/magnumripper/JohnTheRipper/blob/ea33667eb5e1a650ecb6b4985125f4efa0955594/src/keepass2john.c#L83-L85

I would recommend you find out which version of keepass you use and which cipher is used for your kdbx file specifically, also see CipherID here: https://github.com/magnumripper/JohnTheRipper/blob/ea33667eb5e1a650ecb6b4985125f4efa0955594/src/keepass2john.c#L445

you could try to debug it and also maybe comment out this: https://github.com/magnumripper/JohnTheRipper/blob/ea33667eb5e1a650ecb6b4985125f4efa0955594/src/keepass2john.c#L484-L487 for testing purposes (and re-compile)... but if argon2 or ChaCha20 are used in your case it's not supported by hashcat, only AES/Twofish are supported

btw: this new github issue for hashcat seems to be a duplicate of https://github.com/hashcat/hashcat/issues/1013 , so we should close one (the newer one normally)

**Comment by acamro** [comment] 2019-10-27 11:45
I was testing the module with AES and no key file, but it doesn't work at all:

keepass2john Hash:

> $keepass$*2*166505600*0*257446a38e2e55c1281c72eedbec7763977967952131c227cd1c67380e4b6929*922fe244a375d6db0112bf37a26291871f7281b1ec8b07665986371b0fc4c651*f1e2a96915786b5a9324c3985c966317*fafcf1f3a20ac08d467a7abc331ae1da63c206ef7a580b93eda75f86aeaedd88*86082a7e1344a1ff1e0dd5d52b36c31107ad3f80c6bb8bffd7293608b4afa75b

This is the error in the Hashcat output:

> ./OpenCL/m13400-optimized.cl: Optimized OpenCL kernel requested but not needed - falling back to pure OpenCL kernel
> Hashfile 'D:\Projects\zzzz\yyyy\xxxx\kepass_hash.txt' on line 1 ($keepa...07ad3f80c6bb8bffd7293608b4afa75b): Token length exception
> No hashes loaded.

Then I tried to crack the kdbx file with mod0keecrack and this is the output:
> [*] using  db: .\my_password.kdbx
> [*] using key: .\my_password.key
> [*] kdbx header:
> [-]    file magic:          9aa2d903
> [-]    file identifier:     b54bfb67
> [-]    file minor version:  0001
> [-]    file major version:  0003
> [*] kdbx headerentries:
> [-]    END:                 0D0A0D0A
> [-]    COMMENT:
> [-]    CIPHERID:            31C1F2E6BF714350BE5805216AFC5AFF
> [-]    COMPRESSIONFLAGS:    00000001
> [-]    MASTERSEED:          257446A38E2E55C1281C72EEDBEC7763977967952131C227CD1C67380E4B6929
> [-]    TRANSFORMSEED:       922FE244A375D6DB0112BF37A26291871F7281B1EC8B07665986371B0FC4C651
> [-]    TRANSFORMROUNDS:     0000000009ecac80
> [-]    ENCRYPTIONIV:        F1E2A96915786B5A9324C3985C966317
> [-]    PROTECTEDSTREAMKEY:  DEE4F3821B50152D9B33FE59075F83EB915E6DE1E877287FA11EED13CA009523
> [-]    STREAMSTARTBYTES:    FAFCF1F3A20AC08D467A7ABC331AE1DA63C206EF7A580B93EDA75F86AEAEDD88
> [-]    INNERRANDOMSTREAMID: 00000002
> [*] kdbx payload:
> [-]    payload offset:      de
> [-]    payload len:         8a0
> [*] Not using keyfile
> [*] kdbx crack:
> [*] decryption successful with password colombia1uqbarRunalbogota

**Comment by jsteube** [comment] 2020-01-05 19:30
Duplicate of https://github.com/hashcat/hashcat/issues/1013

**Closed as completed by jsteube** 2020-01-05 19:30 UTC
