### ISSUE TITLE
support for Multibit Classic hash with GPU

### ISSUE THREAD

**Issue by deloxd** [hashcat/hashcat#2023] opened 2019-05-15 10:44 UTC
Hi, 

I see the subject die. Maybe somebody try crack hash from Multibit? I try to find solution. 
I can give reward to somebody for help.

**Comment by philsmd** [comment] 2019-05-16 06:54
there are acutally several versions of multibit hashes/wallets, see #1538 (this issue is a duplicate of that older issue). Did you try to run multibit2john.py from magnumripper's john the ripper repository (it's a python 2.7 script) to see which type of wallet/hash you have ?
In theory we would need to close this issue as duplicate (again !, see #1601 ).
The problem with scrypt is also that the GPU support might not be that effective like with many other hashes (depends also on the N, r, p parameters, didn't look at those yet)... so it's probably more important that you have a lot of very fast CPUs for scrypt hashes (in general).

**update**: the default seems to be N = 16384, r = 8, p = 1

**Comment by jsteube** [comment] 2019-05-22 09:43
Double post

**Closed as completed by jsteube** 2019-05-22 09:43 UTC

**Comment by deloxd** [comment] 2019-05-22 15:28
Yes I have the default seems to be like you wrote N = 16384, r = 8, p = 1
