### ISSUE TITLE
False positive results hashcat beta 15xx+ versions modes 12700&15200 (blockchain)

### ISSUE THREAD

**Issue by eastsida** [hashcat/hashcat#2264] opened 2020-01-06 09:59 UTC
Hello, i dont know what changes you've made but previously i had 1403 beta and it shows recovered 0/1.
Since version 15xx+ they shows recovered 1/1. But when i tried to login into blockchain it shows wrong password. Plus tested on my decryptor Mode = CipherMode.CBC, Padding = PaddingMode.ISO10126 and i got System.Security.Cryptography.CryptographicException.
So, no way it decrypted it properly.
Screens:
Version 1403(beta)
https://i.imgur.com/5TECB47.png
Version 1545(beta)
https://i.imgur.com/m4uNMpG.png
Blockchain
https://i.imgur.com/Ob0uHIR.png
My test decryptor
https://i.imgur.com/3q2i1uA.png

**Comment by philsmd** [comment] 2020-01-06 12:04
thanks for the report.

Most important question is why did you not test with latest beta from https://hashcat.net/beta ?

We have this recent change that should prevent false positives https://github.com/hashcat/hashcat/commit/40a5835927f8bc8e39fffd4ed4fa7a9d8e38b69c

Can you share a wallet file that leads to false positives for us to troubleshoot or generate a new one etc ? It' very difficult to reproduce a problem without the data

**Comment by eastsida** [comment] 2020-01-06 12:24
> thanks for the report.
> 
> Most important question is why did you not test with latest beta from https://hashcat.net/beta ?
> 
> We have this recent change that should prevent false positives [40a5835](https://github.com/hashcat/hashcat/commit/40a5835927f8bc8e39fffd4ed4fa7a9d8e38b69c)
> 
> Can you share a wallet file that leads to false positives for us to troubleshoot or generate a new one etc ? It' very difficult to reproduce a problem without the data

Well firstly i tried on 1534 or what was that version after this on 1545 which means you chaged something after version 1403 or liltle bit later. But starting from 15xx+ all will have the same problem.
But ok here you go 1561
https://i.imgur.com/hqZKIkc.png
Yes i can share but not here of course. I can send you via email version 1 false result and version 2,3 false result.
Plus can i ask what is the definition of "decrypted" output ?  As i understood it's looking at first bytes and if they contains "tx_notes", "address" and so on that means it decrypted correctly ? Or i am wrong ? Is this possible for example encode output into json and if it's fail means output not decrypted but i don't know if it will have impact on a speed and how hard to implement this.
But anyway i need email or telegram or something and i will send you this false positive hashcat samples. Thank you.

**Comment by philsmd** [comment] 2020-01-06 12:35
We tried that approach with matching specific strings but it didn't really work well, see https://github.com/hashcat/hashcat/issues/1937 and https://hashcat.net/forum/thread-8814-post-46829.html#pid46829 etc
The problem is that the json objects will be randomly rearranged, because there is no order that the json elements are written to the wallet file. so we have the problem of randomness and that we do not know all the strings we should find.

Could you send the wallet to @jsteube , he will hopefully help to investigate this issue.\
We would probably also need to correct password and the "wrong" password.
The emails addresses can be found in the git commit logs and or the github profile page https://github.com/jsteube
thx

**Comment by eastsida** [comment] 2020-01-06 13:36
Thank you i will send results. About json actually you don't need to search something in output I meant you taking output when hashcat counts that it decrypted encrypted data properly then you encoding it into json which contains some "scheme" or "format" started with "{" ended with "}" has elements that "structured" in certain way.
For example:
Valid
https://i.imgur.com/X1U2Es9.png
Wrong decrypted
https://i.imgur.com/96M3gt8.png
So based on this you can define if it's whole properly decrypted json format wallet without searching address, tx_notes and so on, only based on schema, structure.
Something like this
https://stackoverflow.com/questions/14977848/how-to-make-sure-that-string-is-valid-json-using-json-net
https://tools.ietf.org/html/draft-json-schema-language-01
Plus if they will create wallet v4,5,6 and so on you don't need to look again what it contains and implement new fixes again and again. It will have the same json "structure" in all new versions.
For now i can only tell from 3k decrypted wallets they all starts with "{" ends with "}" and mandatory all contains " "guid" "

**Comment by jsteube** [comment] 2020-01-06 22:11
Fixed with https://github.com/hashcat/hashcat/commit/74c1bf81950f989501a01c9f08da137db513f593
Thanks for reporting
Beta updated

**Closed by jsteube** 2020-01-06 22:11 UTC
