### ISSUE TITLE
Minor bug in rule "E" : RULE_OP_MANGLE_TITLE

### ISSUE THREAD

**Issue by elegant-git** [hashcat/hashcat#2823] opened 2021-06-12 17:39 UTC
The "cap after space" seems to ignore letters that are in positions that are multiples of 4.
Lines below are repeating (3 spaces + letter) with a variable number of leading spaces.

```
rule.txt
E

word.txt
a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a
 a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a
  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a
   a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a
    a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a
     a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a
      a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a
       a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a
        a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a
         a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a

output.txt
hashcat-6.2.1>hashcat.exe word.txt -r rule.txt --stdout >output.txt
Successfully initialized NVIDIA CUDA library.


A  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  <--  should be all caps?
 A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A
  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A
   A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A
    a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  <--  should be all caps?
     A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A
      A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A
       A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A
        a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  a  <--  should be all caps?
         A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A  A




```

**Comment by elegant-git** [comment] 2021-06-12 18:13
Example with "real" sentence... 

```
INPUT  the quick brown fox jumps over the lazy dog.
  BUG  The quick Brown fox jumps Over The Lazy dog.
           ^           ^   ^                   ^
POS(0)     4           16  20                  40
           |           |   |                   |
EXPECT The Quick Brown Fox Jumps Over The Lazy Dog.
```

**Comment by jsteube** [comment] 2021-06-13 12:38
Can you please provide me with the command line you were using. I'm wondering if this affects both optimized and pure kernels.

**Comment by elegant-git** [comment] 2021-06-13 12:54
Greetings, I believe it affects both kernels.
Thank you for your help!

Here is the command line (same as in the git):

D:\hashcat-6.2.1>hashcat.exe word.txt -r rule.txt --stdout
Successfully initialized NVIDIA CUDA library.

Failed to initialize NVIDIA RTC library.

* Device #1: CUDA SDK Toolkit installation NOT detected or incorrectly
installed.
             CUDA SDK Toolkit installation required for proper device
support and utilization
             Falling back to OpenCL Runtime

The quick Brown fox jumps Over The Lazy dog.
A   a   a   a   a   a   a   a   a   a   a   a   a   a   a   a   a   a   a
a   a   a
 A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A
  A   A   A
  A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A
  A   A   A
   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A
A   A   A   A
    a   a   a   a   a   a   a   a   a   a   a   a   a   a   a   a   a   a
a   a   a   a
     A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A
  A   A   A   A
      A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A
  A   A   A   A
       A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A
A   A   A   A   A
        a   a   a   a   a   a   a   a   a   a   a   a   a   a   a   a   a
a   a   a   a   a
         A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A   A
  A   A   A   A   A

**Comment by elegant-git** [comment] 2021-06-13 13:08
Good call.. upon further testing, I think this may only impact the pure
kernel!

The optimized kernel cracked all of the test hashes (md5):

Input words: (goal_lower.txt)
the quick brown fox
a
 a
  a
   a
    a

Target Hashes ( hashes.txt)
22cd45cf6bd51bc0398b46744c097f26
7fc56270e7a70fa81a5935b72eacbe29
4a1f10599d93d68b762e897cc09870a1
1ee35543227781c739e656cb8cc8ef1e
a2c768e0dedd8f8fdc8fa8864fe4bc4d
e7bac7dbaa7413e4068a28b7a2366c63


D:\hashcat-6.2.1>hashcat.exe hashes.txt -a 0 goal_lower.txt -r rule.txt
--potfile-disable --outfile=optimized_kernel.pot -O
Optimized KERNEL RESULTS (6 of 6)
22cd45cf6bd51bc0398b46744c097f26:The Quick Brown Fox
7fc56270e7a70fa81a5935b72eacbe29:A
4a1f10599d93d68b762e897cc09870a1: A
1ee35543227781c739e656cb8cc8ef1e:  A
a2c768e0dedd8f8fdc8fa8864fe4bc4d:   A
e7bac7dbaa7413e4068a28b7a2366c63:    A

D:\hashcat-6.2.1>hashcat.exe hashes.txt -a 0 goal_lower.txt -r rule.txt
--potfile-disable --outfile=regular_kernel.pot
REGULAR KERNEL RESULTS  (4 of 6)
7fc56270e7a70fa81a5935b72eacbe29:A
4a1f10599d93d68b762e897cc09870a1: A
1ee35543227781c739e656cb8cc8ef1e:  A
a2c768e0dedd8f8fdc8fa8864fe4bc4d:   A

**Comment by jsteube** [comment] 2021-06-13 13:26
OK, I can reproduce, looking into it.

**Comment by jsteube** [comment] 2021-06-13 13:51
OK, this should be fixed with commit https://github.com/hashcat/hashcat/commit/8ebf4b98584213891f6e48570c91c31d22b80a81

If you compile from source keep in mind that you need to use make clean, because the rule engine code from OpenCL is shared with the host program. After cracking succeeds on the GPU the host has to redo the exact same steps as the GPU did because the password is not send back in full for performance reasons only the base word and the rule number.

If you use binary version, I have also updated to a new beta binary build on hashcat.net/beta

Please confirm the bug fixed and close the issue. 

Thanks for reporting!

**Comment by elegant-git** [comment] 2021-06-13 14:30
Thank you!!
Best regards,
Al

**Closed as completed** 2021-06-13 14:31 UTC
Labels: bug
