### ISSUE TITLE
Veracrypt boot - segmentation fault

### ISSUE THREAD

**Issue by Banaanhangwagen** [hashcat/hashcat#2317] opened 2020-03-01 19:37 UTC
I work with Hashcat v5.1.0-1710 on a Ubuntu server with correctly installed nvidia driver 440.33.01.

During some testing with Veracrypt boot (with the example hashes, as found on Hashcat-website), I noticed that Hashcat gives a _segmentation fault_ when the correct password is given (during -a 0 or -a 3 attack).
When a wrong password is given, or a wordlist without the correct candidate, one gets the expected result "exhausted".

This is the case for 13761, 13762 and 13763.

I tested it also on a Windows-machine. When the correct candidate is given, it just quits the job without any error reporting, or - in rare cases - it gives the error:
```
(...)
Host memory required for this attack: 116 MB

▓       ¿ÿÐ;╣Oâó³>├ ô2$oÊGcJ┤┐âä²░4IUõ┴Ý¶sÚáÔp¿½è_NðqÈºI▒║èZj;Ä©GuÕKd¦╬Î┌'åøc┴2@7.IîÂ┐á▄■J=]ú©Ùâìì{£╩ÎU╩«%9Ý' because it is larger than the maximum password length.

Started: Sun Mar 01 20:20:04 2020
Stopped: Sun Mar 01 20:20:16 2020
```

Are you able to reproduce this error?

**Comment by Chick3nman** [comment] 2020-03-02 02:43
I have reproduced this error using the latest beta. When testing the example file for 13761, a correct password will cause a segfault. Will need to investigate the issue further to find the root cause.

**Comment by jsteube** [comment] 2020-03-02 09:23
Excellent, thanks for reporting. Fixed with https://github.com/hashcat/hashcat/commit/b627536c452dc8f204da0c9c9417f7cf10e26d47

**Closed as completed by jsteube** 2020-03-02 09:23 UTC
