### ISSUE TITLE
CL_BUILD_PROGRAM_FAILURE. macOS 10.14.6

### ISSUE THREAD

**Issue by shaltai** [hashcat/hashcat#2176] opened 2019-08-29 19:45 UTC
Hello!

I got this error. What am I doing wrong? Help me please :-(

iMac:naive-hashcat shaltai$ HASH_FILE=/var/tmp/home.hccapx POT_FILE=home-wifi.txt HASH_TYPE=2500 ./naive-hashcat.sh

```
hashcat (v5.1.0-1397-g7f4df9eb) starting...

OpenCL API (OpenCL 1.2 (Jun 23 2019 21:50:55)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz, skipped
* Device #2: AMD Radeon R9 M380 Compute Engine, 512/2048 MB allocatable, 12MCU

Hashes: 4 digests; 2 unique digests, 2 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Slow-Hash-SIMD-LOOP

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

Error returned by cvms_element_build_from_source
* Device #2: Kernel /Users/shaltai/naive-hashcat/hashcat-src/OpenCL/m02500-pure.cl build failed - proceeding without this device.
```

**Comment by mike-lo** [comment] 2019-10-09 10:10
Probably duplicate of #1497

**Comment by Rdgeno** [comment] 2019-10-09 15:39
I looked at your link on windows they are able to do something with it. I just get an error and it shuts down

**Comment by Rdgeno** [comment] 2019-10-09 15:43
If you carefully read the post I have to input commands wrong to get anything in unbuntu.

**Comment by jsteube** [comment] 2019-12-24 09:45
We successfully fixed a similar problem on OSX + Vega GPU. Maybe it helps for this issue as well. Please retry with new GitHub master version and make sure to have the kernels/ kernel cached removed first.

**Comment by jsteube** [comment] 2020-07-03 11:36
Please retry with hashcat 6.0.0 + 32 beta from https://hashcat.net/beta/ and reopen the issue if it still exists.

**Closed as completed by jsteube** 2020-07-03 11:36 UTC
