### ISSUE TITLE
RAR 3 unencrypted filenames

### ISSUE THREAD

**Issue by quaesit** [hashcat/hashcat#1001] opened 2017-01-29 11:35 UTC
Aka 99% of the archives out there. Please consider adding mode/kernel if possible. Thank you for sharing your work for free.

**Comment by philsmd** [comment] 2017-01-29 13:30
This is a duplicate of https://github.com/hashcat/hashcat/issues/68 . We should consider closing this issue as duplicate and keep #68 open, do you agree?

**Closed as completed** 2017-01-30 10:57 UTC

**Comment by corporateshark** [comment] 2019-04-16 18:37
#68 was closed. Please, reopen this one.
