### ISSUE TITLE
Hash not broken even though password is generated by rule

### ISSUE THREAD

**Issue by lukasz-cr** [hashcat/hashcat#2871] opened 2021-07-08 10:20 UTC
I am using HaschCat 6.2.2. The same problem occurs when I use HashCat 6.2.1.

I wanted to break this hash: $1$kik$hPT5.9swyJPYLyMlDthqU/ which corresponds to TheWeeknd123

When I use this command
.\hashcat.exe -O -w 3 -m 500 -a 0 md5crypt.txt dict.txt -r passphrase-rule1.txt -r passphrase-rule2-shortened.txt --stdout
I see that TheWeeknd123 is generated, and if I capture the output of this command and later use it for a dictionary attack I break the hash. Everything works the way it should.

However, when I use this command, i.e., I do the same thing without redirecting the output to the console, the has does not get broken.
.\hashcat.exe -O -w 3 -m 500 -a 0 md5crypt.txt dict.txt -r passphrase-rule1.txt -r passphrase-rule2-shortened.txt

[dict.txt](https://github.com/hashcat/hashcat/files/6783705/dict.txt)
[md5crypt.txt](https://github.com/hashcat/hashcat/files/6783707/md5crypt.txt)
[passphrase-rule1.txt](https://github.com/hashcat/hashcat/files/6783716/passphrase-rule1.txt)
[passphrase-rule2-shortened.txt](https://github.com/hashcat/hashcat/files/6783717/passphrase-rule2-shortened.txt)

**Comment by Xanadrel** [comment] 2021-07-08 10:33
Can reproduce, can you try using latest beta from here: https://hashcat.net/beta/ ?
Also it will probably be cracked if you use -S with hashcat 6.2.2 (not beta).

**Comment by jsteube** [comment] 2021-07-08 10:46
I think this is a double post, we had it fixed a few days ago with commit https://github.com/hashcat/hashcat/commit/8ebf4b98584213891f6e48570c91c31d22b80a81

Please retry with latest beta

**Comment by lukasz-cr** [comment] 2021-07-08 10:50
Yes, I have tested it using the beta version, and the hash got cracked properly.

**Comment by Xanadrel** [comment] 2021-07-08 10:52
Closing, duplicate of #2823

**Closed as completed by Xanadrel** 2021-07-08 10:52 UTC
Labels: bug, duplicate
