### ISSUE TITLE
Add Yescrypt

### ISSUE THREAD

**Issue by geo7652** [hashcat/hashcat#4124] opened 2024-11-26 16:18 UTC
After years I still can't find yescrypt in hashcat. Bruteforcing it with cpu is very slow so when will it be added to hashcat?

**Is your request based on a publicly known cryptographic schema and where can we find information about?**
Yes

**Describe alternatives you've considered**
I can't find anything to bruteforce it with gpu

**Where do you typically find the algorithm**
Every distro

**Comment by Xanadrel** [comment] 2024-11-26 17:04
Duplicate of #2816

**Closed as not planned by Xanadrel** 2024-11-26 17:04 UTC
Labels: new algorithm, duplicate
