### ISSUE TITLE
Custom charset not found in hybrid mode

### ISSUE THREAD

**Issue by tampe125** [hashcat/hashcat#1353] opened 2017-09-09 06:52 UTC
Hello,

I'm trying the hybrid attack `-a 7` (mask + wordlist) and I supplied a mask file.
Since the amount of special chars is lower than the standard one, I'm using the custom placeholder `?1` inside the mask file. For example:
```
?d?d?d?d?l?1
?d?d?d?1?l?d
```

This is the command I'm using to run Hashcat 3.6.0:
`./hashcat64.bin -m 0 -a 7 --outfile results.txt --status -1 -_. hash.txt mymask.hcmask mywordlist.txt`

However I always get the following error:
`Custom-charset 1 is undefined.`

If I manually specify the mask instead of supply a mask file, everything works as expected.

**Comment by philsmd** [comment] 2017-09-09 07:26
Hey,
it is explained here https://hashcat.net/wiki/?id=mask_attack#hashcat_mask_files:
```
It is not allowed that a [mask] contains ?1,?2,?3 or ?4 references without those being set via [?1], [?2], [?3], [?4]. This will result in an error message. If you want to use a custom charset for your masks you must define it within the same line of the hcmask file by using the [?1], [?2], [?3], [?4] fields.
```

This means that you need to define the custom charset directly within the .hcmask file (only if you use  at least one out of ?1 ?2 ?3 ?4 within your mask).

This was actually recently changed (in the past it also worked with the custom charset defined on the command line) because users forgot to set the customer charset within the .hcmask line and where confused why hashcat uses "a different custom charset" etc... Furthermore, previous versions also used the "default charsets" whenever no charsets were defined and this made it even more confusing for the user which couldn't figure out what was going on.

I think this change makes sense... the only problem is: whenever the user wants to use a set of (up to 4) custom charset for each and every mask within the .hcmask file... then the .hcmask file must be prepended with the same custom charsets on each and every line (but I guess this is a good compromise and doesn't make anything slower or something like this... it is just much more easier to troubleshoot and understand).

so your mymask.hcmask file must look like this:
```
-_.,?d?d?d?d?l?1
-_.,?d?d?d?1?l?d
```

and your command line must look like this:
```
./hashcat64.bin -m 0 -a 7 --outfile results.txt --status mymask.hcmask mywordlist.txt
```

**Comment by tampe125** [comment] 2017-09-09 07:48
So it was a clear case of RTFM :)
Thanks for taking your time to explain it to me.

**Comment by philsmd** [comment] 2017-09-09 13:18
Glad it works for you now too (with the correct syntax).

Please do not forget to close the issue if you are sure the problem is fixed/resolved (only the repo owner or the OP can close github issues here).

**Closed as completed** 2017-09-09 13:19 UTC
