### ISSUE TITLE
Some rules don't work with --stdout properly

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#3597] opened 2023-01-26 14:08 UTC
**Describe the bug**

Rules `d`, `f`, and probably other don't work properly with `--stdout`.

**To Reproduce**

```
$ cat dic 
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
$ cat rule
d
$ hashcat.bin --version
6.2.6
$ hashcat.bin --stdout -r rule dic
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
```

Output of the last command may vary.

**Expected behavior**

```
$ hashcat.bin --stdout -r rule dic
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
```

**Hardware/Compute device (please complete the following information):**
- Compute device name: NVIDIA GeForce GTX 1050 Ti, 3809/4036 MB, 6MCU
- OpenCL/CUDA driver name: nvidia-drivers
- OpenCL/CUDA driver version: 525.60.13

**Hashcat version (please complete the following information):**
 - OS: Linux
 - Distribution: Gentoo

**Comment by Chick3nman** [comment] 2023-01-26 15:41
This is a duplicate of #3596 so I'm going to close this issue and work on it over there.

**Closed as not planned by Chick3nman** 2023-01-26 15:41 UTC
Labels: duplicate
