### ISSUE TITLE
Unsupported AMD HIP runtime version '0.0.3276' detected! Falling back to OpenCL...

### ISSUE THREAD

**Issue by mikekornikh** [hashcat/hashcat#2971] opened 2021-09-08 17:44 UTC
Hi! I just installed the new version of Hashcat (6.2.4) and when I start it I get this message-
Unsupported AMD HIP runtime version '0.0.3276' detected! Falling back to OpenCL...
Do I need to manually install the proper HIP runtime? I'm running it in Windows 10 on an AMD Radeon RX 5700 graphics card. Thank you for the help!

**Comment by jtojanen** [comment] 2021-09-08 21:33
The message you received is informative, not an error. Everything will work just fine with OpenCL. This is not a bug, please close this and use hashcat forums instead.

**Closed as completed** 2021-09-09 07:12 UTC
