### ISSUE TITLE
Windows 8.1 ETH Wallet Crack Out of Resources

### ISSUE THREAD

**Issue by ryanwoods1706** [hashcat/hashcat#1483] opened 2018-01-02 20:00 UTC
**OS:** Windows 8.1 64 Bit
**Hashcat** Version: 4.0.1
**Hardware:** 
    Intel Core i5-4670
    16 GB RAM
    Nvidia GTX 760

**Issue:**
- It seems that hashcat is crashing my GPU driver and therefore doesnt run the hash, and the reason it outputs is that it is out of resources? I'm assuming this is memory/RAM? Anyway to resolve this/get this working? The image below (print screen) shows more details of the errors.
http://prntscr.com/hv8s0o

**Comment by ryanwoods1706** [comment] 2018-01-02 20:03
Also a side note, I'm cracking an ETH wallet for a friend that has about 22k worth of Ethereum in it, so if someone can help me resolve this, once I'm in I'm willing to pay :)

**Comment by ryanwoods1706** [comment] 2018-01-02 20:05
@jsteube Sorry for the tag, but I'd appreciate some help :)

**Comment by philsmd** [comment] 2018-01-03 07:19
You should use --opencl-device-types 1 (or short -D 1) to crack with your CPU.
Your GPU has not enough resources (mainly the huge amount of VRAM memory needed for scrypt) to crack ethereum scrypt hashes (-m 15700 = Ethereum Wallet, Scrypt)

**Comment by ryanwoods1706** [comment] 2018-01-03 09:18
@philsmd So its impossible to crack it with a GPU? How much VRam is needed? What if i purchase 256GB of system memory will that work at all or not?

**Comment by philsmd** [comment] 2018-01-03 10:02
no an upgrade of the RAM (system volatile memory) doesn't help much if you want to use your GPUs. The VRAM (GPU memory) is much more important.

The hashing algorithm scrypt with those very high costs/settings is known to be GPU-unfriendly. I'm not totally sure if a 1080ti has enough VRAM to be able to run -m 15700 (fast enough). Everything below a 1080ti (which has 11GB, but only part of that can be used by OpenCL... but there is even a nice workaround that hashcat uses with multiple memory allocations) is probably not able to run -m 15700, I guess. Again, I'm not sure if a 1080ti (is able to run -m 15700 fast enough and) is much faster for -m 15700 as a modern high-end CPU.
What also matters a lot are the cost settings for scrypt (but as far as I know for -m 15700 they are mostly the same for all hashes and .... very high settings)... therefore scrypt with a specific set of settings could be very different compared to scrypt with much higher cost settings.

It's actually not too difficult to calculate the memory needed for a specific set of settings (in general).... but since hashcat is able to do multiple allocation and also supports tmto (Time Memory Trade Off) it's actually a little bit more complicated to do the math... again, scrypt is known to use a lot of memory and is known to be GPU-unfriendly by design

**Comment by ryanwoods1706** [comment] 2018-01-03 10:11
@philsmd So really GPU cracking the wallet is out of the question?

**Comment by philsmd** [comment] 2018-01-03 13:58
As said, you could try with a GPU with much more memory (like the nvidia 1080ti), it won't show you the resource error, but it's probably only slightly faster than a modern (high-end) CPU... because it still needs to use a high tmto value and make multiple allocation.... these problems are not present with high-end CPUs.
But I've tested with a 1080ti and it runs -m 15700 just fine... so either you use at GPU with at least the memory available also for a 1080ti... or just crack with a very good CPU (and avoid high tmto and multiple memory allocation altogether).

I think you should close this issue because it is not a hashcat problem/bug. This is just problem with your setup (very low amount of memory on your GPU).

**Comment by ryanwoods1706** [comment] 2018-01-03 14:13
When you tested with -m 15700 on the 1080ti, how much ram did the 1080TI have ? Also mind sending me the KDFParams of the wallet you tested on to see if its the same (forgot which of the paramaters changes how much RAM is needed) But I know that if one of the parameters of the KDFParams is "262144" as shown in the screenshot, then the RAM usage for the GPU goes through the roof

**Comment by Chick3nman** [comment] 2018-01-03 20:17
This is not a hashcat problem, your hardware is simply not adequate for cracking Scrypt with such high settings. Please take this discussion to the forums instead of github. Thanks :)

**Comment by ryanwoods1706** [comment] 2018-01-03 21:34
Hardware isn't an issue, I'm willing to go out and spend $1k/month renting a GPU server to try and crack this. However https://stealthsploit.com/2017/06/12/ethereum-wallet-cracking/ this tutorial on cracking ETH wallets, in the comments theres loads of people who have the same issue I'm having above and was told that the algorithm will NOT crack on a GPU if certain parameters are too high, hence im trying to get some help here before i go spend a grand

**Comment by jsteube** [comment] 2018-01-04 12:48
As @philsmd and @Chick3nman have explained nicely before this is not an issue. A GPU can only work advantageous compared to CPU if the SCRYPT settings are low enough (like with litecoin computation). Therefore there's no way around adding more CPU power for your algorithm if you want more speed.

**Closed as completed by jsteube** 2018-01-04 12:48 UTC
