### ISSUE TITLE
macos test problem

### ISSUE THREAD

**Issue by nijikon** [hashcat/hashcat#974] opened 2017-01-17 19:03 UTC
Don't really know if this is a problem or proper behaviour. I need to clarify.

```
bash-3.2$ hashcat -m 500 example500.hash example.dict
hashcat (v3.30) starting...

/Users/n/.hashcat/sessions/hashcat.log: m

Started: Tue Jan 17 20:00:36 2017
Stopped: Tue Jan 17 20:00:36 2017
```

Exit code is 255.

**Comment by jsteube** [comment] 2017-01-23 13:38
Since I do not have OSX I can not reproduce. Did you make sure to run "make clean" before compiling?

**Comment by nijikon** [comment] 2017-01-24 11:32
@jsteube I've added it now, but it didn't help. Here is a build log https://gist.github.com/3f2211200a574873e1b4ea3ab8d4668e

**Comment by jsteube** [comment] 2017-01-29 09:02
Can you please retry with latest github version? It's doing some detailed file permissions checks on startup, maybe it will give us some more useful debugging output. Also, what is homebrew, maybe it's related?

**Comment by philsmd** [comment] 2017-02-03 17:29
I had the chance to investigate this "issue" a little bit here: https://github.com/Homebrew/homebrew-core/pull/8655#issuecomment-277308487 .

My conclusion: this is completely unrelated to hashcat, it is just an incorrect test which doesn't respect the sandboxing rules and therefore the sandbox blocks the file read/writes.
An example of a modified test was provided within the above issue (https://github.com/Homebrew/homebrew-core/pull/8655).

I would say, that we can close this, since I don't see any misbehaving/problem from hashcat itself.

**Comment by jsteube** [comment] 2017-02-03 17:30
Thanks! Great work

**Closed as completed by jsteube** 2017-02-03 17:30 UTC
Labels: needs information / data

**Comment by neheb** [comment] 2017-02-03 20:31
Although, the : m error _is_ a problem with hashcat since strerror is not used.
