### ISSUE TITLE
LM cracking via PWDump Format Stals

### ISSUE THREAD

**Issue by mubix** [hashcat/hashcat#2752] opened 2021-04-12 02:06 UTC
I'm not sure what the issue is exactly, but when I attempt to crack the LM side of a PWDump format (from secretsdump.py of Impacket) hashfile, a single CPU spins up to 100% and never finishes. It stops at "Sorted hashes...". I have run into this on multiple versions of Hashcat, including the latest version from Git and download from the site (6.1.1), on Windows and on Linux platforms.

Unfortunately I don't have an example dump that I can share at the moment, but I'll try to generate one and provide it.

Here is the command I tried running:
```
hashcat -O -w 3 --session=mubix -m 3000 hashfile.txt -a3 -1 ?u?d?s ?1?1?1?1?1?1?1 -i
```

**Comment by Chick3nman** [comment] 2021-04-12 15:39
How many hashes are in the list?

**Comment by mubix** [comment] 2021-04-12 16:46
@Chick3nman I've had the exact same issue with a few hundred, and a few thousand, to 10s of thousands. I waited days a couple times to see if it was hung up just on sorting. It's not that I can tell. I think it's a deeper bug, but I won't be able to do much of providing that until I get some test data for ya'll

**Comment by Chick3nman** [comment] 2021-04-12 17:10
Interesting, I'll see if i can recreate this issue. I work with ntds files fairly often and haven't run into it so it may have to do with some specific pw dump parsing problem.

**Comment by mubix** [comment] 2021-04-12 19:04
@Chick3nman I only have this issue when attempting to crack `-m 3000 -a3` LM. Never with any other mode/module

**Comment by Chick3nman** [comment] 2021-04-21 07:52
There have been a number of fixes to the LM kernel since this issue was opened, can you confirm that this still happens with the latest binaries? I have been unable to reproduce this issue.

**Comment by jsteube** [comment] 2021-04-25 16:10
@mubix please update

**Comment by mubix** [comment] 2021-04-29 02:30
@jsteube / @Chick3nman apologies for the delay, the latest release from github does not fix the issue :(

**Comment by Chick3nman** [comment] 2021-04-29 05:24
Strange, i will need to see if i can recreate the stalling during startup.

**Comment by philsmd** [comment] 2021-05-17 08:11
I've investigated and was able to reproduce this problem locally and I'm now pretty confident that it has to do with `OPTS_TYPE_HASH_SPLIT` that is only used by -m 3000 = LM.

The following section of code in `src/hashes.c` is quite demanding:
https://github.com/hashcat/hashcat/blob/442a95d0ea60d0f63c6d5fe7ce2d96ea247a03e1/src/hashes.c#L1424-L1443

So it would make sense if you, @mubix, would try running hashcat (for testing purposes) with this heavy loop commented out (alternatively, one could think to test it by removing `OPTS_TYPE_HASH_SPLIT` from `src/modules/module_03000.c`, but in that case more changes are required because this flag is responsible also for actually splitting the hashes in 2 halves etc). This would be great because this way we could make sure we are really talking about the same issue and that we have correctly pinpointed it to this "split & reunite feature".

I think the main problem is that this section of code could end up in a complexity (worst case) of `2 * n * 2 * n` where `n` is the number of pwdump hash lines (the 2x comes from the 2 halves for each pwdump hash line => 4 * n^2 in total). So this is quite a huge loop which could take quite a while.

-m 1000 = NTLM doesn't have this pwdump `hash split feature` and therefore isn't affected by this problem/complexity/freeze.

As a (maybe) better alternative, we could probably think about setting these `split->split_neighbor` attributes already earlier e.g. when parsing that specific hash line or similar (I didn't investigate if this is possible/feasible/clever), instead of comparing each and every hash with each other afterwards. My educated guess is that some optimization should be possible for sure, because `4n²` could end up in quite a large loop runtime and therefore hashcat seems to be freezed at startup (but again only for -m 3000 = LM hashes and only when using the pwdump format).

Thanks

Note 1: attached is a randomly generated hash file that "freezes" for me with the current version using this command: `hashcat -m 3000 hashfile.txt dict.txt` (this of course depends on your setup / CPU power mainly, but 4 * 80000 * 80000 is already quite a huge number, so you should at least see the `Sorted hashes...` freeze for several seconds/minutes). The hashes themself of course are garbage, they are NOT intended to be useful/crackable.

Note 2: in `potfile_handle_show` (for --show) and `potfile_handle_left` (for --left) in the source code file `src/potfile.c` we have similar heavy loops that basically also have `2n * 2n` complexity (worst case).

Note 3: as a workaround you could just use the normal -m 3000 format (no pwdump file) in the meantime (by extracting only the both halves of the LM part from the original pwdump formatted line, splitted into 2 separate hash lines for both halves).

CC: @jsteube (any idea on how to fix this with minimum code change, but by decreasing the startup time/complexity a lot ?)

[hashfile.txt](https://github.com/hashcat/hashcat/files/6492258/hashfile.txt)

**Comment by jsteube** [comment] 2021-05-17 11:27
Indeed this loop is the source of the problem. When I first added it, I never thought of an LM hashlist with that many entries. It is expected that LM hashlists come from a single domain with a limited number of users. The work around you had described works well for me. It is important to note that this is not really a bug as in a software error, it's just not ideally written. After I had waited for like 90 seconds, hashcat started and worked well. And then there's the work around. I tend to close the issue unless you have additional comments or feel free to send in any improvements.

**Comment by jsteube** [comment] 2021-06-03 18:45
No response from OP, therefore closing. Feel free to reopen with comments or to send in PR with improvements.

**Closed as completed by jsteube** 2021-06-03 18:45 UTC

**Comment by baggers27** [comment] 2026-01-04 17:54
Just wondering if there is any way of getting this reopened, or should I raise a new issue? I'm running into this issue and it would be good to get it fixed if possible (I know there's a workaround but would be nicer to optimise the code). I have had a go at making changes myself in order to submit a PR and failed miserably so would appreciate some input if possible.

**Comment by mubix** [comment] 2026-01-05 05:46
Ya, I just extract the LM and split it myself as the workaround. Definitely would love to just have it be a single step. I didn't respond back in 2021 I'm not sure why but if I find the time to comment out and recompile I will.

**Comment by baggers27** [comment] 2026-08-25 20:52
Note that this was fixed under https://github.com/hashcat/hashcat/pull/4697 or commit https://github.com/hashcat/hashcat/commit/3ff4b5e3644cdcd7b3975cfb5b5cf82bae10217d - thanks!
